### ISSUE TITLE
Interface draft: Different Property Types and States still confusing

### ISSUE THREAD

**Issue by benthor** [ietf-tapswg/api-drafts#1012]
As [promised](https://datatracker.ietf.org/meeting/113/materials/minutes-113-taps-01), here follows a bit of feedback on the different Property types in the Interface draft, from the perspective of an academic developer who is currently attempting to follow the draft spec as closely as possible while trying to implement a path-aware transport system in a [statically typed programming language](https://golang.org)

In [Chapter 4 of the Interface draft](https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-transport-properties), it says:

> Transport Properties are divided into Selection, Connection, and Message Properties. Selection Properties [...] can only be set during pre-establishment. They are only used to specify which paths and protocol stacks can be used and are preferred by the application. Although Connection Properties [...] can be set during pre-establishment, they may be changed later. They are used to inform decisions made during establishment and to fine-tune the established connection. 

At this point, the reader of the document could be expected to conclude the following:

- **Selection Properties** are a set of preferences for protocol/path selection that (obviously) can no longer be meaningfully changed once a connection has been established.
- **Connection Properties** are a set of "run-time preferences" for connections which could still be adjusted when a connection is already established, but should ideally already be known during protocol/path selection

The text goes on to state:

> Calling Initiate on a Preconnection creates an outbound Connection or a Listener, and the Selection Properties remain readable from the Connection or Listener, but become immutable.

With this wording, the reader can now reasonably conclude that the original Selection Properties that have resulted in a given Connection should remain available during the lifetime of that Connection, perhaps in form of a copy of the original data structure. So far so straight forward.

In [Section 6.2](https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#section-6.2) however, this conclusion is called into question. After the text has gone on to introduce the 5 different Preference Levels, it states

> Many properties are only considered during establishment, and can not be changed after a Connection is established; however, they can still be queried. The return type of a queried Selection Property is Boolean, where `true` means that the Selection Property has been applied and `false` means that the Selection Property has not been applied.

At this point, the reader becomes confused.

- Why is the text talking about "many properties" that can no longer be changed, instead of relying on the earlier, nice and clear distinction between Selection and Connection Properties?
- Where earlier, Selection Properties were said to remain _readable_, now they are only _queryable_?
- The type of a Selection Property that has been "applied" mutates from a Preference Level to become a Boolean?
- Are "applied" Selection Properties still Selection Properties? Shouldn't they better be referred to using a different term?
- So the original Selection _Preferences_ that resulted in the current Connection are not available after all? Only the (Boolean) _Properties_ of the chosen Protocol can be "queried"?

But wait, the text goes on:

> Note that `true` does not mean that a request has been honored. For example, if `Congestion control` was requested with preference level `Prefer`, but congestion control could not be supported, querying the `congestionControl` property yields the value `false`. If the preference level `Avoid` was used for `Congestion control`, and, as requested, the Connection is not congestion controlled, querying the `congestionControl` property also yields the value `false`.

This is a complicated way of saying that the values _only_ reflect the _actual_ Properties of the chosen Connection and (in direct contradiction to the previous paragraph) do _not_ actually indicate whether a Selection Property has also been "applied" or not. (A Boolean only carries exactly one bit of information after all.)

In other words, the _Protocol Properties_ can be queried. The usefulness of this is probably limited however. If we already know that our Connection is using, e.g., TCP, we don't have to issue any "queries" to know that the Connection offers reliable transport, is subject to congestion control and preserves packet ordering. (This is indeed how I have chosen to implement this. The chosen _Protocol_ can be queried for the Properties it inherently has. In the Preconnection phase, the Selection _Preferences_ are matched against these and any `Require`/`Prohibit` conflict results in that Protocol being dropped from consideration.)

---

Hoping not to be unreasonable (or somehow block-headed), I have the following suggestions

- Either introduce a new term for Properties that have been "applied", or
- Use the term "Preferences" (e.g., "Selection Preferences", "Connection Preferences") to refer to a collection of adjustable "Settings" and the term "Properties" to refer to measured or queried values that _are_ actual Properties of underlying Connections and Protocols
- Go into a bit more detail about what the draft really means when talking about "querying" Properties (versus setting them), maybe even in terms of exemplary interactions with Property data structures. (After all, the draft elsewhere goes into considerable detail with it's exemplary Event-based system)
- Think about whether it in general would clear things up when the explicit notion of Protocol Properties as a (static) counterpoint to (adjustable) Selection Properties is introduced

**Comment by theri** [comment]
(Replying as an individual and co-author)

Thanks for raising this issue!

> With this wording, the reader can now reasonably conclude that the original Selection Properties that have resulted in a given Connection should remain available during the lifetime of that Connection, perhaps in form of a copy of the original data structure. So far so straight forward.
Yes, this matches my understanding is well.
If the later text confuses this issue for the reader, then perhaps we'll need to tweak it.

> Why is the text talking about "many properties" that can no longer be changed, instead of relying on the earlier, nice and clear distinction between Selection and Connection Properties?

I'd say that Selection Properties can no longer be changed, Connection Properties still can be changed (though maybe changing a Connection Property later would not have any effect, e.g., if Capacity Profile changes but was only taken into account when selecting a path). Perhaps the text should reflect that.

> Where earlier, Selection Properties were said to remain readable, now they are only queryable?
For me, these are synonyms, whereby a "query" is what the application has to do in order to read the properties.
Perhaps the "queried" should become "read" to avoid confusion.

> The type of a Selection Property that has been "applied" mutates from a Preference Level to become a Boolean?
That is indeed how I think of it on a conceptual level, but I understand how this might confuse implementers, especially if they can't just change a data type of a property.

> Are "applied" Selection Properties still Selection Properties? Shouldn't they better be referred to using a different term?
In the [Architecture doc](https://www.ietf.org/archive/id/draft-ietf-taps-arch-12.html#name-transport-services-implemen), we define Protocol Stack as a Transport Services implementation concept, and we talk about a certain protocol stacks providing certain features (see [Transport Features defined in the minset RFC 8923](https://www.rfc-editor.org/rfc/rfc8923).
Perhaps we could rephrase this part of the API draft to use that terminology, e.g., the application can query the actually used protocol stack and then know which Transport Features it supports.

I would strongly prefer using our existing terminology to introducing yet another term.

> So the original Selection Preferences that resulted in the current Connection are not available after all? Only the (Boolean) Properties of the chosen Protocol can be "queried"?
Good question. I vaguely remember discussing this, and I *think* folks felt like querying the Selection Properties that the application had set was not very useful at that stage.

The other text you quoted indeed sounds a bit complicated and maybe it can be reworded to be clearer.

Curious to hear what my co-authors and/or other TAPS participants think!

**Comment by philsbln** [comment]
I completely second what @theri wrote. 

With regards to querying the Transport Features selected vs. getting the preferences provided earlier, I remember we had lengthy discussions and somewhat converged to the current state. Primary arguments ware
- Multiple read/query variants are confusing
- Original Preferences are not really useful - if you really want to read them later, keep the Preferences Object
- Constrained implementations don't want to be forced to store them.

@benthor based on these arguments, what option would you prefer
a) different get/query operations of selection properties after the connection has been set up
b) the current way of "mutating" preferences with clearer description in the text

**Comment by mwelzl** [comment]
Just to add: having finally gotten around to carefully reading this, I also completely agree with everything @theri wrote. This is exactly how I would have answered, and her suggestions are exactly what I think should be done to address these comments.

I also agree with @philsbln that these were the arguments regarding querying the querying issue,  and I agree with the arguments as well.

The quoted text containing the `congestion control` example is a great catch!  Such a terribly convoluted paragraph. I have a nagging feeling that this was my fault!   :-(

**Comment by mwelzl** [comment]
PR #1033 tries to solve this; the PR itself contains a full explanation of my rationale for the changes. Please take a look!
