### ISSUE TITLE
Implementation Draft Review: Section 4.1 - Choice of terms leads to confusing language

### ISSUE THREAD

**Issue by benthor** [ietf-tapswg/api-drafts#1016]
Raising this issue as part of my review of the the Implementation Draft.

Quoting from Section 4.1 "Structuring Candidates as a Tree"

~~~~~~~~~~
1 [www.example.com:80, Any, TCP]
  1.1 [www.example.com:80, Wi-Fi, TCP]
    1.1.1 [192.0.2.1:80, Wi-Fi, TCP]
  1.2 [www.example.com:80, LTE, TCP]
    1.2.1 [192.0.2.1:80, LTE, TCP]
    1.2.2 [2001:DB8::1.80, LTE, TCP]
~~~~~~~~~~

> When an implementation views this aggregate set of connection attempts as a single connection establishment, it only will use one of the leaf nodes to transfer data. Thus, when a single leaf node becomes ready to use, then the entire connection attempt is ready to use by the application. Another way to represent this is that every leaf node updates the state of its parent node when it becomes ready, until the trunk node of the tree is ready, which then notifies the application that the connection as a whole is ready to use.

Feedback: 

- While it is understood that "connection attempt" is here used to refer to a given node in the tree, rather than the actual (stateful) process of attempting to connect to the given endpoint (using the given parameters), it does not make for easy reading.
- Similarly, it is _possible_ to grasp how an "aggregate set" can be "viewed" as "a single connection establishment", but the language could be clearer here as well.
- Couldn't an "attempt" that has succeeded and is "ready to use" be referred to differently?
- Couldn't "candidate" or "option" be substituted for "attempt" to improve readability? 

 Proposal:

> When an implementation is asked to establish a single connection, only one of the leaf nodes in the candidate set is needed to transfer data. Thus, when a single leaf node becomes ready to use, then the entire connection attempt has been successful. One way to implement this is by having every leaf node update the state of its parent node when it becomes ready, until the trunk node of the tree is ready, which then notifies the application that the connection as a whole is ready to use.

**Comment by gorryfair** [comment]
Seems quite close to me

**Comment by tfpauly** [comment]
Yes, I like this proposed text.
