### ISSUE TITLE
Review by CA - Datagram v Connectionless

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1026]
* "Connection establishment is only a local operation for a Datagram
  transport (e.g., UDP(-Lite))": I think the criterion is not Datagram
  transports but "transports without a handshake" or "connectionless
  protocols" as it is used later in the document.

**Comment by gorryfair** [comment]
I wrote, and I suggest we use "connectionless protocols" explicitly mentioning examples of UDP and UDP-Lite when used as a transport without a handshake.

**Comment by mwelzl** [comment]
To whoever plans to address this: I checked occurrences of the word "datagram" in the architecture and API drafts, and I found (only) one sentence that needs fixing on similar grounds, I think, in the API draft:

> Guidance on setting this value for datagram transports is provided in [RFC8085].

in Section 8.1.4 "Timeout for keep alive packets".   Surely the guidance regarding this matter in the UDP usage RFC is related to the fact that UDP(-Lite) is connectionless, not that it's datagram based.

**Comment by gorryfair** [comment]
Starting #1034 to fix this.
