### ISSUE TITLE
Review by CA - Final message property IsEndOfMessage event?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1028]
Framers: What is the difference between the Final message property and
  the separate IsEndOfMessage event argument?

**Comment by gorryfair** [comment]
Also there, the term MessageContext could use a definition

**Comment by mwelzl** [comment]
and searching "isEndOfMessage" tells me that there is no text describing this parameter.

Regarding the question, the difference *should* be clear: `isEndOfMessage` seems self-explanatory, whereas `Final` indicates that the Message carrying it is the last one of the Connection. So, this is End of the Message vs. End of the Connection.

**Comment by tfpauly** [comment]
Sounds like this needs a reference to the API doc, and change IsEndOfMessage to EndOfMessage to match the API.

**Comment by tfpauly** [comment]
Probably fix with #1029
