### ISSUE TITLE
Review by CA - Is there formal language or pseudocode?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1029]
Framers: The <tt> paragraphs in Defining Message Framers and later
  might be formal language or pseudocode, I can't tell. It might help if
  the introduction stated something around names and signatures of
  signals and functions being expressed in pseudocode, and that
  identifiers in implementations are expected to be similar to those but
  following the conventions of the language

**Comment by tfpauly** [comment]
We should reference section 1.1 of the API document which defines the notation used.
