### ISSUE TITLE
Evaluate the applicability of §6.3 to ICE-like protocols

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#103]
editor's note from pre-00:

> This API is sufficient for TCP-style simultaneous open, but should be considered experimental for ICE-like protocols.

This didn't seem like something we need in -00, so opening this issue to make sure it doesn't get lost...

**Comment by britram** [comment]
@csperkins is there a chance we can get to this in the next week or so, or shall we push it to ietf-01?

**Comment by csperkins** [comment]
I think push it to the ietf-01 milestone. If we're prioritising work in this space, #127 is not urgent.

**Comment by tfpauly** [comment]
Side meeting: closing until we have a need to change this

**Comment by britram** [comment]
this actually seems done in the document
