### ISSUE TITLE
Review by CA - ConnectionError additional info

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1031]
* UDP, ConnectionError: Would those soft errors contain additional
  information about the ICMP error code, and can an application expect
  to find the (partial) original datagram in the error?

**Comment by gorryfair** [comment]
This is a good question! - on the one hand, the additional info can be valuable - for example to validate an ICMP message, as suggested for validating ICMP for a DPLPMTUD probe - but on the other hand, this info is often not provided by existing APIs.

**Comment by chrysn** [comment]
I figure that a practical thing to state would be that the information is provided if it is accessible on a platform.

Having text that describes this as matter of implementation quality would help TAPS implementers push for (eg. MSG_ERRQUEUE style) provisions in their platforms.

**Comment by tfpauly** [comment]
If the system makes this information available, we could mention that you could pass it up.

**Comment by gorryfair** [comment]
See a proposal in  #1052

**Comment by mwelzl** [comment]
The pointer to the PR with the specific proposal to address this issue got a "thumbs up" from the @chrysn who wrote the review. So, this PR should have closed this issue. Doing it manually.
