### ISSUE TITLE
Review by CA - Which ICMP to forward for Multicast?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1032]
(More out of curiosity, with no expectation that this would find its
  way into the text unless you think I've hit a bug): In UDP Multicast
  Receive, which kind of ICMP notifications can come in there that would
  constitute a ConnectionError -- given that this transport does not
  send (and would thus usually not trigger any)?

**Comment by tfpauly** [comment]
Section 10.4 for multicast receive mentions ICMP errors. You could have errors on initiate for joining a multicast group, etc, but it likely doesn't make sense to have ICMP errors mentioned here.

**Comment by gorryfair** [comment]
Suggest we can close this issue.
