### ISSUE TITLE
Art-art review by Bron Gondwana: normative language

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1037]
Two items here:

1.

>   The implementation stores these properties as a part of the
>   Preconnection object for use during connection establishment.  For
>   Selection Properties that are not provided by the application, the
>   implementation must use the default values specified in the Transport
>   Services API ([I-D.ietf-taps-interface]).

Normative MUST?  I guess this is just a guidance document so doesn't need
anything normative.  There's some later "should" as well which I would
generally ask the same question for.

2.

>   Upon receiving this event, a framer implementation is responsible for
>   performing any necessary transformations and sending the resulting
>   data back to the Message Framer, which will in turn send it to the
>   next protocol.  Implementations SHOULD ensure that there is a way to
>   pass the original data through without copying to improve
>   performance.

but... here we have some NORMATIVE language.  That SHOULD should probably be
non-capitalised to align with earlier usage.  (and so on later in the document,
e.g. in the SCTP description)

**Comment by tfpauly** [comment]
The first one can just be "uses the default values", without normative text.

Second one can be lowercase as well. SCTP has normative SHOULDs and MUSTs that can be removed.
