### ISSUE TITLE
Refer to all properties by their name, not the section title

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1040]
Examples:

> A connection can not be used
>   for sending if the connection was created with the Selection Property
>   `Direction of Communication` set to `unidirectional receive` or if a Message
>   marked as `Final` was sent over this connection.
> 
should be:
> A connection can not be used
>   for sending if the connection was created with the Selection Property
>   `direction` set to `unidirectional receive` or if a Message
>   marked as `Final` was sent over this connection.
> 

, and:

> The Transport Services API provides two properties to allow a sender
> to signal the relative priority of data transmission: the Priority Message
> Property {{msg-priority}}, and the Connection Priority Connection Property
> {{conn-priority}}.

should be:

> The Transport Services API provides two properties to allow a sender
> to signal the relative priority of data transmission: the `msgPriority`
> Message Property {{msg-priority}},
> and the `connPriority` Connection Property
> {{conn-priority}}.

...and many more. Thoughts?  This is a large and painful effort, so I'm checking first  :)

**Comment by abrunstrom** [comment]
We have referred to the section titles? I agree this is incorrect and we should refer to the name of the property. I am surprised no one has noticed this before.

**Comment by mwelzl** [comment]
It dates back to a time before we introduced the names, but I agree it's surprising that noone noticed it.

**Comment by tfpauly** [comment]
Interim: let's do this for API draft, yes.

**Comment by mwelzl** [comment]
Yesterday, I said "I can do this tomorrow". Oh how naive. This is just to apologize - it will take longer... sorry!
