### ISSUE TITLE
Does Connection.clone() cause a ConnectionReceived<Connection> event at the peer?

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/api-drafts#1049]
If `Connection.clone()` is called, is an unsolicited `ConnectionReceived<Connection>` event generated at the peer? I assume so, but can't find it documented.

**Comment by csperkins** [comment]
I'd expect a `ConnectionReceived<Connection>` event to be delivered before an event indicating arrival of data on the new connection. That could be immediately before, if there's no explicit on-the-wire signalling that the new connection has been created.

**Comment by mwelzl** [comment]
Ah, ok!  I agree it should happen as you describe it, and I'll take care of this: I'll check if this is already covered (and if so, if the text should be more explicit about it). If it isn't covered, I'll add text to state this.
