### ISSUE TITLE
FG: Local Endpoint candidates

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1054]
Some comments/feedback on the aforementioned I-D:

* Section 4.2.1.1. Local Endpoint candidates

You should probably consider PCP/UPnP here. see e.g. https://www.ietf.org/id/draft-gont-v6ops-ipv6-addressing-considerations-02.html#name-support-for-firewall-traver

**Comment by gorryfair** [comment]
Is there a stable reference - rather than an individual ID we should cite?

**Comment by tfpauly** [comment]
I'd rather not call out non-standard protocols like UPnP here.

**Comment by gorryfair** [comment]
I understand. That appears to support not including this reference. Is this issue ready to be closed?

**Comment by britram** [comment]
I'd concur with closing.

**Comment by gorryfair** [comment]
So, closing this with no update.
