### ISSUE TITLE
FG: listeners - port usage

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1056]
Added based on TAPS WG input from FG:

> 4.7. Implementing listeners When an implementation is asked to Listen, it registers with the system to wait for incoming traffic to the Local Endpoint. If no Local Endpoint is specified, the implementation should use an ephemeral port.

Note: there are implications of using a port number from the ephemeral
port range. See e.g. Section 3.1 of
https://www.rfc-editor.org/rfc/rfc6056.html#page-8

TL;DR; The general idea is that one should use the same range to pick
port for outgoing connections than to pick ports for listening endpoints.

> If the Selection Properties do not require a single network
> interface or path, but allow the use of multiple paths, the Listener
> object should register for incoming traffic on all of the network
> interfaces or paths that conform to the Properties. The set of
> available paths can change over time, so the implementation should
> monitor network path changes, and change the registration of the
> Listener across all usable paths as appropriate. When using multiple
> paths, the Listener is generally expected to use the same port for
> listening on each.

I'd probably stress this a bit more e.g., quite often the port needs to be registered somewhere (e.g., directory service), so having different ports for each interface would seem problematic.

**Comment by gorryfair** [comment]
This seems like good, but general advice on port usage, I'm not sure that new text is needed to discuss these issues in the API. I propose we close this with no update?

**Comment by mwelzl** [comment]
With three people (including myself) agreeing that we should close this with no text update, as the suggestion is only to point at general advice on port usage, I'm closing this now.
