### ISSUE TITLE
Capitalization of function parameters

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#1068]
From discussion on #1063 

> ...we do the same with other capitalized terms too, here and in the API draft - e.g., "messageContext". Should we generally agree to begin terms with a lowercase letter when they are used as parameters in code examples? I think we have this in most places, though at least the API draft has several counterexamples... e.g., the server example code:
> 
> Preconnection := NewPreconnection(LocalSpecifier,
> TransportProperties,
> SecurityParameters)

**Comment by mwelzl** [comment]
This was a mistake. As I wanted to do this now, I noticed that all occurrences of capitalized terms as parameters are objects that are defined and used elsewhere in the code examples. For example:

Preconnection := NewPreconnection(RemoteSpecifier,
                                  TransportProperties,
                                  SecurityParameters)

refers to RemoteSpecifier etc., being objects that are initialized some lines above. Making them appear in lower case everywhere would be awkward, this is then a much more drastic change to our pseudocode.

As a result, I think it's fine to leave things as they are, and I suggest to close this issue with no action.
