### ISSUE TITLE
Discussion about impact on the architecture when the minset expands 

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1081]
https://github.com/ietf-tapswg/api-drafts/blob/9266fbe3b55966edaf4013e755d46ae6f0fed8de/draft-ietf-taps-arch.md?plain=1#L226

Assuming there would be more protocols in the future and the minset functionalities will expand via extension or amendments. It would important to indicate if this architecture should is also extensible or it only supports on the minimum set referred. Definitely we haven't seen the future yet, but it would be important to express if we have considered such expansion of minimum functionalities.

**Comment by gorryfair** [comment]
To me, the current spec is based on minset that describes the common functions. So, the addition I would expect here is to say that there can be extensions and protocol-specific features.

**Comment by tfpauly** [comment]
I expect that if a common feature is added to the minset, then the architecture and API surface would also be extended to match.
