### ISSUE TITLE
relation between path property change and system policy

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1087]
https://github.com/ietf-tapswg/api-drafts/blob/9266fbe3b55966edaf4013e755d46ae6f0fed8de/draft-ietf-taps-arch.md?plain=1#L441

Should any change in path properties not be trigger any event towards the system policy module?

**Comment by gorryfair** [comment]
I don't think we talked about that explicitly (others might recall more), however, to me it seems very reasonable that a change of path properties would result in notifying the system policy module of this change.

**Comment by philsbln** [comment]
We always considered the interaction between TAPS implementation and the system policy as implementation specific and, thus, out of scope. If we add it here, we will need to also add it in a couple of other places and potentially rathole into writing a fourth document about policy considerations.

**Comment by zaheduzzaman** [comment]
Well the box is there, so it needs some description of it's existence and relation with others. If we consider the details are out of scope of this architecture then we need to be explicitly saying that.

**Comment by abrunstrom** [comment]
I do not think a path change will change the system policy. It may update the cached state, but this is not part of the event handling, so I do not think we should add anything about it here.

The System Policy, as well as Cached Sate, is covered in the Implementation section. If anything more is needed, it should be described there. 

> System Policy: Represents the input from an operating system or other global preferences that can constrain or influence how an implementation will gather candidate paths and Protocol Stacks ({{gathering}}) and race the candidates during establishment ({{racing}}). Specific aspects of the System Policy either apply to all Connections or only certain ones, depending on the runtime context and properties of the Connection.

Do we really need more here?

**Comment by gorryfair** [comment]
The text could mention that this can include  information about the lower layers, such as the capabilities of  interfaces and the capabilities  of attached networks that have been cached or are known to the system.

**Comment by gorryfair** [comment]
I added some lines of text in PR #1110, which tries to not leave the diagram blocks disconnected from the text.

**Comment by gorryfair** [comment]
Some lines with context are now merged, together with a glossary for the whole document (It was on a previously abandoned nice to-do list for a while, but I finally integrated it here).
@zaheduzzaman - do these changes help and do you wish more?

**Comment by zaheduzzaman** [comment]
It is better than before, thanks. lets close this issue.
