### ISSUE TITLE
Application expectancy on cached state

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1089]
https://github.com/ietf-tapswg/api-drafts/blob/9266fbe3b55966edaf4013e755d46ae6f0fed8de/draft-ietf-taps-arch.md?plain=1#L480

I think we should be very specific that the application SHOULD not expect certain caching behavior or MAY expect a minimum set of information cached.

This is also related to the expectancy from application to expect same protocol given same properties and security parameter each time. will such input generate same consistent out put from one TAPS system?

**Comment by gorryfair** [comment]
I suggest adding this explicitly - something like: This caching does not imply that the same decisions are necessarily made for subsequent connections, rather, it means that cached state is used by the Transport Services architecture to inform functions such as choosing the candidates to be raced, selecting appropriate transport parameters, etc.

**Comment by gorryfair** [comment]
See PR on request required properties #1115, which could close this issue.

**Comment by gorryfair** [comment]
Thought resolved by merged PR in latest editor version.

**Comment by gorryfair** [comment]
@zaheduzzaman Does the merged text in master address issue #1089?

**Comment by zaheduzzaman** [comment]
LGTM, Thansk.
