### ISSUE TITLE
Keep all the requirements in the same place

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1090]
https://github.com/ietf-tapswg/api-drafts/blob/9266fbe3b55966edaf4013e755d46ae6f0fed8de/draft-ietf-taps-arch.md?plain=1#L544-L546

This I believe is already covered in section 3.3.

https://github.com/ietf-tapswg/api-drafts/blob/9266fbe3b55966edaf4013e755d46ae6f0fed8de/draft-ietf-taps-arch.md?plain=1#L552-L553

why this should not be moved to section 3.3 ?

**Comment by zaheduzzaman** [comment]
Any thoughts here?

**Comment by tfpauly** [comment]
We did this intentionally to make sure the security considerations had the normative language there. I personally find it OK to have it both places. @zaheduzzaman are you OK with no change?

**Comment by gorryfair** [comment]
(We could of course note in one sentence that the requirements for security are provided in the security considerations section).

**Comment by tfpauly** [comment]
I added a reference back to 3.3, and made the MAY be a can. So that takes care of the second point. However, the first point with the cert reference I don't think is covered in 3.3, and should remain in security.

**Comment by tfpauly** [comment]
@zaheduzzaman

**Comment by zaheduzzaman** [comment]
seems like I missed all the call out for me.. this has been strange that I don't get any emails about my mentions and comment's reply. This is only happening in case of TAPS github.

anyway, changes are OK with me.
