### ISSUE TITLE
Some minor comments on architecture document

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1091]
These comments are good to be addressed to improve the document, however, they can be done as part of IETF last call as well

> Please put forward ref to major concepts that are later defined in the document when using earlier than defined. This would avoid unnecessary confusions and misinterpretation. There are already good examples of such forward reference in the document. The ask here is to be consisted with that. 

> "the nature of the interaction over networks" has been one of the motivations for asynchronous event driven TAPS API , I think it would be great to provide some details of the nature of the interaction over networks so that readers are on the same page.

> Can we mention in section 2.2 that a packet might content more than one messages? This will make the 2nd bullet of the benefits more appealing.

> The last paragraph of section 2.2 would be better to split into the benefit bullets.

> Can we define the term like "protocol racing"?  

> Section 4.1 : looking at the architecture figure - "state is torn down in the transport" should this be connection instead of transport?

> Section 4.1.2 : I would describe the object first and then the transport properties. In the current arrangement when properties are described it mentions Connection which is described just later. Also transport properties here are kind of repetition of what we have in Section 3.1.

> Section 4.1.7 : a ref to the "half-close" concept would be helpful, as we are not defining it.

**Comment by gorryfair** [comment]
Fixes proposed in PRs #1110, #1111, #1112, #1113, #1114
