### ISSUE TITLE
Diff between protocol specific properties and protocol properties

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1101]
https://github.com/ietf-tapswg/api-drafts/blob/c70520fb819813d22024a3587bd3f8d4134cc344/draft-ietf-taps-interface.md?plain=1#L1945-L1952

Are Protocol Specific Properties and Protocol Properties same or different?

Also note that we are first time defining the Protocol Properties in the interface document ( described along with Connection Properties) and not introduced in the architecture document. I think we should be clear about what we are defining where and describing where. I would suggest use of cross reference rather describing everything again and again, which might create confusion and inconsistency.

**Comment by mwelzl** [comment]
Oh, this seems like a mistake (great catch, thanks!) - "Protocol Properties" don't exist, I think we only have "protocol-specific Properties".

**Comment by zaheduzzaman** [comment]
I caught this when reading the implementation doc. So it should be fixed there as well.
