### ISSUE TITLE
Ranking criteria for Protocol Option not described

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1102]
https://github.com/ietf-tapswg/api-drafts/blob/c70520fb819813d22024a3587bd3f8d4134cc344/draft-ietf-taps-impl.md?plain=1#L289

I think we should add a similar ranking consideration description as we have for Network paths. Otherwise, I am not sure how to rank the protocol option.

**Comment by abrunstrom** [comment]
I think here as well that the options should be ranked based on preference, system policy, and performance. I made a pull request to add it.

**Comment by zaheduzzaman** [comment]
LGTM, lets of others have any opinion about it..

**Comment by mwelzl** [comment]
I agree with @abrunstrom
