### ISSUE TITLE
Protocol option examples are hard!!!

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1107]
https://github.com/ietf-tapswg/api-drafts/blob/9a98252f1b9c790a17df01f1ed9be458bfb2ea3d/draft-ietf-taps-impl.md?plain=1#L302-L317

We have given example but we haven't really defined how
 the format should be written or how one should interpret in the
example. Here "Any Stream" means any protocol that supports
streaming ... but it would take quit some time to get to that point . It is also confusing that an "Any" is used with comma (,) and another is without a
 comma... 

To understand the example correctly, I suggest we either keep the examples on to a level where this is already described or describe how we are formatting the expression in this document as we described tree
structure with numeric ( for example 1 , 1,1 ).

**Comment by abrunstrom** [comment]
Perhaps we can just write HTTP and Stream without the Any part? Alternatively we could add a specific interface, e.g Wi-Fi, to avoid the first Any. And then also clarify the description of the example and what is raced. 

The notation is described earlier in the text, so I assume that is not the problem?

**Comment by zaheduzzaman** [comment]
If you propose the changes then I can perhaps understand it better about the modified example.

**Comment by philsbln** [comment]
@zaheduzzaman does PR #1119 solve the issue for you?
