### ISSUE TITLE
Implementing Listeners for MUXed protocols

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1141]
4.7.3.  Implementing listeners for Multiplexed Protocols

   If the
   abstraction of Connection presented to the application is mapped to
   the multiplexed stream, then the Listener should deliver new
   Connection objects in the same way for either case.

What controls the condition "If the ... Connection is mapped to
[i.e. represents] a multiplexed stream ..."?  It seems to me that
there is either a blanket rule (e.g. SCTP streams are always presented
as individual Connections) or there is a setting in the Listener.  In
either case, this is described somewhere in the TAPS API definition,
and a reference should be given here.

   The
   implementation should allow the application to introspect the
   Connection Group marked on the Connections to determine the grouping
   of the multiplexing.

The meaning of "should allow" is not clear.  I would expect that the
API is specified to set Connection Groups for all sets of Connections
that share a multiplexed lower-level protocol, and the API has a
defined mechanism for accessing the Connection Group of a Connection.

For some multiplexed protocols (e.g. QUIC), once the connection is
established, either end can initiate new streams.  This means that the
TAPS client may need a way to provide Listener service.  Does the TAPS
API define how this happens?  And if so, have you checked that the
various passages of this document that refer to Listeners cover
client-end Listeners correctly?

***
From the review by Dale Worley: https://mailarchive.ietf.org/arch/msg/last-call/bpBk8QxZMLksr3ZuROtf2_BXYdI/
Note that indentation was lost by copy+pasting here - look at the edited version or the version at the URL to get a clearer view of what is being quoted.

**Comment by tfpauly** [comment]
"If the
abstraction of Connection presented to the application is mapped to
the multiplexed stream"

- QUIC would map the Connection to the multiplexed stream
- TCP wouldn't, since it doesn't have a multiplexed stream

**Comment by tfpauly** [comment]
Suggestion to just make this "When the abstraction..."

**Comment by mwelzl** [comment]
... needs checking in the API doc, to then state clearer under what conditions MUXing can happen.

**Comment by mwelzl** [comment]
A few things here:

- in yesterday's meeting, @abrunstrom said that this only happens when Clone is called, and I said that such MUXing could also happen automatically. I was wrong: the API is clear, it would indeed only happen upon Clone. Clone is not guaranteed to yield MUXing (e.g., when the underlying protocol can't do it), and the Selection Property `multistreaming` can be used to state a preference for this to happen.
- on the passive (Listener) side, this is not controlled by the application, however: connections just "arrive". We only expose multi-streaming via the Connection grouping. Hence, the rule must be: if a new stream is being used, this must be presented to the application as a new Connection (which is grouped with the other ones that are already MUXed on the same underlying connection).
- The current first sentence of this paragraph also doesn't make sense to me: "Protocols that provide multiplexing of streams into a single four-tuple can listen both for entirely new connections (a new HTTP/2 stream on a new TCP connection, for example) and for new sub-connections (a new HTTP/2 stream on an existing connection)." - how can "a new TCP connection" be an entirely new connection **of a protocol that provides multiplexing of streams**? I therefore changed this in PR #1166.
- Regarding the sentence: "The implementation should allow the application to introspect the Connection Group marked on the Connections to determine the grouping of the multiplexing."  I agree that this should be in the API, where it is: one can query by calling Connection.GroupedConnections(). So, then, the quoted sentence is just unnecessary in the implementation draft. PR #1166 removes it.
- Regarding this: "For some multiplexed protocols (e.g. QUIC), once the connection is established, either end can initiate new streams. This means that the TAPS client may need a way to provide Listener service. Does the TAPS API define how this happens?".  This is nothing special in the API: upon listening, the application gets a Connection, and there is nothing stopping the application from later calling "Clone()" on it - which should then have this effect in case of QUIC.
- Regarding this: "And if so, have you checked that the various passages of this document that refer to Listeners cover client-end Listeners correctly?" ... I have checked for occurrences of "Listener" and found nothing that needs changing.
