### ISSUE TITLE
Connection termination

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1149]
8.  Implementing Connection Termination

I think this section needs substantial revision.  As far as I can
tell, the core of it is "Once you send a close on an SCTP connection,
any data in flight from the remote end will be lost, so in TAPS, the
semantics of a reliable, bidirectional, byte-stream connection are
that once the application calls Close, any data in flight from the
remote end MAY be lost."  As a design choice, I would argue against it
(and that the implementation cover over that SCTP behavior), but I
assume the authors know better than I do.

However, it's critically important that this is stated in the API
definition, as the application writer might not expect that property,
and certainly can't be expected to read the implementation
documentation to discover that it doesn't get quite as good service as
TCP provides.

Once that is done, this section can be reduced to mentioning that
because the API permits the loss of tail-end data, a reliable,
bidirectional, byte-stream connection can be mapped directly to an
SCTP stream.

***
From the review by Dale Worley: https://mailarchive.ietf.org/arch/msg/last-call/bpBk8QxZMLksr3ZuROtf2_BXYdI/
Note that indentation was lost by copy+pasting here - look at the edited version or the version at the URL to get a clearer view of what is being quoted.

**Comment by mwelzl** [comment]
I'll check just in case but I'm *really* sure that we cover this in the -interface draft (and I don't think we want to re-iterate discussing whether the specific behavior problematic).

**Comment by gorryfair** [comment]
Sect 10 of API sayeth:
_Close terminates a Connection after satisfying all the requirements that were specified regarding the delivery of Messages that the application has already given to the Transport Services system. Upon successfully satisfying all these requirements, the Connection will send the Closed Event. For example, if reliable delivery was requested for a Message handed over before calling Close, the Closed Event will signify that this Message has indeed been delivered. This Action does not affect any other Connection in the same Connection Group.

**Comment by mwelzl** [comment]
Ok... that's indeed not enough IMO.

**Comment by mwelzl** [comment]
I agree about reducing this section - most of the text can be thrown out; however, I don't think it helps the reader to say here (as suggested) that, due to the stricter semantics, we can map to an SCTP stream.

There is text there that suggests to use SCTP Stream Reset as an indication that a stream is "closed", such that the peer's Transport Services System can inform the application. I think this is important to keep.
