### ISSUE TITLE
Comment from Ops area review

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#1176]
The draft describes the methods (APIs) for applications to call Transport
services.

It would be nicer if adding a comparison with the existing methods to call
TCP/UDP services, such as on Linux you can call connect() to the TCP-socket, or
use write(), etc.

**Comment by abrunstrom** [comment]
Making a pass in the mail archive to see that we have not missed any of the feedback. I do not agree with this comment as I think adding comparisons are out of scope. Adding it as an issue just to note that we have seen and considered it. 
@tfpauly if you agree it is out of scope we can close with no action.

**Comment by tfpauly** [comment]
I agree that this is out of scope for the current documents

**Comment by mwelzl** [comment]
I also agree that this is out of scope.
