### ISSUE TITLE
API presentation language

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1180]
_From Genart review: https://mailarchive.ietf.org/arch/msg/taps/L7_Aopnvp-xn9aEQ_zI9kgxts68/_

Internationalisation-related concerns are minimal.  Though maybe
something could be explicitly said about the parts of the API that can
become visible to human eyes, e.g., Message Contexts, and SendError
reasons.

Not a blocking issue - because in general the meaning can be inferred
quite easily - but I've found the typographic conventions to be not
super clear / consistent.  Some times input parameters are exemplary
(e.g., "https", 443), other times they are given generic names (e.g.,
GroupAddress).  It'd be probably neater if the API were described more
formally in terms of their (abstract) input and output types to prevent
the reader from inferring the wrong signatures.  Also, examples could
use a more self-consistent pseudo-code convention, but as per premise,
this is not blocking.  However, I'd suggest the authors to do a pass on
the whole document and see if they see opportunities to improve the API
presentation language.

**Comment by mwelzl** [comment]
I don't understand what these internationalisation-related concerns are - how is "Message Context" related to internationalisation?

Regarding typography, we have made at least one major consistency pass since this review happened; I suggest to leave this as is.

**Comment by britram** [comment]
Agreed, closing with no action.
