### ISSUE TITLE
HTTPS + raw PK

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1184]
_From Genart review: https://mailarchive.ietf.org/arch/msg/taps/L7_Aopnvp-xn9aEQ_zI9kgxts68/_

HTTPS with raw public keys is not a great match ;-)
What about using a PK cert rather than raw PK?

**Comment by britram** [comment]
This seems to be referring to the example in Section 3.1; I think the right thing to do here is to remove key-pair from this example, because the certificate is covered by the identity parameter IIUC.

**Comment by mwelzl** [comment]
Ah yes, I dropped the section heading by accident, sorry - it points at 3.1.1
