### ISSUE TITLE
Example in section 3.1.2

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1185]
_From Genart review: https://mailarchive.ietf.org/arch/msg/taps/L7_Aopnvp-xn9aEQ_zI9kgxts68/_

I have found this example to be rather puzzling.  It looks to be sending
the same message on two different connections to the same HTTPS endpoint
at roughly the same time.  What is the use case for this?  Also, I
couldn't tell whether the same output buffer is used for both responses,
which added to my confusion.

The in last para:

  "Preconnections are reusable after being used to initiate a
   Connection.  Hence, for example, after the Connections were closed,
   the following would be correct:"

the positioning of "for example" is slightly ambiguous: it is not clear
whether it is necessary that all connections derived from a given
preconnection are closed before one is able to call Initiate() again, or
not.
Could you please clarify this aspect?

**Comment by mwelzl** [comment]
I assigned this to Tommy just for the heck of it: perhaps he CAN give an example use case   :-)
Regarding the thing with Initiate(), I think we clearly want it to be possible to derive connections from preconnections irrespective of closing the connections before or not... so yeah, let's just rephrase this a little bit.

**Comment by tfpauly** [comment]
I don't think it's about sending the same messageDataRequest message on both connections, it's just saying you can set up both connections and use them...

**Comment by mwelzl** [comment]
Ah, easy - I think what's needed is something along the lines of:
"Hence, for example, whether the Connections were closed or not,
the following would be correct:"

(now I'm not sure if this is a beautiful phrase - which is why I delegated it  :)   but semantically, I think that's what he's asking for - the mention of closing Connections gives the impression that this might be needed)
