### ISSUE TITLE
s/SHOULD/MUST regarding multiple remote endpoints

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1188]
_From Genart review: https://mailarchive.ietf.org/arch/msg/taps/L7_Aopnvp-xn9aEQ_zI9kgxts68/_

Section 6:

5th para: why SHOULD and not MUST? Specifically, when is it OK for
multiple remote endpoints to represent different services?

**Comment by mwelzl** [comment]
Assigning @tfpauly because I have a feeling that, if anyone, he would have wanted this to be a SHOULD.

Perhaps it's just a mistake that happened though. I also think this should be a MUST. What's the counter-example?

**Comment by tfpauly** [comment]
Well I think the reason it might fail to be met is that you might think that something is the same service, but it actually isn't — since the discovery mechanisms can be imperfect.
