### ISSUE TITLE
Section 6.1 "withport" example

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1189]
_From Genart review: https://mailarchive.ietf.org/arch/msg/taps/L7_Aopnvp-xn9aEQ_zI9kgxts68/_

Maybe use 4443 for WithPort(): I guess one would normally use
WithService("https") if they want to use the standard port for the
service, and WithPort(...) only for alternative/non-default.

# 6.1.4

Same comment as before with regards to WithPort().

**Comment by britram** [comment]
Agreed, closing with no action.
