### ISSUE TITLE
Rendezvous sentence in section 4.1.4

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1213]
From the [INT directorate review](https://datatracker.ietf.org/doc/review-ietf-taps-arch-18-intdir-telechat-volz-2023-08-25/) by Bernie Volz:

“If successful, the Rendezvous call returns a Connection object to represent
the established peer-to-peer connection.”

Doesn’t sound very asynchronous, especially because of “established” which
implies it could take some time?

**Comment by csperkins** [comment]
"generates and asynchronously returns"? Although, tbh, the language isn't that different to that we use elsewhere.

**Comment by gorryfair** [comment]
Seems better, added to PR #1235
