### ISSUE TITLE
BCP14 language

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1220]
From the review by Éric Vyncke, INT AD:

## Section 3.1

The presence of normative BCP14 terms ("SHOULD", ...) in an architecture
document looks weird to me (see my DISCUSS point above). Is this document an
'architecture' document or an 'architecture and requirements' one ?

**Comment by gorryfair** [comment]
We arrived at the name of this draft "arch" quite some while ago, but if it serves us better we could change the title - at least just a little to align with the chosen status and the inclusion of the requirements for the system. 
For example, we could entitle this the Transport Services System ... if we wanted to do that, with very few changes.

**Comment by csperkins** [comment]
I'm not sure I see expressing normative requirements to conform to an architecture as weird.

**Comment by gorryfair** [comment]
To put another way, these are requirements to build this transport system, i.e., what needs to be done to make this work, rather than a list of requirements to change something that exists.

**Comment by britram** [comment]
I'm not stylistically thrilled about adding "and requirements" to the title, but it's not wrong in the strictest sense, and it's (far) better than pulling the normative terms into the API doc.
