### ISSUE TITLE
"Safely" in "safely swapping or racing stacks"

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1221]
From the review by Éric Vyncke, INT AD:

## Section 3.3

What is the exact meaning of 'safely' in `Equivalent Protocol Stacks can be
safely swapped or raced in parallel` ?

**Comment by gorryfair** [comment]
It would be a good start to say that they have identical (?) security properties....

**Comment by gorryfair** [comment]
See also:  Issue #1248
