### ISSUE TITLE
A wording detail in Section 4.1.4

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1222]
From the review by Éric Vyncke, INT AD:

s/Establishment (Section 4.1.4) focuses on the *actions* that an application
*takes on* the connection objects/Establishment (Section 4.1.4) focuses on the
*requests* that an application *sets to* the connection objects/ as it is not
really the application doing those actions ?

**Comment by gorryfair** [comment]
See #1235

**Comment by mwelzl** [comment]
#1235 doesn't do this, but I also don't think we should do this. Actions are defined in the TAPS documents, they are essentially function calls of the API - and "Establishment" refers to these function calls (I can tell that Éric wasn't thinking in terms of our nomenclature, but about actually carrying out an "action" related to a connection, and he's trying to say that instead, the application just delegates).

Instead "setting a request" is a concept that we don't have. So, altogether, I think we should leave this unchanged, as #1235 does.

Whoever agrees, should close this issue  :-)
