### ISSUE TITLE
What about DNSSEC or DoH?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1224]
From the review by Éric Vyncke, INT AD:

## Section 4.1.3

Do the security parameters include DNS resolution security parameters ? E.g.,
mandatory use of DNSSEC or DoH?

**Comment by gorryfair** [comment]
I think this ought to be more cleae. To me, an equivalent stack (i.e. a candidate for racing) needs to have equivalent security properties. If any property is required, then it must be present to be offered as a candidate. The Transport Services system does not dictate what the default system policy is, but a default could require a specific security property.  Is this a good start at a short PR?
