### ISSUE TITLE
"Connection" capitalisation

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1227]
From the review by Éric Vyncke, INT AD:

## Section 2

Is a capitalised "Connections" required in `the interface for an application to
create Connections and transfer data` ? Or should there be a text in the
glossary section about the use of capitalised terms ?

**Comment by gorryfair** [comment]
Unsure what is needed, if any, to fix this:  Connection" is defined in the glossarty.

Along with text that says: " this document (and other Transport Services documents) use the capitalized "Connection" term, it refers to a Connection object that is being offered by the Transport Services system, as opposed to more generic uses of the word "connection"."

**Comment by gorryfair** [comment]
Fixed in PR
