### ISSUE TITLE
nits in Section 2.1

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1228]
From the review by Éric Vyncke, INT AD:

## Section 2.1

s/all interaction using the Transport Services API is expected to be
asynchronous/all interactionS using the Transport Services API ARE expected to
be asynchronous/ ?

**Comment by gorryfair** [comment]
I can read this either way, but I do see the text here can be improved, see a PR #1235

**Comment by mwelzl** [comment]
This looks unnecessary to me, both versions seem correct to me and convey the same meaning.
