### ISSUE TITLE
Editorial comments

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1233]
Some of these were categorized as "nits" and others not - I took the liberty of categorizing them all as "editorial", which, I think, they are. I thought twice only about the "Messages are sent in the payload of IP packet." comment, but I believe that's just a matter of writing "Messages are sent as part of the payload of an IP packet." instead.

(interestingly, not even the comment mentioned the missing article in this sentence?  :-)   )

So, over and out from Michael, and handing over to ...

From the INT review by Erik Kline:

### S1.4

* "Racing: ... along with any security parameters"
 Should this be "Security Parameters" (caps) to refer to the
 subsequent definition?

### S2.1

* "generally uses a try-and-fail model"

 I'm not so sure about "generally"; mostly I've seen apps use a
 kernel-assisted callback style (select/poll/epoll/kqueue/...).

 It's probably not worth spending too much time trying to recraft
 text, but if it seems relevant to mention perhaps give it some
 thought.

### S4.1

* s/connection object/Connection Object/g or
 s/connection object/Connection object/g?

### S4.1.5

* "Messages are sent in the payload of IP packet."

 What does this mean in the context of a TCP-TLS transport or
 a transport using a Framer?

 A Message will indeed be _somewhere_ in the payload section
 of an IP packet, but the statement as written might be construed
 as a Message occupying the entirety of the payload, I think.

### S4.2.3

* Should the definitions in Section 1.4 contain an entry for
 Connection Context?

* Should Figure 3 contain some indication of where a Connection
 Context fits?

### S1.4

* "such as a hostnames or URL":
 s/hostnames/hostname/ or
 s/a hostnames/hostnames/

### S4

* Consider putting a box around "Network Layer Interface" in
 Figure 3, for consistency with Figures 1 & 2.

**Comment by mwelzl** [comment]
@gorryfair accidentally addressed this with a commit to the master ( https://github.com/ietf-tapswg/api-drafts/commit/317c9efd8fe3a4b666b78c1a12a884d2c4b73529 ), and asked me to check. If I number the bullets above from 1-8:

* The commit addresses 1, 2, 3, 5, 7. Items 4, 6, 8 are still missing: that's the comment about payload, and the two that refer to figure 3.
* The commit introduces a nit: simply search for "the Socket API can uses" to fix (should be "use").

**Comment by gorryfair** [comment]
/uses/uses/, /Connection object/ was fixed in PR #1235. Network Layer Interface was resolved in fig 3.

I did not add extra on existing mechanisms in either PR. See next.

**Comment by gorryfair** [comment]
Not yet resolved, do we wish to add text about using select/poll/etc?

/ I've seen apps use a
kernel-assisted callback style (select/poll/epoll/kqueue/...).

It's probably not worth spending too much time trying to recraft
text, but if it seems relevant to mention perhaps give it some
thought./

**Comment by gorryfair** [comment]
After thought: Indeed, an implementor could, but I don't think we ought to expand the list of how the sockets API can use select/poll - that would be too much coding fun (and too much text).
