### ISSUE TITLE
ART-ART: architecture and interface ?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1238]
My first observation and request is that the group rethink the separation of
the architecture and interface documents. It is a warning-sign that the
interface document is a normative reference for the architecture document. As
the documents are currently constructed, a new reader cannot grasp the
architecture without inferring some of it through reading the interface.

Consider reformulating the architecture document as an overview - introduce
principles, concepts, and terminology, but don't attempt to be normative.
(There are signs that this may already be, or have been, a path the document
was being pushed towards). If nothing else, rename it, and acknowledge that the
actual architecture is specified using the interface definition.

Note that the first sentence of the Overview in the interface document also
highlights the current structural problem.

**Comment by mwelzl** [comment]
This was discussed at length in #879, which also points at a discussion at an interim. There are related PRs mentioned there, which reformulate some things to address this comment, and the overall decision was to keep the split.
