### ISSUE TITLE
ART-ART: Non-normative text in Arch

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1240]
The document currently says (just before section 3.1) "The rest of this
document describes the architecture non-normatively", but then goes on to use a
bunch of 2119/8174 language (much of which really shouldn't be - please try
eliminating all of them).

**Comment by gorryfair** [comment]
Fixed in PR  #1237

**Comment by gorryfair** [comment]
Could be closed when PR is merged.on the overall .

**Comment by mwelzl** [comment]
This was already fixed in #938, which closed #881.
