### ISSUE TITLE
ART-ART: Robustness requirement

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1246]
In 3.1 consider "It is important for applications using a Transport Services
system to be robust to the" instead of using REQUIRED.

**Comment by gorryfair** [comment]
Could be so, although the app will break if it does not do this. New text proposed in #1237

**Comment by mwelzl** [comment]
See also: #889 - it seems to me that removing the REQUIRED was overlooked in the process, though.
