### ISSUE TITLE
ART-ART: SHOULD or MUST in 3.2?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1247]
At 3.2, if this were a requirements document for the Transport Services system,
the SHOULD in the first paragraph might make sense. But if its an architecture
document, or better, an overview and introduction. It would be better to simply
say "is" rather than SHOULD. (And in a requirements document, I would argue
that this SHOULD should be a MUST).

**Comment by mwelzl** [comment]
See #889
