### ISSUE TITLE
Security by default?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1255]
From the review by Roman Danyliw:

** Section 3.1.
  It is RECOMMENDED that the default values for Properties are selected
  to ensure correctness for the widest set of applications,

Is there an opening here to stress “security by default” such that the
recommended default values not only ensure correctness but also security and
privacy for the end-user for the widest set of applications?

**Comment by mwelzl** [comment]
First, I think this warrants a separate paragraph - the one quoted here is complex enough as it is, and I don't think we should just add a few words about security to it. Actually, it wouldn't even fit under the subsection heading - perhaps the next one instead (specialized features)?

Should we say something: I'm not sure. I can see that it would be a useful recommendation, but then "security" and "privacy" are very broad terms... what specifically should we say? "The best available security and privacy"?  this would seem very vague to me - best in what sense?  Or: "some level of security and privacy"?  This wouldn't really mean anything...

Perhaps:

```It is RECOMMENDED that a Transport Services implementation makes use of specialized security and privacy features of the underlying protocol.```

But then, this is very obvious, and what that really should mean in practice is very unclear.  I'm left with the feeling that it might be better not to make a recommendation than to make such a vague one.

**Comment by gorryfair** [comment]
I think this is out of scope. It's in my mind linked to the use of Contexts. If a context is local, you might not care, or might prefer speed. If you have an authenticated VPN to a known service, that's different; but also a public Internet connection might have a policy that is more perscriptive. The TAPS WG never produced a document on how to handle system policy and that ID is where we should have said this. I'd vote for not saying anything extra in this spec - and leaving this to general IETF guidance.

**Comment by britram** [comment]
IMO "It is RECOMMENDED that a Transport Services implementation makes use of specialized security and privacy features of the underlying protocol." is consistent with the context-sensitivity of the application of these features, so I'd be okay with that change.

**Comment by tfpauly** [comment]
This section is referring to Transport Properties, _not_ Security Parameters. As such, this just means that things like reliability, window size, etc, should be chosen generically. They should have no impact on security parameters, which need to be more strict.

**Comment by tfpauly** [comment]
I'd recommend not changing any text here.

**Comment by mwelzl** [comment]
I declare rough consensus (may I? not being a chair... but I like saying these words  ;-)   ) for "not changing anything", and hence close this.
