### ISSUE TITLE
How to signal equivalence of security properties

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1256]
From the review by Roman Danyliw:

** Section 6.
```
  However, a Transport
  Services implementation can race different security protocols, e.g.,
  if the application explicitly specifies that it considers them
  equivalent.
```

I didn’t see any treatment in the earlier text on the “API” properties where an
application signals equivalence of security properties.  Could a cross
reference please be provided.

Also, from the review by Paul Wouters:

I am not sure this is a very clear distinction. Is IPsec with PolyChacha
different from WireGuard with PolyChacha? How about TLS 1.2 with AES-GCM
and TLS 1.3 with PolyChacha?  How about TLS 1.2 with AES-CBC and TLS
1.2 with AES-GCM ? Or TLS 1.3 vs QUIC? And TLS 1.2 vs
QUIC? Or TLS vs DTLS?

Some of these might not have fully known properties beforehand? Eg
what about TLS 1.2 where the server insists on PSK and rejects PFS?
Or IKEv2/IPsec with ECDSA versus IKEv2/IPsec with RSA?

It's a very gradient flow between Protocol Stacks. I am not sure the
defined distinction between Transport Services and Protocol Stacks is
that clear in practise.

How does DNS fit into this? Eg is it assumed that the application that can
request a minimum encryption can also request DNS resolving properties?
Eg insist on DoH/DoT, or insist on not using ADD, or insist on not using
the famous Quad DNS servers? Or insisting on DNSSEC validated answers only?

How does Remote Access VPN fit into this? Not at all? Or could an
application request "only through VPN connection X" ? Or is this
completely out of scope?  Either way, it could be clarified.

**Comment by mwelzl** [comment]
@britram wrote about this, in #1287:

from my email on the subject:

> ** Section 6 of draft-ietf-taps-arch-18 said:
> ==[ snip ]==
>  However, a Transport
>  Services implementation can race different security protocols, e.g.,
>  if the application explicitly specifies that it considers them
>  equivalent.
> ==[ snip ]==
> 
> How does one use the API described in this document to convey equivalence?
> 

That’s an excellent question. I’m actually wondering whether the text in the architecture document is correct: is it the application that makes the equivalence determination, or the system policy? I think it’s the latter, as the former is probably (far) too prone to accident. I’ll file an issue to make this change in architecture.

**Comment by britram** [comment]
It's the system policy. I have the feeling we've already made this change to arch, let me check...
