### ISSUE TITLE
Is "IP Address" scoped?  (section 1)

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1260]
From the review by Éric Vyncke:

Also Section 1:

Is `IP Address` scoped ? E.g., fe80::1%eth0 Can it be unicast, anycast,
multicast ? Even if section 6.1 is about this issue, it may be worth already
telling the readers.

**Comment by philsbln** [comment]
Every IPv6 address is scoped by [RFC4007](https://datatracker.ietf.org/doc/rfc4007/) / [RFC4291](https://datatracker.ietf.org/doc/html/rfc4291), while scope is orthogonal to being unicast/anycast/multicast.
Both are documented in the [ipv6-address-space IANA registry](https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml). 

If the Scope is not Global, there might be a zone-id to select the zone (oo-programmers would call it instance) of the scope.

Does it make sense to make a summary in the API?

**Comment by tfpauly** [comment]
Propose to close without action.
