### ISSUE TITLE
tcp in uppercase?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1263]
From the review by Éric Vyncke:

## Section 4.1

Should 'tcp' be in uppercase in `tcp Connection could support ` ?

**Comment by mwelzl** [comment]
#1404 will clarify that property names are case-insensitive. I like lowercase `tcp` here for style, and also because it somehow stresses that we're talking about a property name and not TCP per se (we do use TCP in the same sentence for that, so I think it's nice to have that distinction).

=> I propose to close this without action.

**Comment by mwelzl** [comment]
To be fixed: should be "Connection using TCP"  (so Connection is used right, and TCP capitalized here but not below)

**Comment by mwelzl** [comment]
This is now fixed - I missed which PR did it, but the text does now say "e.g., a `tcp` Connection could support a TCP-specific Transport Property, such as the TCP user timeout value, in a Protocol-specific Property called `tcp.userTimeoutValue` "  and this seems just right. Closing.

**Comment by abrunstrom** [comment]
Sorry, but I do not think this is right. It is not a `tcp` Connection. It is a (TAPS) Connection that uses TCP.

**Comment by mwelzl** [comment]
No need to be sorry of course!  it was a good catch and I agree. Will fix.
