### ISSUE TITLE
Be specific when talking about the RFC series

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1264]
From the review by Éric Vyncke:

## Section 4.1

`IETF document published in the RFC Series` in which stream ? Are ISE or IAB or
IRTF streams also OK ?

**Comment by gorryfair** [comment]
Indeed:

- For IETF protocols, the name of a Protocol-specific Property SHOULD be specified in an IETF document published in the RFC Series.

Ought to be "IETF Review" or "Standards Action", likely the former?

**Comment by mwelzl** [comment]
How does one phrase that?  "For IETF protocols, the name of a Protocol-specific Property SHOULD be specified in an IETF document published in the RFC Series after IETF Review."  ?
