### ISSUE TITLE
Section 6.1: WithIPAddress, WithInterface, WithPvD ?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1266]
From the review by Éric Vyncke:

## Section 6.1

I am not sure whether I like the split between .WithIPAddress() and
.WithInterface()... E.g., using "fe80::1%eth0" as an endpoint would be nicer ?

Should there be a .WithPvD() to handle multiple PvDs on the same interface ?
Even after reading section 6.2.12, it is unclear.

**Comment by gorryfair** [comment]
I'll propose assigning to Tommy - because I expect him to have more to say on this...

**Comment by mwelzl** [comment]
Also related to this, from the review by Robet Wilton:

  Note that an IPv6 address specified with a scope (e.g.
  2001:db8:4920:e29d:a420:7461:7073:0a%en0) is equivalent to
  WithIPAddress with an unscoped address and WithInterface together.

Would it not just be cleaner to not allow interface scoped IP addresses, and
force the clients to use WithInterface, in the case they want to target a
specific interface?

**Comment by tfpauly** [comment]
- I don't think we should add a "withPvD" here... the way to locally identify a PvD isn't well-enough established
- Allowing WithInterface makes things work for endpoint types that don't use "%en0" style semantics, so it should be allowed.
- I don't think we should prohibit interface-scoped IPs

Overall, I suggest closing this without action.
