### ISSUE TITLE
s/TTL/hop limit ?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1267]
From the review by Éric Vyncke:

## Section 6.1.1

TTL is so legacy... Why not using RFC 8200 hop limit ?

**Comment by gorryfair** [comment]
I prefer Hop Limit .. = with a note that this includes the IPv4 TTL. It's a primitive change, so Ive retagged as discuss... others please agree or not to say if this ought to change!

**Comment by gorryfair** [comment]
Resolved.

**Comment by mwelzl** [comment]
Related, so adding here. This is not in DISCUSS, so safe to ignore, as it's been overtaken by events:


From the review by Lars Eggert, COMMENT part:

### Section 6.1.1, paragraph 3
```
    RemoteSpecifier.WithTTL(TTL)
```
I'd point out that since IPv6, we switched to "hop count" for the
term, to make it clear it's not actually a time value
(anymore). Suggest to use the more modern term?
