### ISSUE TITLE
Definition of "Endpoint"

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1272]
Note: this feedback was given for both API and Architecture, but I believe it only concerns Architecture. It is worth double-checking with API though - it might affect usage of the term "Endpoint" in the API.

From the review by Warren Kumari:

1: S 1.4.  Glossary of Key Terms
*Endpoint: An identifier for one side of a Connection (local or
     remote), such as a hostnames or URL.

I'm not really sure that the definition of "Endpoint" works. E.g: the
definition of "Connection" is "Shared state of two or more endpoints that
persists across Messages". Ok, fine. But can you really have shared state
between two **identifiers**? I don't really see how I'd have shared state
between e.g hostnames, but I can see how I'd have state between entities
*identified* by an identifier like a hostname. I understand what you are aiming
for (and also "endpoint" seems to be used in more than one context), but I
don't think that the definition as written actually works...

**Comment by gorryfair** [comment]
My memory is for arch that we had "Endpoint", and "Endpoint Identifier " as different terms, is this what is being asked?

**Comment by mwelzl** [comment]
I guess so. The split would seem better to me. Note, RFC 8303 defines:

   Endpoint:  an entity that communicates with one or more other
      endpoints using a transport protocol.

This seems better to me. This said, if we change this, we must ensure that the term "Endpoint" is not used to mean an identifier. Actually, a quick search for "Endpoint" in the interface draft indicates that an Endpoint is indeed rather a communicating entity there than just an identifier. However, this is different in the architecture draft!  This looks like a lot of work...someone should check all occurrences and get them right, it's not even easy to do  :-(
