### ISSUE TITLE
How are IETF namespaces to be differentiated?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1275]
This issue arose while trying to determine the case of TCP in the specs, but isn't related to that. Issue #1271.

This concerns how an IETF WG could create a namespace for properties associated with an IETF protocol. The original idea was that we just copied entries from an IANA registry to give us a set of namespaces for each IETF protocol. However, we never actually said how we would avoid a vendor name matching an IETF protocol, or for that matter what happens when a new protocol emerges (as QUIC did). The only way I can see to make this manageable for a consistent parameter set for an app, is to declare the format of IETF namespace at least different to the vendor space. The two namespaces can be treated the same in the transport system, this is about allocating the names.

That would mean that the format of the two types of namespaces needs to differ in some way. We could use an initial capital letter to differentiate IETF namespaces (most IETF  protocols and extensions do use capital letters in the acronyms). That might be less language independent, so an alternative proposal is to prefix vendor namespaces with a special character (this could be underscore, or anything more appropriate). I think we need to do this, what are thoughts on using underscore before vendor namespaces?

**Comment by philsbln** [comment]
After all discussions, I guess we have three options left:
- Go with the capitalisation @mwelzl suggested … this looks awkward to me an @tfpauly … i would really prefer to keep properties case-insensitive.
- Go with the prefix for vendor namespace, and here I also prefer '_'
- Go and create an IANA registry for the namespaces. Reserve anything from the Protocol Numbers and ALPN Protocol IDs

I guess the last one would be the cleanest option, but generate a lot of work, so I have a slight preference to go with the underscore-prefix.

Shouldn't we take this question to the list?

**Comment by gorryfair** [comment]
It would be nice to see if we can find a good proposal - and yes "Discuss" means a change we need to agree upon,:-).

**Comment by tfpauly** [comment]
I'd rather not have a registry defined here — that seems pretty heavy-weight. I'd prefer the underscore prefix approach.

**Comment by gorryfair** [comment]
I think the underscore prefix approach would separate the two spaces - vendor and IETF-defined. I'd like to see that.

There also are 2 following topics:

1.  How does the IETF link its part of the namespace to the RFCs/protocols that exist and the ones that will be used in future? - (as a WG Chair I'd like to know whether a new ID matches a namespace or not). 
A list in this RFC would work for now (but isn't great when a new thing comes along); just say needs to be unique (is difficult to manage); We could base on an existing registry (I am not sure there really is a great choice, despite our try); I think a new registry would work for this (I quite like that, initially filled with TCP, UDP, QUIC, SCTP, etc);

2. How do people know entries in the vendor namespaces ... the answer here could be FCFS, or its could be "just be unique on your system, must start with _". The latter seems fair to me for this, since the forward-flexibility exists: the IETF could in future, if need, also allocate a different prefix to use a registry or to allow some other way of allocating.

**Comment by philsbln** [comment]
Based on the comment of @martinduke and the difficulty to find scattered parameters, I am more and more convinced that we should do both: introduce the "_" for vendor-specific namespaces (with FCFS registry or without registry) and have a registry for the IETF namespace.

**Comment by mirjak** [comment]
I don't think we need a registry. While it would be good to have the same parameter names on different systems, there are local interfaces and each system can actually ensure locally to not have conflicts. we could use the underscore notation to make it easier to avoid conflict across systems for non-vendor-specific parameters. But I don't we need or should try to deconflict any vendor-specific names.

**Comment by mwelzl** [comment]
Related, so I'm adding this here:

From the review by Lars Eggert, COMMENT part:

### Section 4.1, paragraph 7
```
    Namespaces for each of the keywords provided in the IANA protocol
    numbers registry (see https://www.iana.org/assignments/protocol-
    numbers/protocol-numbers.xhtml) are reserved for Protocol-specific
    Properties and MUST NOT be used for vendor or implementation-specific
    properties.  Terms listed as keywords as in the protocol numbers
    registry SHOULD be avoided as any part of a vendor- or
    implementation-specific property name.
```
This doesn't work if vendors use property names that the IETF later
adds to the IANA registry. Suggest to instead define a
vendor-specific prefix/name here, ideally one that is illegal for the
IANA registry.

**Comment by mwelzl** [comment]
Related, so I'm adding this here:

From the review by Paul Wouters, COMMENT part:

```
       Vendor or implementation specific properties MUST use a string
       identifying the vendor or implementation as the Namespace
```

What if Vendor Foo has a non-standard tcp property MagicSmoke? Does it go
under tcp.Foo.MagicSmoke or under Foo.tcp.MagicSmoke or something else?
