### ISSUE TITLE
Security Protocol Racing (section 6) (COMMENT on -interface from Roman Danyliw)

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#1287]
from my email on the subject:

> ** Section 6 of draft-ietf-taps-arch-18 said:
> ==[ snip ]==
>  However, a Transport
>  Services implementation can race different security protocols, e.g.,
>  if the application explicitly specifies that it considers them
>  equivalent.
> ==[ snip ]==
> 
> How does one use the API described in this document to convey equivalence?
> 

That’s an excellent question. I’m actually wondering whether the text in the architecture document is correct: is it the application that makes the equivalence determination, or the system policy? I think it’s the latter, as the former is probably (far) too prone to accident. I’ll file an issue to make this change in architecture.

**Comment by mwelzl** [comment]
Closing because this is a duplicate of #1256
