### ISSUE TITLE
"without corruption"

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1311]
From the review by Erik Kline:

### S6.2.1

* "without corruption"?

 I think I would have expected "without loss"; "without corruption" implies
 to me that there's some extra level of integrity checking go on (vis.
 S6.2.7).

This is also for ### S9.1.3.7

**Comment by gorryfair** [comment]
The text reads: "This property specifies whether the application needs to use a transport
protocol that ensures that all data is received at the Remote Endpoint without
corruption."
- I think this could be  all data is received in order without loss or duplication?
