### ISSUE TITLE
Temporary local address: why avoid for rendezvous?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1312]
From the review by Erik Kline:

### S6.2.13

* Why should the preference be Avoid for Rendezvous use cases?  It seems
 to me like many Rendezvous uses are not necessarily long-lived and so
 might be Preference None (Ignore), or even Prefer.

**Comment by csperkins** [comment]
I think it should be `Prefer` for `Rendezvous`. Setting this to `Avoid` makes sense for `Listen`, because listening services tend to be long-lived and public, but not for Rendezvous which is used for peer-to-peer connections.
