### ISSUE TITLE
Example on QUIC?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1328]
From the review by Benson Muite:

5) In section 10, an example using QUIC would be helpful, even
if encryption is ignored.

**Comment by mwelzl** [comment]
Hm - the implementation draft doesn't discuss QUIC. There should really be a QUIC mapping document, but that one just doesn't have it.

Suggest to close without action.

**Comment by abrunstrom** [comment]
Would it be useful to add a sentence in the introduction explicitly mentioning what protocol mappings are in the document?

**Comment by gorryfair** [comment]
Sure, please add to #1424
