### ISSUE TITLE
How does an application learn allowed/available interface names?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1331]
From the review by Lars Eggert, DISCUSS part:

### Section 6.1, paragraph 13
```
    *  Interface name (string), e.g., to qualify link-local or multicast
       addresses (see Section 6.1.2 for details):

    LocalSpecifier.WithInterface("en0")
```
How does an application learn which interface name strings are
allowed/available on the system? The API doesn't seem to provide this
information. Also, based on the examples, there seem to be special
names such as "any" - where are those defined and how are conflicts
with names used on the system avoided?

**Comment by mwelzl** [comment]
Look at issue #865

**Comment by mwelzl** [comment]
LocalEndpoints returned by Resolve()  => this should contain information about the available interfaces. See #947. State somewhere that this is what can be used here.

**Comment by csperkins** [comment]
I don't understand why we need an alternative mechanism here, rather than just use `Resolve()`?

**Comment by mwelzl** [comment]
I think it's because of the following paragraph in the API draft:


_Note that the set of Local Endpoints returned by Resolve might or might not contain information about all possible local interfaces; it is valid only for a Rendezvous happening at the same time as the resolution. Care ought to be taken in using these values in any other context._

**Comment by csperkins** [comment]
Sure - see the PR I submitted that fixes that
