### ISSUE TITLE
WithProtocol TCP/TLS in an example

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1333]
From the review by Lars Eggert, DISCUSS part:

### Section 6.1.3, paragraph 9
```
    The following example shows a case where [example.com](http://example.com/) has a server
    running on port 443, with an alternate port of 8443 for QUIC.

    RemoteSpecifier := NewRemoteEndpoint()
    RemoteSpecifier.WithHostname("[example.com](http://example.com/)")
    RemoteSpecifier.WithPort(443)

    QUICRemoteSpecifier := NewRemoteEndpoint()
    QUICRemoteSpecifier.WithHostname("[example.com](http://example.com/)")
    QUICRemoteSpecifier.WithPort(8443)
    QUICRemoteSpecifier.WithProtocol(QUIC)

    RemoteSpecifier.AddAlias(QUICRemoteSpecifier)
```
Why does the `RemoteSpecifier` definition not contain a `WithProtocol`
clause for TCP/TLS? And what would that look like, given that TCP/TLS
is a protocol combination?

**Comment by mwelzl** [comment]
Side comment: this example should use https

**Comment by mwelzl** [comment]
Regarding: why does it not contain one: the first is the default, the QUIC part defines an exception for one specific protocol.

What would that look like: we don't want applications to specify a protocol. We allow doing it to override a default, and should specify better how to do this. Maybe we should have a primitive to query for available protocols?

**Comment by tfpauly** [comment]
I don't think we need a way to query the available protocols — it should just be a matter of enumerating for an implementation what protocols are available in terms of symbols/objects.

**Comment by mwelzl** [comment]
The API documentation of a Transport Services system should contain a list of choosable protocols and protocol combinations.

**Comment by gorryfair** [comment]
These are strings, we can provide a few examples, and we ought not to try to enumerate all acceptable strings.

**Comment by mwelzl** [comment]
> Side comment: this example should use https

This is already done (overtaken by events).
