### ISSUE TITLE
Property names

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1338]
From the review by Lars Eggert, COMMENT part:

### Section 4.1, paragraph 1
```
    Transport Properties are referred to by property names.  For the
    purposes of this document, these names are alphanumeric strings in
    which the following characters are allowed: lowercase letters a-z,
    uppercase letters A-Z, digits 0-9, the hyphen -, and the underscore
    _. These names serve two purposes:
```
This allows property names that are indistinguishable from integers.
Is that a bug or a feature? Also, are they case-sensitive?

**Comment by gorryfair** [comment]
May have been taken-over by other changes: Only the IETF-defined property names are indestinguishable (can be numeric strings) because the uncoordinated vendor space now requires an underscore prefix.

**Comment by mwelzl** [comment]
Nah, I think he means that "3455" would be a legal property name, and also, are they case-sensitive?

**Comment by mwelzl** [comment]
Okay, a property name like "123" or "_15_" is awkward, but allowed. As long as we can distinguish them within our IETF space, I agree, it might be okay... I mean, "0-RTT" is a term that begins with "0"  (not how we write the related property, but still... why not allow it).

We still need to say something about being case-sensitive, I suppose (I'd say: "not").

**Comment by philsbln** [comment]
I guess we can't prevent prevent all stupid things. I don't see a reason to forbid this besides aesthetics and some languages not allowing to have Integers as labels for constants.

**Comment by gorryfair** [comment]
Allowing integers would have the side effect of making the code even less portable between languages, etc. So we could just forbid this?
