### ISSUE TITLE
How to express "Full Coverage"

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1346]
From the review by Lars Eggert, COMMENT part:

### Section 8.1.1, paragraph 3
```
    Type:  Integer (non-negative) or Full Coverage

    Default:  Full Coverage
```
How is "Full Coverage" expressed?

**Comment by mwelzl** [comment]
Why should we specify this? E.g., a C API could use -1 as a special number, a Python API could make use of the Full Coverage parameter which by default is False, ...

**Comment by mwelzl** [comment]
Related:
From the review by Paul Wouters, COMMENT part:

```
       If this property is an Integer
```

It is best to define the actual type in this document and not let implementations
choose, if the goal is to try and harmonize implementations. I also see no non-integer
value being given here ?

**Comment by gorryfair** [comment]
If it helps, UDP-Lite says this:

**the Checksum Coverage is expressed in octets ...  A
   Checksum Coverage of zero indicates that the entire UDP-Lite packet
   is covered by the checksum. **

Any Checksum Coverage 0- 8 is treated the same as the value 0. Values >8 indicate a partial coverage of the payload.
UDP has only two modes of course, full-coverage and no-coverage.
