### ISSUE TITLE
Later control of sender checksum coverage, and corruption / reliability

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1348]
From the review by Lars Eggert, COMMENT part:

### Section 6.2.7, paragraph 4
```
    This property specifies the application's need for protection against
    corruption for all data transmitted on this Connection.  Disabling
    this property could enable later control of the sender checksum
    coverage (see Section 9.1.3.6).
```
I don't know what "enable later control of the sender checksum
coverage" is supposed to mean. Also, how does this
(and `fullChecksumRecv`) intersect with `reliability`, which also
talks about corruption?

**Comment by gorryfair** [comment]
The other place ought not to talk about corruption - that one is about order and loss (see PR submitted); this case ought to talk about corruption.

**Comment by mwelzl** [comment]
`reliability` doesn't talk about corruption, but I found it: there's this sentence in `msgReliable`:
"When true, this property specifies that a Message should be sent in such a way that the transport protocol ensures all data is received on the other side without corruption."

I'll remove "without corruption" from this sentence. Also, the "later control" is about being able to (meaningfully) use property that affects the sending checksum later. This can guide racing to try UDP-Lite or not, for instance.
