### ISSUE TITLE
s/datagram/UDP payload

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1350]
From the review by Lars Eggert, COMMENT part:

### Section 9.2.1, paragraph 2
```
    messageData := "hello"
    Connection.Send(messageData)
    The interpretation of a Message to be sent is dependent on the
    implementation, and on the constraints on the Protocol Stacks implied
    by the Connection’s transport properties.  For example, a Message may
    be a single datagram for UDP Connections; or an HTTP Request for HTTP
    Connections.
```
I don't think you mean "UDP datagram here", since that would include
the UDP header. UDP payload?

**Comment by gorryfair** [comment]
well, could be:

For example, a Message may be the payload of
    a single datagram for UDP Connections; or an HTTP Request for HTTP
    Connections.
