### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1353]
From the review by Lars Eggert, COMMENT part:

### Inclusive language

Found terminology that should be reviewed for inclusivity; see
https://www.rfc-editor.org/part2/#inclusive_language for background and more
guidance:

* Terms `natively` and `native`; alternatives might be `built-in`,
  `fundamental`, `ingrained`, `intrinsic`, `original`

**Comment by gorryfair** [comment]
Just wondered, is the word "native" really an issue for the Internet community, when the word does not refer to an ethnic group?

Of a country, region, etc.: that is the place of a person's birth and early life; that is the place of origin of a plant or animal.  ... i.e.  "innate, produced by birth,"

**Comment by tfpauly** [comment]
I think this should be easy to fix, I can take a stab at it
