### ISSUE TITLE
Netflows vs. IP flows

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1357]
From the review by Paul Wouters, DISCUSS part:

- netflows vs IP flows?

Is TAPS only meant for flows or does it also support IP transport.
I don't see an example that would embody "setup a connection to 192.0.1.1 port
80, but require IPsec. I guess it could be added, eg a WithVPN("IPsec") or
something, but I'm not sure you can specify credentials without those being
interpreted to be for the port 80 in this example ? Is this specifically out
of scope, or just not (yet) specified?

Related, lets say you want to only use a flow if it goes over TOR, I guess one
could introduce a WithTOR() transport requirement. I'm a bit concerned that
without an IANA registry for functions, this might cause conflicts in the future.

**Comment by gorryfair** [comment]
It seems to me that this might have a two part answer?
- Yes I personally think the ARCH does allow this.
- No I think there is no curren binding specified fo how to do this in the API/Implementation. To me, this means an implementor can add this, and it might be something that IETF wishes to standardise in future in another RFC?

**Comment by mwelzl** [comment]
I'd agree that this is work for the future and would suggest to take the risk of conflicts: an IANA registry can still be created once TAPS is a wild success?!

**Comment by mwelzl** [comment]
Reply using @gorryfair 's comment above.
