### ISSUE TITLE
Single credentials for multiple protocols?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1358]
From the review by Paul Wouters, DISCUSS part:

Does this document cause encouraging of re-using of key pairs for
different protocols (eg TLS and IKEv2, or TLS 1.2 and QUIC). This
might have security implications (eg using RSA as RSA-PKCS1.5 as
well as RSA-PSS)

**Comment by britram** [comment]
Reply: It is not intended to, thought the document does read that way currently. The fix to #1286 will remove this ambiguity.
