### ISSUE TITLE
WithPort and WithService, but not WithProtocol

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1361]
From the review by Paul Wouters, DISCUSS part:

How does one choose their syslog service transport protocol, since syslog
over udp and tcp are valid and both have the same service name? Or does
WithService accept values like "514/udp" ?

**Comment by mwelzl** [comment]
The endpoint does not directly indicate what protocol to use. That's what the Transport Services system chooses.

**Comment by gorryfair** [comment]
My take is:
Normally, an endpoint ought not to request a specific transport protocol or protocol stack. The Transport Services Implementation is responsible for mapping the API to a specific available transport Protocol Stack and managing the available network interfaces and paths. When specifically needed, this automated selection could be over-ridden (e.g., to test a specific protocol stack).

**Comment by mwelzl** [comment]
... and it is now done using "WithProtocol".
