### ISSUE TITLE
ALPN

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1362]
From the review by Paul Wouters, DISCUSS part:

I don't see a WithALPN method for setting the ALPN.

**Comment by mwelzl** [comment]
Interim consensus: put it with security parameters

**Comment by tfpauly** [comment]
Should go into  [6.3.1. ](https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#section-6.3.1)[Specifying Security Parameters on a Pre-Connection](https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-specifying-security-paramete)
