### ISSUE TITLE
C.send()

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1368]
From the review by Paul Wouters, COMMENT part:

I don't understand this code:

```
       Connection := Preconnection.Initiate()
       Connection2 := Connection.Clone()

       Connection -> Ready<>
       Connection2 -> Ready<>

       //---- Ready event handler for any Connection C begin ----
       C.Send(messageDataRequest)
```

Where does "C" come from in "C.Send" ? The comment says "any Connection C"?

**Comment by mwelzl** [comment]
Ideas on how to make this clearer?  I'm tempted to close with no action, I honestly think the comment makes it clear enough?

**Comment by gorryfair** [comment]
I didn't know what C really was either, sorry. 
Do I understand this as valid?

Connection.Send(messageDataRequest)
Connection2.Send(messageDataRequest)

**Comment by mwelzl** [comment]
Huh?  I mean,  the comment says: "//---- Ready event handler for any Connection C begin ----"
So, C is the Connection...

You can think of the event handler like a function, which gets a Connection object in the function call, and that object is "C". How to make this even clearer?

**Comment by gorryfair** [comment]
I see the comment in the code, the example still does not use "C"

**Comment by mwelzl** [comment]
The point of using "C" instead of "Connection" is that it's one handler that's being used by both connections; it gets a Connection object, "C", and then calls "send" and "receive" on it. What's missing is the function signature that clarifies that "C" is a parameter for this Event - I thought the comment makes it clear, as I think we don't have any function signatures elsewhere in our examples...  this is all pretty abstract.

Does it help to look at real code?  See the server example here (the client adds a bit more functionality, but the server is really simple):
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9433510
https://arxiv.org/pdf/2102.11035.pdf

There's one handler, it gets a connection object, receives something on it and answers back on it. This same handler can be used by 15 connections...
