### ISSUE TITLE
About using [] in the addRemote call

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1371]
From the review by Paul Wouters, COMMENT part:

       Preconnection.AddRemote(RemoteCandidates)

Should this not technically be:

```
       Preconnection.AddRemote([]RemoteCandidates)
```

as the array contains at least a host and a stun server candidate?

Maybe this is just the difference between you using the variable you define
that has been assigned, versus a more C like prototype format, eg:

```
       Preconnection := NewPreconnection([]LocalEndpoint,
```

So I guess if your example here had set LocalEndpoint := [a,b] you would not
have used [] in the call ?

**Comment by mwelzl** [comment]
We think (interim) that this may be right: the brackets might be needed?

**Comment by tfpauly** [comment]
The problem is that RemoteCandidates is only defined in a comment and its type is not clear. Perhaps declare it in the code with a type with []RemoteEndpoint, and then comment that it gets filled out.
