### ISSUE TITLE
Priority order

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1378]
From the review by Paul Wouters, COMMENT part:

```
      A higher value reflects a higher priority.
```

This is uncommon in IETF protocols. Normally priority is down with lower numbers
being higher priority. Why reverse it here?

**Comment by gorryfair** [comment]
Can we reverse the order?

**Comment by tfpauly** [comment]
Sure, that seems fine to reverse to me.

**Comment by mwelzl** [comment]
I'm not sure this is generally uncommon in "IETF protocols" - e.g. RFC 8699 is a counter-example. But, okay, I think it doesn't matter - and it would probably be good for our API to be aligned with RFC 9218.

I do find it a little awkward that we had it like this, then agreed to flip it, and now flip it back. But I don't really care, it's fine with me  :-)
