### ISSUE TITLE
Draft should point at implementations somewhere

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#145]
I think it would be useful to somewhere (appendix?) include a sentence like: "Many of the mechanisms described in this document are implemented by the open-source NEAT library, which is available from [NEAT github] and described in [NEAT commag paper]".

And, if there could also be more such statements (from Apple about Apple's implementation, from socket intents about their implementation, ..) that would be fantastic, I think.

**Comment by mwelzl** [comment]
Just a clarification because @philsbln had this on his slides today: this one isn't really anything worth discussing, I meant it just as a "to do item" for myself. Sorry if that was bad github style...

**Comment by mwelzl** [comment]
I made a start for this as a new appendix to the implementation draft, which I pushed directly to the master. Rather than discussing things in a PR, people should just fix / amend text related to their own implementation directly as they see fit and push these changes to master, I'd say.

**Comment by tfpauly** [comment]
Added our implementation details with c54cd80
