### ISSUE TITLE
Correctly follow BCP205

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1466]
Make sure the implementation overview is in the right document, probably it should also have the correct name, and add a note to the RFC Editor requesting that the section be removed before publication.

**Comment by mwelzl** [comment]
... or is it too late in the process for that? We can tell the RFC editor to remove this in any case?

**Comment by tfpauly** [comment]
The fact that this exists in the implementation draft (https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-impl.html#name-existing-implementations) seems OK to me — we can point people there, and it would be removed anyhow.
