### ISSUE TITLE
Issues to consider (Handley)

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/api-drafts#147]
Input from Mark Handley, distributed with permission:

> Hi Aaron, Colin,
> 
> As I mentioned, I'm playing with ideas for a new TCP-replacement transport protocol at the moment.  It doesn't really have a name right now, but lets call it NeoTCP.  Likely it won't go anywhere, but some of the ideas differ a bit from other transport protocols, so may serve as a useful test for the TAPS API.  
> 
> 1.  Pre-authentication.  I want to put the ssh server on my home machine on the Internet without it being constantly attacked with password guessing attacks.  NeoTCP implements very simple pre-authentication, where my laptop and my home machine share a secret.  When connecting, the client sends the pair  (nonce, Hash(nonce, secret)).  The server won't send a syn/ack equivalent unless the secret match one of the secrets from its cache.    
> 
> 2.  Source-spoofing protection.  NeoTCP supports the equivalent of SYN cookies, but with a 4-way handshake to avoid the potential deadlock associated with SYN cookies.  I'm also playing with the idea of allowing middleboxes to interpose a challenge in response to the SYN, and when the challenge response arrives from the client, only then is the packet passed through to the actual server, and the handshake continues.  I'm not clear yet if including middleboxes in some way impacts the API.
> 
> 3.  Encryption.  Goal is to do tcpcrypt-like encryption, but provide hooks to higher layers so they can do whatever full authentication that particular application needs.
> 
> 4.  Redirect.  Redirecting connections is a very common application-layer function, but really you would prefer to redirect before you've set up a connection.  Such redirection obviously needs some form of authentication (maybe this contradicts 3 - not clear where I'm going on this yet).   What would the API be for a redirect server? It's not a full server;  it listens, but simply sends stateless syn/ack redirects, rather than accept connections.   
> 
> 5. Acking.  NeoTCP supports multi-path using two sequence spaces - subflow packet sequence numbers and data sequence numbers like MPTCP.  Unlike MPTCP, the data sequence number ack indicates the receiving application received the packet (with MPTCP, it only indicates reception by the receiving stack.
> 
> 6. Pulling.  NeoTCP takes some lessons from NDP, and is a receiver-driven protocol.  When several senders are sending to one receiver, this allows the receiver to choose precisely which senders to pull packets from at any time.  This generalizes the QUIC/HTTP2 priorities to now support multiple different senders.  You can use this to do aggregate congestion control for incoming traffic, avoiding self-congestion.  It's up to the receiving application to determine priorities, and to the transport to decide how to use those priorities.
> 
> 7.  Close is a total mess with TCP.  It's even worse with a user-space protocol - your application may quit when close returns; data may not have been received yet and needs retransmitting, but there's no-one left to do it.   By default, with NDP close won't return until the receiving application has received sent data.   Obviously you need some way to avoid deadlock when the receiver died; that timeout is application specific.
> 
> 8. Finally, we've done a lot of work over the last couple of years on understanding MPTCP for web traffic.  It's ugly. You have a whole load of short objects, and the application has a priority order for them.  But the paths may have very different latency.  If you send any packet from the highest priority object on the high latency path, you can delay the object significantly, and it can really hurt the overall page load time, as other requests get stalled waiting for that object.  The best you can do is to run a per-packet scheduler, and ask the question "if I send the next packet from this object on the higher latency path, will it arrive after the rest of the object sent on the lower latency path?" If the answer is yes, you shouldn't send that packet on the higher latency path.  Next you have to consider the second highest priority object, and ask if you should instead send a packet from that object on the higher latency path.  You should, if will arrive before both the highest priority object and all the rest of the second highest priority object. If not, you shouldn't, and you should consider the third highest priority object, and so on.  Obviously, this is complicated.  At the very least, the transport protocol needs to know which packets are from which object, and what those object priorities are.  At the receiver, objects may arrive out of order, but packets within an object must be in-order.
> 
> There are probably more things, but that's what comes to mind right now.
> 
> Mark

**Comment by britram** [comment]
@chris-wood to split this into multiple issues

**Comment by mwelzl** [comment]
A few comments:

5. is probably irrelevant for the API.

6. is interesting, and I think that this is already possible via our concept of grouping and prioritization between grouped connections. I'm quite sure I would have spoken up otherwise - I was careful about it myself because I also believe in congestion control coupling for flows from different sources, see:
http://heim.ifi.uio.no/~michawe/research/publications/ctrltcp-infocom-gi-2018.pdf

7. be that as it may, we are anyway limited to quite restrictive semantics as they must be the smallest common denominator of underlying transports that become "connections", including streams of a transport association. So I think this item is also irrelevant.

(Most of?) the others are bigger discussions...

**Comment by philsbln** [comment]
For most of the stuff (except 8) I have a rough idea how to extend TAPS to support these without changing any calls/semantics.
I don't think we need to actually address these in the draft, but we should collect these questions and exercise the "could this be added" task again before submitting the final version.

**Comment by csperkins** [comment]
Some thoughts on these:

1. This looks like extra parameters we'd pass to a `Preconnection`
2. This looks like it can be handled internally to the transport during connection setup
3. This requires an authentication callback into the application during connection setup, but probably so do many security protocols since identity is often tied to application semantics. We need to support the concept.
4. Excepting possible authentication callbacks, this looks to be something that can be hidden within the connection setup operation.
5. Affects when ACKs are delivered by the protocol, but not clear an API issue? Or if it is, it's additional metadata attached to a receiver callback.
6. We need to ensure we can specify priorities on connections at the receiver. Not sure our preferences are flexible enough to signal?
7. Doesn't seem to affect the API, except for perhaps the timing of the Closed callback.
8. Requires an API that allows prioritisation of data on different sub-flows, which we have. Given that, if you have a multipath transport you can be as smart or as dumb as you like the in scheduler, but it's not visible in the API.

I think we should review this again later, but it looks like we're probably flexible enough in the API we have to support all of these, with at most some quite minor additions.

**Comment by tfpauly** [comment]
Side meeting: after discussion, we believe the architecture covers these with enough flexibility for future expansion.
