### ISSUE TITLE
Add Unidirectional Streams for Multicast / Source and Sink support 

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#150]
We need unidirectional connections. You know, for multicast. And ICN. And unidirectional streaming protocols.

**Comment by britram** [comment]
This is a dup of #170, which has more discussion

**Comment by philsbln** [comment]
I am re-opening this ticket as #170 only dealt with unidirectional streams in unicast context (added with PR #191):

Current status:
 - The current model for unidirectional streams supports half-closed connections and QUIC style unidirectional streams so far.
 - We don't know yet whether it is sufficient to have can_read/can_write property on the connection level to model unidirectional connections
 - We don't have pre-connection methods to create multicast sessions yet

**Comment by philsbln** [comment]
I am re-opening this ticket as #170 only dealt with unidirectional streams in unicast context (added with PR #191):

Current status:
 - The current model for unidirectional streams supports half-closed connections and QUIC style unidirectional streams so far.
 - We don't know yet whether it is sufficient to have can_read/can_write property on the connection level to model unidirectional connections
 - We don't have pre-connection methods to create multicast sessions yet

**Comment by britram** [comment]
there's a selection property for this, tagged discuss, which we haven't discussed yet. I'm moving this down to the appendix as part of my restructuring in my work on #208

**Comment by GrumpyOldTroll** [comment]
If help is still wanted here, I'm maybe up for an attempt or 2 at adding multicast support.
Has there been some prior discussion I can review about rough ideas on pre-connection methods for multicast sessions, or should I just try making something up?

**Comment by MaxF12** [comment]
Closed by A#380
