### ISSUE TITLE
Privacy considerations section

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#177]
Each document should have a privacy considerations section to discuss the tradeoffs inherent in the API.

**Comment by britram** [comment]
hey @chris-wood any cycles for this before the BKK deadline?

**Comment by chris-wood** [comment]
Yes! Keep the pings coming.

**Comment by mwelzl** [comment]
Ping!  (post-bkk even!)

**Comment by chris-wood** [comment]
Pong! Will get to this ASAP.

**Comment by britram** [comment]
pingety pingety ping

**Comment by tfpauly** [comment]
When this is done, add a pointer from architecture to interface security considerations.

**Comment by tfpauly** [comment]
Indicate that anything you pass to the API can go onto the wire, etc, etc.

**Comment by csperkins** [comment]
§5.1 of the API draft talks about when DNS resolution happens, which is a potential privacy issue to point to.
