### ISSUE TITLE
ARCH: Message Framing, Parsing, and Serialization

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#188]
- This subsection appears out-of sequence. (Actually this could really help the reader if made a little easier to read and placed ahead of discussing the details).
- I would like to express a preference for a rewrite of this section to use a simpler style of English.
- I also would like consideration whether to position (at least parts of) this subsection earlier to explain why messages are being considered. If I read the spec without knowing more, an app developer could wonder what happened to the concept of streams and what I had lost.
----
/for transports that care about timing/
- Is this transports that care, or applications that care?
---
/choosing what messages to retransmit/
perhaps should be:
/choosing which messages may be retransmitted/
---
/such as SCTP/
- expand abbreviation on first use, and provide reference.
---
/message oriented API/message-oriented API
---
- I don't agree with this text:
/To support a message oriented API, while still being compatible with stream-based transport protocols, implementations of the transport services architecture should provide APIs for framing and de-framing messages. That is, we push message framing down into the transport services API, allowing applications to send and receive complete messages./
- Maybe a rewrite could separate what it means to have minimal support for messages and what additional API functions you could have to allow more advanced support for messages.
- I think we agreed an API **could** do this, and I think we have to say this is optional. Here is a start at what I suggest:
/A message-oriented API, can remain compatible with a stream-based transport protocol. An implementation of the transport services architecture could provide additional API functions for framing and de-framing of the messages. That is, ..../
---

**Comment by tfpauly** [comment]
Section being referenced no longer exists
