### ISSUE TITLE
Define the server-side equivalent of racing

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#206]
When `Preconnection.Initiate()` is called, the stack picks candidates and races them, selecting the "best" one.

When `Preconnection.Listen()` is called, does the stack listen on *all* non-prohibited candidates, or the first _n_ candidates in order of preference, or...?

This needs to be explicitly addressed both in -arch and -interface.

(thanks Zahed for raising this at the TSV dinner)

**Comment by tfpauly** [comment]
So, haven't done this yet for protocols, but I've been working on this recently for path listening. The approach there is:

- Create the same preconnection settings with preferences for which paths/Interfaces/etc are allowed to be used
- When you do candidate gathering, you get a list of all eligible interfaces for listening
- Open a sub-listener on each of these interfaces (we call the sub-listener an "Inbox")
- Watch the candidate list, and remove and add inboxes as necessary

**Comment by tfpauly** [comment]
Another area in which we do some interesting dynamic inbox work is when you use multiplexed protocols: say you are listening for new HTTP2/TLS/TCP connections on a TCP-level "Inbox"; when you get one, you can also start listening for extra streams on those connections as an HTTP2-level "Inbox". Thus there is precedent for listening for specific things based on interactions of other connections. Could be useful?

**Comment by philsbln** [comment]
@tfpauly I think it is useful.
The problem I see is that doing so will force us to fully model what pseudo-transports are and how they work.  That is definitely useful but adds another layer of complexity. We have to decide whether to include this in the API or build this as a layer on top.

**Comment by csperkins** [comment]
Also needed to implement ICE.

**Comment by mwelzl** [comment]
I wonder why this has the API label: ISTM that nothing in the current API draft contradicts implementing what @tfpauly says in his first message above. There are Preconnections, with various preferences, from which Connections are established via Active or Passive Open - so it should be expected that any preferences chosen on the Preconnections also apply when Listening.

Regarding @tfpauly's second message ("Thus there is precedent for listening for specific things based on interactions of other connections. "), if I got this right, you want to be able to prefer "Listen" to operate on streams from an already existing connection.

As a TAPS user, couldn't I implement this by using "Clone" on the first connection and not even calling Listen on it - now, the sender could send me data? If I want to be less strict and additionally allow other incoming Connections (in case the sender isn't muxing Connections), I can also issue a Listen on a new Preconnection.

**Comment by mwelzl** [comment]
Ah ok!  I thought this might be a reason but I don't know enough about the rendezvous procedure.

**Comment by adventureloop** [comment]
should be considered with #282

**Comment by tfpauly** [comment]
Also note that while it already happens implicitly for socket listeners, listening on multiple interfaces and addresses by default needs to be specified.
