### ISSUE TITLE
Do we need an IANA Registry of Properties

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/api-drafts#210]
We will end up with a set Turns out we might need a lot of (protocol) specific properties, we should discuss whether we need an IANA registry of properties and how this will look like.

 - Include Types ?
 - Include Names ?
 - Some numeric representation ?

What do we do with ENUM values?

**Comment by tfpauly** [comment]
I agree that a registry seems unnecessary; this is not a matter of protocol or on-the-wire standard.

**Comment by philsbln** [comment]
If we don't want to clutter the basic API document, we will end up having at least a half a dozen documents defining specific properties for different protocols.
Does anyone have a good alternative to collect all these except in an IANA registry?

**Comment by tfpauly** [comment]
We do *not* need to have documents specify every property. Implementation should be allowed to extend as they need.

**Comment by britram** [comment]
this discussion does suggest that we might want to be more explicit up front in the interface document about the scope and purpose of the document (i.e. this is meant primarily to define a standard API "shape", not the particular strings and codepoints, etc.). I'll file an issue.

**Comment by csperkins** [comment]
I agree with @tfpauly that we don't need to document every property, and with @britram that we're documenting the shape of an abstract API, *but* I also see value in consistent property naming across concrete implementations of that API. Some form of registry might make sense here.

**Comment by adfalk** [comment]
This seems like a topic for the mail list rather than GH.

--aaron
