### ISSUE TITLE
Consider per-context addresses as suggested by draft-gont-taps-address-usage-*

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/api-drafts#212]
The discussion around ``draft-gont-taps-address-usage-problem-statement`` and ``draft-gont-taps-address-usage-analysis``suggests that it should be possible to request per-application / per-context / per-connection source addresses.

 - For the cases of per-application and per-connection source addresses, this can be tuning this can be accomplished by the addition of a property. This includes name-resolution issues.
 - For per-context source addresses, I am not sure whether our current architecture is fit to support this.

Consider the following case: a browser wants to separate different tabs onto different source addresses. It needs some way to specify some kind of *context* to allow the transport API either to assign the right address to a new connection or request a new address for all upcoming connections and name resolutions done within this context.
As this is orthogonal to multi-streaming, simply cloning an existing connection is not sufficient.

One possible solution would be to introduce some new "Taps Context" that is used when creating pre-connections, but that looks like overkill for this feature…

**Comment by britram** [comment]
Closing on lack of activity. This is a good thought experiment to see if the API is flexible enough to support it. However, see #300 for specific handling of privacy addresses in V6.
