### ISSUE TITLE
API document should begin with a simple usage example

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#247]
Similar to the way we added simple diagrams to the architecture document to make the "story" of the document more compelling, we should begin the interface document with a simple workflow for an example connection. This way, we can show concretely up front how this is simple and useful, while being quite flexible and powerful. This can also inform how we then continue to explain depth to the details.

**Comment by theri** [comment]
I'm going to prepare a PR this week.

**Comment by philsbln** [comment]
closed by #293
