### ISSUE TITLE
Implementation should separate out protocol-specific bits

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#248]
Right now, there are protocol specific examples mixed into the generic flow description; then, later, there is a section that has some description for protocol specific considerations.

Possible re-organizations:

1.

Per-protocol mappings for each API call + per-protocol specific options. This is a guide to each protocol, such as a section for UDP and how each call is implemented for UDP, and what options UDP offers specifically.

General discussion about Pre-Establishment, Establishment, Data Transfer, etc, that has less information about specific protocols.

2.

Structure everything with the general topics (Pre-Establishment, Establishment, Data Transfer, etc), and have a rigorous list of each protocol's mappings at the end of each section. So, for Establishment, we describe racing, etc; and then go through and explain what Initiate() does for TCP, UDP, UDP Lite, QUIC, SCTP.

**Comment by JonathanLennox** [comment]
I'd go further and say that protocol-specific stuff need to be split out into a separate document.

Protocol-specific mappings should be defined in a standards-track document, whereas most of the Implementation draft should be Informational.

**Comment by mwelzl** [comment]
@JonathanLennox - maybe ... I don't disagree with your proposal, but I do think that this should be a discussion for a larger group. Maybe the right strategy, for now, is to reorganize along Tommy's proposed method #1 or #2 (not sure myself which one is better), and then later take text out as you propose if this is the consensus. Make sense?

**Comment by JonathanLennox** [comment]
Agreed -- this would need consensus of the WG, not just a GitHub issue discussion.  Separating out the text to start, so it's clear what would end up in a separate document, would be a good first step.

**Comment by csperkins** [comment]
I'd tend to lean towards option 2, but I suspect we won't know for sure if it works until someone tries to implement the changes. I'd prefer not to introduce more drafts unless we absolutely have to.

**Comment by tfpauly** [comment]
I think this is covered well by #352
