### ISSUE TITLE
API needs a way to handle "STARTTLS"

### ISSUE THREAD

**Issue by JonathanLennox** [ietf-tapswg/api-drafts#249]
SMTP and XMPP (among other protocols, probably) have "STARTTLS" semantics, where a TLS layer can be inserted on top of an already-existing (unencrypted) connection sometime after some application-layer protocol negotiation has already happened.

Frequently, the choice of certificate presented / accepted can depend on information in the application-level protocol (since these mechanisms pre-date the invention of SNI).

There should be some way some way for applications using the TAPS API to be able to do this.

**Comment by JonathanLennox** [comment]
API-wise, this feels like it might be similar to the issue of dynamically changing a connection's framer (the Websockets problem).

**Comment by britram** [comment]
Yep, this seems like the same problem as websockets.

However, like websockets, the actual implementation of transition-to-TLS with STARTTLS is application-dependent, so there could be an argument that the application logic really does need to be involved here (i.e., that STARTTLS belongs above the TAPS interface boundary). I'm not sure I buy that argument, though.

Tagging this discuss...

**Comment by tfpauly** [comment]
One way to solve this that's a bit of a cute hack is to:
- Let framer protocols defined by the application have the ability to do a short handshake (which is often the case, you may need a prelude prior to application data)
- Put a framer protocol that defines "STARTTLS" *below* TLS in your protocol stack to insert itself before TLS starts

**Comment by JonathanLennox** [comment]
The problem with making STARTTLS be part of a framer is that STARTTLS is, in some circumstances, opportunistic -- the protocol might proceed without TLS if the peer doesn't support it.

Also, the first level of application code (parsers, etc.) that uses the TCP connection before STARTTLS is going to be essentially the same as the code that uses the TLS connection after STARTTLS, so artificially forcing the former to be a framer feels unfortunate.

I feel like a more general solution is a mechanism whereby the application can take an existing connection, and then dynamically add another protocol on top of it, or replace the existing top.  A framer in this context could be just a special case of a protocol.

(There'd need to be some way for the application, or the replaced protocol, to push back any excessive already-read bytes to its parent connection to be read by the new child, but that doesn't seem so complex.)

**Comment by philsbln** [comment]
We have not fully defined the API of the framer yet – I guess "un-reading" is a common case for a framer anyway. What we then need is
a) A way to replace a framer in-flight
b) A set of pseudo-framer, e.g., for TLS
c) A way to stack framers (which also looks not-so-uncommon)

**Comment by JonathanLennox** [comment]
I think we need to be able to stack protocols in general, not just framers.

This was my point with STARTTLS, but consider also the case of implementing HTTPS 1.1 vs. 2:

Connect with TLS, with ALPN set to "h2".
Check ALPN negotiation in the result
Depending on the result, insert either HTTP/1.1 or HTTP/2 on top of the TLS connection.

**Comment by JonathanLennox** [comment]
Yes, HTTP/1.1 vs. HTTP/2, proper, should be implemented by the stack itself, since HTTP is a protocol defined by TAPS.

That said, TAPS is never going to be able to implement every protocol every application will want to use, and mechanisms like ALPN will likely be needed by applications' protocols as well.  My general rule of thumb is that every mechanism that the TAPS stack needs internally is likely going to also be needed by applications.

**Comment by britram** [comment]
closed with a shrug: no stack mutation needs to be in the architecture as discussed in Singapore (106). Framers are capable of being abused^Winnovated-with for stack mutation.
