### ISSUE TITLE
Editorial: Move Message Object to basic objects section

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#255]
Given messages are part of the basic concept we rely on, I would propose to move the definition of Message to the Basic Objects section and rename "Data Transfer Objects and Actions" to just "Data Transfer Actions".

**Comment by mirjak** [comment]
Maybe put also everything that is listed in the "Pre-Establishment" section into the Basic Objects section (basically just remove the heading), because all other subsections then only talk about actions and events.

**Comment by mirjak** [comment]
And as we are talking about this part of the doc, I find it a bit strange that there is a point for "endpoint" while that term on it own does not show up in the image. However, actually this point doesn't provide a whole lot of information. The only interesting bit is this sentence:

"An Endpoint may be specified at various levels, and an Endpoint with wider scope (such as a hostname) can be resolved to more concrete identities (such as IP addresses)."

Maybe we can just remove the endpoint definition and instead add a sentence similar as the one above to each of the local and remote endpoint definitions?

**Comment by mirjak** [comment]
Or alternatively, move local and remote endpoint (and message) to Basic Objects, and have a separate section to talk about properties (maybe even including message and connection properties...)

**Comment by tfpauly** [comment]
I disagree with this change; perhaps we can have a better name for "Basic Objects", but they are a category for a reason.

Perhaps the Basic Objects can be though of as "Top-Level Objects"—they're the main things you interact with to establish connectivity and send data. There are other objects (Endpoints, Paths, Messages) but those are only useful when attached to a Preconnection, Connection, or Listener.

**Comment by mirjak** [comment]
I don't think top-level objects is any better. And I would see endpoint and message also as one of the main things you interact with if you want to send or establish. If you want to create a preconnection you have to create an enpoint first; if you want to send you have to create a message first.

However, I think I understand where you see the difference but I don't know if it is any important to distinguish here. These are all objects while the others things you described are not objects but actions or events.

I guess if you put all objects in the same section you could have two subsections but I also don't know what the right headings would be (assosiation objects and data objects... :-( )

**Comment by philsbln** [comment]
Maybe tell the story a little bit differently:
 - Basic Operation Overview (no message there)
 - Transport Services Concepts
   - Objects
   - Phases
   - Actions
   - Properties

**Comment by tfpauly** [comment]
Discussed with @mirjak, let's rename `Basic Objects` to something like `Connection Objects`.
