### ISSUE TITLE
Not all Events are shown in the diagram

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#257]
Should we add "Connection Ready", "Message Sent", and "Path Properties Changed" to the diagram? Actually I not sure why "Path Properties Changed" shows up in this doc at all. This seems to be rather specific and the section actually explicilty says "The API may expand this list.".

**Comment by mirjak** [comment]
Btw. Receive() is also missing in the diagram...

**Comment by mirjak** [comment]
And listen() should be a call on Preconnection. However see also issue #254

**Comment by mirjak** [comment]
Actually looking at this even more, the way Events are display is confusing in general. Maybe we should considering redrawing this diagram differently or splitting it up in two/multiple diagrams...?

**Comment by tfpauly** [comment]
@britram can you help look at how we want this diagram to be?

**Comment by britram** [comment]
on it.

**Comment by mirjak** [comment]
Rendezvous and Framer are not in the diagram but not sure it makes sense to add that; also some events are still missing but I'd be afraid that the diagram becomes too confusing if we add more things. Current diagram is definitely better than the previous version!

**Comment by britram** [comment]
I'm still on this one. @mirjak let's have a look at this this week or next.

**Comment by britram** [comment]
I had another look at this and... it seems done to me? @mirjak can you close or point out what else we need here?

**Comment by britram** [comment]
(Where "done" = "adding additional events will make the diagram less useful in general")

**Comment by mirjak** [comment]
I agree that adding more would make the diagram too complex. Maybe it would make sense to have a different diagram that shows all interaction with the application like conn ready or path properties changed; but might also be a boring diagram.

what would be nice, would be to have the rendezvous part in there somehow but that doesn't seem really straight forward... maybe also a separate diagram?

**Comment by tfpauly** [comment]
Weirdest part of the diagram is that send is an arrow into connection... but it's a function that is called on connection, while initiate is an arrow from preconnection to connection, but is a function on the connection.
