### ISSUE TITLE
Do we need a terminology section in arch?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#258]
I think we should move some of the terms definied in "Transport System Implementation Concepts" to a terminilogy section at the beginning of the doc, such as "Path", "Connection Group", "Protocol Instance" and "Protocol Stack", because these terms seems rather basic and not implementation internals. Further these terms have already been defined in other docs, so it would just be fine to say there that we are using these terms from these other docs at the beginning.

Alternatively or additionally, I'm wondering if it would be possible to integrate the term "Path" somewhere in the first diagram ("Concepts and Relationships in the Transport Services Architecture").

**Comment by tfpauly** [comment]
+1 to representing path in the diagram

**Comment by tfpauly** [comment]
Since much of the document really is defining terms and concepts, I'd like to keep those all together in the same part. They used to be more at the front, but then we decided to put more of the Design Principles—"why this is cool"—up front. I'd like to get more input and discussion on this.

**Comment by mwelzl** [comment]
I like the "why this is cool - up front" sequence that we have now. Seeing a terminology section to begin with makes me think "okay, I have to learn this by heart, wait, let me get a coffee, now I can dig through this document". That's ok for a spec that I must read, as a coder... but this one maybe has a different role, of convincing people that this whole TAPS thing is any good?  If that's at least part of the role, I wouldn't put a terminology section early.

**Comment by csperkins** [comment]
I don't mind the location, but maybe we need to give more context? The draft is a long list of concepts, with perhaps not enough explanation and context around them.

**Comment by britram** [comment]
closed as OBE in Singapore.
