### ISSUE TITLE
Clarify path vs endpoint racing

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#260]
as I would think a path is an association of a remote and local enpoint...?

At least based on the definition we have in the arch doc, I don't really understand the difference.

**Comment by tfpauly** [comment]
These are different concepts; I can certainly try to improve clarity, but at the most simple levels:
- Path racing is like racing between Wi-Fi and Cellular interfaces, or across different PvDs on a single interface (so, local endpoint related)
- Endpoint racing is like racing between four different IP addresses resolved from a hostname on a single interface/path/PvD (so, remote endpoint related).

Perhaps specifying that "endpoint racing" is really "remote endpoint racing" will help

**Comment by tfpauly** [comment]
I updated the architecture document with the following:

```
* Path Racing: Path Racing is the act of attempting to establish, or 
scheduling attempts to establish, multiple Protocol Stacks that
 differ based on a selection from the available Paths. Since 
different Paths will have distinct configurations for local addresses
 and DNS servers, attempts across different Paths will perform 
separate DNS resolution stepss, which can lead to further racing
 of the resolved Remote Endpoints.

* Remote Endpoint Racing: Remote Endpoint Racing is the act of attempting
 to establish, or scheduling attempts to establish, multiple Protocol Stacks
that differ based on the specific representation of the Remote Endpoint, 
such as IP addresses resolved from a DNS hostname.
```

Does that help?

**Comment by mirjak** [comment]
That does help, however, i guess I would call both of these path racing; while one is the remote endpoint racing, I guess the one would then be local enpoint racing...?

**Comment by gorryfair** [comment]
I actually think /path/ is a good description for this one, it's not really about which endpoint you choose for the source, but which path you wish to evaluate.

**Comment by theri** [comment]
Agree with Gorry. 
Adding to that: Path racing might be the choice between local interfaces, but it might also be the choice between two IPv6 prefixes that the endpoint got assigned by different routers on the local link, so you essentially choose which router your traffic will go through.

Small suggestions/nits for @tfpauly's text:
s/DNS servers/DNS resolvers/
s/stepss/steps/

**Comment by mirjak** [comment]
The confusing part to me is that we defined path as something that has an local and remote enpoint. So with is path racing only focused on local porperties and remote enpoint racing something different?

**Comment by philsbln** [comment]
I just skimmed the document for path definitions and the only one I can find is:

 _Path: Represents an available set of properties that a local system can use to communicate with a remote system, such as routes, addresses, and physical and virtual network interfaces._

Which fairly well matches @tfpauly's definition of Path Racing.

**Comment by tfpauly** [comment]
@philsbln right, I don't think that a `Path` is a local + remote endpoint—it is a way off the device, effectively like a PvD (not an association from Post)

**Comment by philsbln** [comment]
@tfpauly I used to characterise a path with src-addr + output-interface, but this is not future proof if we consider segment routing.
I guess PvD is a nice first explanation, but might be wrong in many cases, e.g., in an IPv6 hybrid access scenarios with multiple routers on an ethernet network announcing different prefixes and different PvDs or in cases where you have a wireless and wired access within the same PvD

I guess getting more concrete than your definition will not do us any good.
