### ISSUE TITLE
Editorial: section "Message Framing, Parsing, and Serialization" seems a bit misplaced

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#262]
First this section only takes about message framing and not parsing and serialization. Second the section seems to be added random at the end (I know why this is), however, maybe we can add some of the text to the "Design Principles" section and other the part taking about message properties (which by the have not be introduced in this doc) somewhere where message is defined...?

**Comment by tfpauly** [comment]
I quite agree that this is misplaced at the moment. I think migrating the text it has uniquely into Design Principles and Message makes sense.

**Comment by tfpauly** [comment]
I've moved the text into Section 1.3. Data Transfer Using Messages, and 4.1.4. Data Transfer Objects and Actions. I think this flows better. Please let me know if that satisfies you as well!

**Comment by csperkins** [comment]
LGTM (with a couple of minor editorial nits I pushed)

**Comment by mirjak** [comment]
LGTM
