### ISSUE TITLE
Clarify multi-streaming can cause that ConnectionReceived events can be fired from pre-connection used for initate()

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/api-drafts#269]
This issue popped up while discussing #266 and seem to be a wired QUIC multi-streaming issue, possible affecting SCTP too):

When a multi-streaming protocol like QUIC allows both ends to open new streams (e.g. by cloning the QUIC connection representing the stream), the both side needs a way to get a ConnectionReceived event for a new stream. That might result in the following weird pattern:
```
pc1 := NewPreconnection(…)
c1 := pc1.Initiate()
…
pc1 ->  ConnectionReceived<c1.1>
…
pc1 ->  ConnectionReceived<c1.2>
```

I think this needs to be documented somehow and we may need to add a Selection Property do turn off this behaviour.

**Comment by csperkins** [comment]
Calling `Initiate()` is an active open. Once the connection is open, the peer can open new streams, but those would surely be `ConnectionReceived<>` events on the *`Connection`* not on the `Preconnection`.

**Comment by philsbln** [comment]
@csperkins I am not sure with this one: assuming you have a bunch of ``Connections`` which are streams on the same multi-streaming connection – which one should fire the ``ConnectionReceived<>``? The first one? What happens if I close the first one?

**Comment by csperkins** [comment]
That's a good point, and I'm not sure I know the answer, but I *don't* think the`Preconnection` should fire the events. A `Preconnection` is a potential connection, yet to be instantiated, but these connections come from an already active connection.

I've never been entirely comfortable with cloning a connection as the multi-streaming abstraction. This is perhaps the first scenario where it struggles though.

**Comment by abrunstrom** [comment]
I do not understand the pattern in the example. You do not get a ConnectionReceived after an active open, you need a Listen?

**Comment by abrunstrom** [comment]
@philsbln the TAPS interface is the same weather you have TCP or QUIC underneath. For TAPS an active open generates a READY event not a ConnectionReceived? I do not think your example is a valid TAPS sequence.

**Comment by philsbln** [comment]
@abrunstrom the Ready event is not shown in the example (it would be within the first ``…``).
The problem I raised is how to model the addition of streams to a multi-streaming connection. In case of QUIC, additional streams can be initiated by the server/listening side of the QUIC connection.
If we model QUIC streams as TAPS connections, this results in ``ConnectionReceived<>`` events at the client (and server) side for each new QUIC stream.

**Comment by mwelzl** [comment]
I also see a problem with the communication pattern here. To me, modelling a stream as a TAPS connection means that for every new connection that a peer creates (be it a stream of an existing connection or not), I'll have to listen. So: if I expect 5 incoming connections, which may e.g. be 1 connection with 1 stream and 4 later-added streams below the API, I'll have to listen 5 times.

What this also means is that the grouping notion should be a readable property - I believe that we currently only describe it as something that's actively created via clone().

Regarding code, no idea how @tfpauly has done this, but I believe that the NEAT implementation is like I describe here. For more details on this specific aspect, see: http://dl.ifip.org/db/conf/networking/networking2017/1570349380.pdf

**Comment by tfpauly** [comment]
@csperkins We create a Listener from a Connection to handle inbound streams associated with the same parent transport connection. 

@mwelzl Currently, our Listener object doesn't require calling Listen() for each new connection—you can get the event invoked many times, so it doesn't require knowing how many streams may be opened by the peer. In order to get back pressure, we're talking about having a window for how many new inbound connections will be allowed at a time.

**Comment by philsbln** [comment]
@tfpauly This solution sounds very reasonable – I guess we should do it the same way for TAPS and add that as Text to the API

@mwelzl Some comments:

1. It depends – if writing a server, you might want all streams of a multi-streaming connection grouped, but not all multi-streaming connections received through the same listener. So the behaviour wether to group should be a property of the Listener.

2. I would not group connections received through the same Rendezvous (analogous to server-style listener).

3. We might want to add a ``Stop()`` and a ``MaxPendingConnections``or  ``MaxConnections`` property to the listener

**Comment by mwelzl** [comment]
@philsbn:

1. I agree, but: just because groups may encompass more than the Connections from one Listener doesn't mean that it would be bad to always group the Connections from one Listener (i.e., group them among themselves, but maybe group them with others too). Besides, I think that wouldn't be the listener *deciding* anyway.

2. Just to understand this, are you saying "no, see my argument for case 1" ?  Then we're just discussing case 1, my answer is above. Otherwise I'd say: why not?

3. yes ... but what do you mean with `Stop()`? We have `Stop()`, just the semantics are not what I suggested. Regarding `MaxConnections`, I think that's a good idea - my own proposal was me overdoing "keep it simple, let's not add features". Nobody needs to use this unless they want to.

**Comment by mwelzl** [comment]
@philsbln 

1. Me too. I can imagine other things ( this paper of ours comes to mind:  http://heim.ifi.uio.no/michawe/research/publications/ctrltcp-infocom-gi-2018.pdf  ), but generally I agree and don't think we should complicate the API for this. But I'm getting confused: *you* wrote "you might want all streams of a multi-streaming connection grouped, but not all multi-streaming connections received through the same listener". That sounded to me like *you* want to support multiple streams, but from several listeners?!

2. ACK

3. Agreed!

**Comment by philsbln** [comment]
@mwelzl let me elaborate on this…

- You might want all streams of a multi-streaming connection grouped, e.g., all streams within  a QUIC connection
- You might not want all multi-streaming connections (e.g., QUIC connections) received through the same Listener object grouped
- You definitely do not want all  all streams of all QUIC connection received through one listener grouped (except if you have hierarchical groups that allows you to sort that out the cases above)

**Comment by mwelzl** [comment]
I agree with all this. Anyway I think it's a moot point: whether they're grouped or not is not up to the listener to decide? So grouping needs to be something that can be queried.

**Comment by philsbln** [comment]
Ok – fair enough – but I still think the Listener is the right place to _configure_ whether connections that come out of it should be grouped by default or not.

**Comment by mwelzl** [comment]
Not unless we have a concrete idea on what to do with this information inside the transport system.

=> I think no text update is needed as a result of this issue and lean towards closing it...

**Comment by philsbln** [comment]
I don't think we really need a text update for the grouping, but for the original question.

To address the handling of incoming streams in multi-streaming connections, I would like to have the solution @tfpauly outlined reflected in the API.

**Comment by abrunstrom** [comment]
One question on this, for @tfpauly, the description of your Listener object being able to accept multiple events, is that how it works in general or was that specif for a multi-streaming scenario?
As specified I am not sure that our Listen action does not allow multiple ConnectionReceived events? The text says 

> Listening continues until the global context shuts down, or until the Stop action is performed on the same Preconnection

**Comment by tfpauly** [comment]
@abrunstrom The listener object for all cases (both multi streaming and receiving brand-new transport connections) allows multiple events.

I think the existing text is a bit ambiguous, but it seems that "listening continues" implies that the event can certainly fire again.

**Comment by britram** [comment]
Revisit after #301 is done
