### ISSUE TITLE
Implementation should describe how to handle proxies/TOR

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#282]
Having proxies to go through on a system (SOCKS, HTTP Connect, etc) or a set of TOR endpoints requires the implementation to do some nested/recursive work, and pass down endpoints correctly to protocol instances. The implementation document should describe this.

**Comment by mirjak** [comment]
+1

**Comment by mirjak** [comment]
There is already text in 4.1.3.3. Protocol Options. Is that sufficient or do we need more?
