### ISSUE TITLE
Interface draft should describe a way to express transport-level padding for messages

### ISSUE THREAD

**Issue by chris-wood** [ietf-tapswg/api-drafts#286]
This could expressed as a property on outgoing messages. Should it then also be expressed as metadata for received messages?

**Comment by gorryfair** [comment]
This rather depends on why the transport API adds padding, and whether the transport API knows how much padding to add or the app, and finally how the padding is added.

On send, I understand your proposal, and that would be OK with me. It would also be fine to simply send "null" data as a part of the original data?

I am less sure of what should happen at receive. It could be that the transport does not forward padding upwards to the receiver if it was added by the stack at the sender. That would seem to be fine to me, and I don't (yet) know why the receiver would care, you may have a use-case.

**Comment by philsbln** [comment]
This sounds like three problems for me:
1) Padding at the application (I guess we should not care, unless done in a framer)
2) Padding added somewhere in the protocol stack
   - very generic thingy, depends on the protocols chosen after racing
   - may happen at multiple layers and add up
   - the application my want to specify it wants at least messages of size X on top of the IP layer
      - required for QUIC amplification protection
      - may be useful for probing and amplification protection for other protocols
      - the transport system can then choose whether padding is needed and where to pad
3) Protocol Specific Padding, which needs a property per protocol

I agree it would be nice to have some way of exposing "how much padding was added" as receive meta-data, but this would require more design on what  receive meta-data is and how it should look like.

**Comment by gorryfair** [comment]
Interesting.
I agree on (1) We do not care, but safely could mention if it otherwise creates doubt.
(2) QUIC can add that, and may choose to. TCP can't, UDP can't; UDP-Options could; etc. Any tunnel/framing can clearly do that. As a starting point I suggest we don't let the text talk to talk about this.
(3)   I suggest we also don't describe this, and leave this as a possible future thing to add once this current spec is published.

**Comment by britram** [comment]
Discussed at May interim -- we might want to separate the goal from the mechanism. Deferring this until QUIC (or some other protocol) actually implements it. Will be a good test of experimental extensibility of TAPS.

**Comment by csperkins** [comment]
And when we come to this in future, note that RFC 6562 suggests transport-level padding via Secure RTP as a security mechanisms to address certain threats. There are real use cases for this.
