### ISSUE TITLE
TAPS ARCH - Textual review to notes

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#299]
These are all comments on rev -03, and I think they can all be held to edit for the next revision.

(1)  SHOULD be defined to apply to multiple transport
- is this the same as:
 SHOULD apply to multiple transport

(2) mechanisms which
- should be:
mechanisms which,

(3) Connection Group:
- is now renamed:
TAPS Context: (or similar).

(4) within the same Connection Group are allowed be multiplexed
- is the /multiplexed/ the same as /cloned/ now?

(5) Is this normative:
  [I-D.ietf-taps-interface]

These are normative:
 [RFC8174] 
 [RFC2119]

**Comment by tfpauly** [comment]
Addressed the parts of this that are still valid with 3471e89
