### ISSUE TITLE
More expressive multipath transport property

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#303]
The current multipath selection property is an on/off selection.  We will eventually need something more expressive here to distinguish for instance between handover/back-up and aggregate multipath modes.

**Comment by tfpauly** [comment]
For reference, the Network.framework multi path property values are:

```
	/// Multipath services represent the modes of multipath usage that are
	/// allowed for connections.
	public enum MultipathServiceType {
		/// No multipath transport will be attempted
		case disabled
		/// Only use the expensive interface when the when the primary one is not available
		case handover
		/// Use the expensive interface more aggressively to reduce latency
		case interactive
		/// Use all available interfaces to provide the highest throughput and lowest latency
		case aggregate
	}
```

**Comment by philsbln** [comment]
If I remember correctly, we had something like this that got turned into a regular preference at some point in time. I agree that this expressiveness is useful, but can't this be achieved even better by also setting CostPreference + CapacityProfile?
