### ISSUE TITLE
Differentiating between bad selection property configuration and connection issues

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#307]
Per the interface draft, an InitiateError gets thrown both when the set of (protocol) candidates is empty as well as when it is not possible to establish a connection.
The distinction here is that an application can mend an error involving an empty candidate set while it does not necessarily have control over fixing issues related to the network. 
It might be useful to divide this into distinct two errors, one that points to an empty candidate set and one that points to issues during an actual connection establishment attempt.

**Comment by philsbln** [comment]
@MaxF12 closed this one and open issue #341 and #342 which are parts of a possible solution for this. Let's continue discussion in these
