### ISSUE TITLE
More editorial author comments on API

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#318]
In section 6.4:
This para opens with the words “Groups of Connections”
- Please check which letter groups should be capitalised in this section, I think it should be “Connection Group”, so this should be “Groups of connections”.
—
In Section 7:
“Data is sent in terms of Messages,”
- Is it true that “blocks of data supplied by the application are sent as Messages” 
- or what does “in terms of” refer to?
—
In Section 7.1:
“Message data is created as an array of octets”
- even I have a a hard time remembering 6-bit bytes, can we declare “octet”as historic and use “bytes”.
- is the data “created” or “transferred”
—
In Section 7.1:
“Applications can query the protocol property Maximum Message Size on Send to determine the maximum size allowed for a single Message.”
- I don’t know how the app does this across the API, can we be more clear? (It could be the example below seeks to explain this, in which case maybe a little wording change would help me?)
—
Section 7.2:
“There are several events” - should this be “Events”?
—
Section 7.2.1:
“and is no longer the responsibility of the implementation of this interface”:
- why use the words “the implementation of”, is there something more subtle that needs explained, or can these words be deleted?
—
Section 7.3:
“The simpler form of Send that does not take any messageContext is equivalent to passing a default MessageContext with not values added.”
- These read wrong: /not/ /is equivalent/, could this be better?
“The simpler form of Send, which does not take any messageContext, is equivalent to passing a default MessageContext without adding any values.”
- Also, what are values here: properties or something else?
—
Section 7.5:
“In order to reduce the overhead”
- please remove /In order/ to avoid any misunderstanding about ordering.
—
Section 9.1.2. Required minimum coverage of the Corruption Protection for receiving
- The default needs to be protect the entire message.

**Comment by mwelzl** [comment]
PR #330 addresses this. A detail below:

Regarding:
> Please check which letter groups should be capitalised in this section, I think it should be “Connection Group”, so this should be “Groups of connections”.

Sure this can (and should!) lead to some form of grouping of transport connections below, but it is meant as a construct applying to the Connections that an application sees - conceptually these are the ones that are grouped. So I think it should be "Connections", not "connections".
