### ISSUE TITLE
Issues concerning framers

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#322]
Hi, we now implemented (basic) framers in [PyTAPS](https://github.com/fg-inet/python-asyncio-taps), here are some things we noticed that might be of value for the upcoming interim:

- The current way the deframer is supposed to modify the octetstream is not very well specified, the deframer should probably have an interface to the connection on which it can either tell it how much of the stream it has removed or what the new stream is. 

- If the application enables partial receives, the framer needs a way to communicate to the connection that it only deframed part of the message.

- If there is an error during the deframing process (that is not caused by an incomplete message), the deframer needs some standardized behavior on how to indicate this. The connection should then throw an appropriate event, possibly an invalid configuration event (as mentioned [here](https://github.com/ietf-tapswg/api-drafts/issues/307)) since both are issues the application can actively remedy.

**Comment by tfpauly** [comment]
Please see the proposed changes in #323, and review!

**Comment by MaxF12** [comment]
These have been solved by the new version of framers, thanks.
