### ISSUE TITLE
Comments on new framers

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#340]
Just some points about the new text on framers in the API draft:

- In 10.2 it is specified in which order multiple framers run on incoming and outgoing messages, it is however never specified what the order looks like on Start and Stop events.
- In 10.6, "MessageFramer.DeliverAndAdvanceReceiveCursor" appears to be missing the "Data" argument that is present in "MessageFramer.Deliver".
- Also in 10.6, in the second paragraph it says:
> The application requests a specific amount of data it needs to have available in order to parse. 

When it is probably meant to say 

> The framer implementation requests a specific amount of data it needs to have available in order to parse. 

- While the framer implementation is able to notify the Connection that it has finished handling a Start event (by calling MessageFramer.MakeConnectionReady), there is no such way for Stop events.

**Comment by tfpauly** [comment]
As notes for the responses to these points:

- If there are multiple framers, the "lowest" one (the one closest to the transport) would receive start first, and the next would get the start event when the lower one is ready. Similar for stop.
- Good calls on the missing data argument and the typo re application vs framer.
- I was thinking to use the failConnection call to complete a stop, potentially with no error?
