### ISSUE TITLE
Allow error events to include reason

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#342]
Error events should be able to hand the application a reason that further details the circumstances of the error event being fired. This should be optional and doesn't have to be portable but an implementation should provide an enumerated list of all the possible reasons.

**Comment by mwelzl** [comment]
Just to be clear, you mean "...but an application should be provided with an enumerated list of ...", right?

**Comment by MaxF12** [comment]
Yes sorry, the TAPS implementation should provide a list of enumerated reasons for errors.

**Comment by mwelzl** [comment]
No problem. That's an easy text fix, I think.

**Comment by MaxF12** [comment]
Closed by #351
