### ISSUE TITLE
Listeners should have backpressure

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#343]
There should be a way to put back pressure or limits on the number of inbound connections for a listener. The two approaches are:

1. To have a one-to-one callback for listen -> received connect
2. To have a way to set a numeric limit of new inbound connections

My preference is (2). (1) has an issue of being very impractical for servers that don't know how many connections they'll receive, and may require them to call `listen` a thousand times without any other activity. (2) is more similar to how calling `listen()` on sockets work.

**Comment by mwelzl** [comment]
+1 on variant 2 - indeed it's common and known to people from sockets, and just seems like the easier and more efficient solution (albeit maybe less "beautiful", in a way).

**Comment by abrunstrom** [comment]
+1 on variant 2 as well.

**Comment by britram** [comment]
Do variant 2.

**Comment by mwelzl** [comment]
I believe that PR #350 fully addresses this; hence I'm closing it.
