### ISSUE TITLE
Framers: Move parts to Implementation draft

### ISSUE THREAD

**Issue by theri** [ietf-tapswg/api-drafts#344]
As discussed at the IETF 105 TAPS session:

I suggest defining framers as a set of functions that transforms messages into byte streams and vice versa (quite similar to what we have now, but replace "piece of code" with "set of functions"). And then we have to find words for the "Framers can also do a bit more negotiation, handshake, etc".

Also, I suggest keeping the following in the API draft:

- how to add a Framer to a Preconnection
- what functionality a Framer can implement
- how an application can interact with framer metadata through the Message Context

The rest I suggest to move to the Implementation draft, e.g., the "How can a Framer be implemented". It's an example, but Framers can also be implemented in different ways.

I'm willing to contribute text if needed.

**Comment by tfpauly** [comment]
Done with #359!
