### ISSUE TITLE
Fix "Implementing maintenance" section

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#356]
In line with the API draft, this section should now probably be called "Implementing Connection Management", and it should avoid protocol-specific text. Making this more confusing, there's currently a "Managing connections" subsection there, which is full of protocol-specific references to RFC 8303 and TODO's - very very old text from me.

I think that this should all be removed, and replaced with something more appropriate. I don't have a very good idea about the new text that should go in there though, which is why I'm opening this issue.

This relates to #248: maybe, at this point, if this is done, #248 is already fully addressed.

**Comment by tfpauly** [comment]
Fixed this up with 1ac1e18. I retitled several of the sections, and made the text in connection management explain how to handle setting properties, and passing along errors. Let me know if you think this satisfies things, @mwelzl!

**Comment by mwelzl** [comment]
Sorry, I see I'm too late - but, FWIW, I'm fine with it   :-)   thanks a lot for doing this!
