### ISSUE TITLE
Update wording where interface to security protocol implies racing/abstraction

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#364]
Under "Protocol Stack Equivalence", for example, text like

> Both stacks MUST offer the same security properties

needs to change to conform to the rework of the security document. This is related to #363.

**Comment by theri** [comment]
Yes, I think this is part of the "protocol stack equivalence" issue #305.
As #305 is assigned to me, I'll just self-assign this one and close both once this is done.

**Comment by tfpauly** [comment]
Fixed by #389
