### ISSUE TITLE
Protocols in Figure 2

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#374]
I find the box Transport System Implementation with the "(UDP, TCP, SCTP, DCCP, TLS, QUIC, etc)" confusing in Figure 2. How should that be read? It looks like the Transport System Implementation is the protocols which I think is not the intent. In Figure 3 we have the Protocol Stacks as its own box which makes more sense I think. I am sure we discussed this figure before, but looking at it now it looks strange to me.

**Comment by mwelzl** [comment]
We (group in Singapore) solved this by adding the word "using" in front of the protocols  :-)

**Comment by tfpauly** [comment]
Added!
