### ISSUE TITLE
Multiple receives convenience feature

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#375]
The basic API forces applications to individually queue each receive. This can seem unituitive and become annoying. 
I suggest the addition of a separate call to the convenience features section so we don't have to change the signature of the original receive call and keep the basic API minimal and not redundant.

**Comment by mwelzl** [comment]
Or we just add a "multiple" parameter to the normal recv call, which would automatically imply that this would only be used to receive multiple messages of the same length, thereby making things simpler?

**Comment by MaxF12** [comment]
Right, I had hoped we could also get something in that would just receive all incoming messages until some form of stop is called. 
By adding a parameter for how many receives you want to queue you are not changing much about the (at least for me) core issue, which is that as of right now, you basically always just put another receive call into the handleReceived and handleReceivedPartial callbacks. 

I was thinking more along the lines of havig a startReceive(multiple?) Call that just automatically queues the reception of new messages until the optional multiple parameter is reached. If there is no multiple specified, it will just queue receives until the connection is closed. Then there would be stopReceive() which can be called at any time to stop the queueing of new receives.

**Comment by philsbln** [comment]
Just add an optional parameter to the he recv call how many messages to receive, that can be infinity?

**Comment by tfpauly** [comment]
This mechanism is the way that we get backpressure. If you don't have this mechanism, you fundamentally lose flow control. I'm quite concerned about changing this.

You can certainly do a receiveMultipleMessages (with a max number of messages to receive in a batch), but that still needs an individual callback.

**Comment by mwelzl** [comment]
Yeah, and I'm already somewhat sorry for bringing this up. In fact these possible complications are what made me decide against opening the issue after all...   I guess people could just implement this on top of our single recv anyway if they wanted to?

**Comment by britram** [comment]
This is a convenience feature. At this stage, adding them doesn't seem like the right thing to do.
