### ISSUE TITLE
Multicast impact on architecture?

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#382]
We have the following in the architectire draft:

> Connection Received: Signals to an application that a given Listener has passively received a Connection.

Should we remove "passively" now that we are adding multicast? Or we go with the main use case?

**Comment by tfpauly** [comment]
I think it's still technically passive. Perhaps you joined a group explicitly when you called Listen(), but the action of transmitting of packets that become a new connection object is still the responsibility of the initiator (the one sending multicast traffic)

**Comment by tfpauly** [comment]
Discussed in Singapore: while passively may be technically correct, it also adds no value. So we can remove it.

**Comment by tfpauly** [comment]
Fixed
