### ISSUE TITLE
Experimental cost property: cost preference

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#384]
You've got to let me know: should this stay or should it go?

I think it should go.

**Comment by gorryfair** [comment]
I like the idea as one direction for a future vision - but I don't like the idea of having this section in this document, and the think the annexe does not help.

I propose we should now remove all appendix A, A.1, and A 1.1.1.

Gorry

**Comment by philsbln** [comment]
I would prefer to let this stay (and move it into the main text) as it is something I got asked about whether it is in by application developers. It is there to avoid the abuse of interface type and feed into things like Apple's Low data mode.

@tfpauly do do have opinion on that? How is this done in network framework?

**Comment by tfpauly** [comment]
We definitely do this, but I don't think we should necessarily specify it here. Let that be another document, since I fear ratholing on this will hold up the document.

**Comment by philsbln** [comment]
As this is the last advisable concept in the API that does not directly map to something in MINSET, lets' remove it and maybe start an extension with application intends once the documents are done.

**Comment by mwelzl** [comment]
I'll remove all of appendix A and push this directly to the master branch instead of making a PR. Not much to review.
