### ISSUE TITLE
A surprisingly few number of NiTS in Arch

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#392]
I just read Arch and have the following NiTs which I think we should address:

/Listeners by default register with multiple paths/
ought this to be:
/Listeners, by default, register with multiple paths/

/A Framer is a data translation layer that can be added to a Connection to define how application-level Messages are transmitted over a transport protocol. /
- I think this should be (because I don’t think they are protocol specific)  
/A Framer is a data translation layer that can be added to a Connection to define how application-level Messages are transmitted over the transport service. /
- 
/to retransmit in the event of packet loss,/
- better to avoid event here :-)
/to retransmit when there is packet loss,/

**Comment by MaxF12** [comment]
I am just gonna add a few more nits here:

- The Listener object in figure 4 is a bit awkward, it appears as if the Listen() call appears out of thin air while per the API it gets called on the preconception object like Initiate() and Rendezvous(). 
- In section 4.1.1, there are 5 references to section 4.1.2, is it really necessary to have that many?
- Point 2 in section 4.2.3 only talks about required transport services, the same should probably be said about prohibited services, i.e. "both protocol stacks MUST NOT offer transport services prohibited by the application"

**Comment by philsbln** [comment]
Let me add to this:
 - Section 1: print send() and recv() in fixed-with font [HTML/XML issue only] 
 - Section 2 - Figure 1: socket() [with the brackets] looks odd in the figure title

**Comment by philsbln** [comment]
@gorryfair I fear framers may be specific to the underlaying protocol, e.g., for SIP slicing messages out of TCP stream whereby doing nothing for SCTP and UDP

**Comment by gorryfair** [comment]
In relation to frames I think I only asked to add /service/ instead of protocol... I don't understand how Phil's comment reacts to that

**Comment by philsbln** [comment]
@gorryfair I think protocol is correct here and would not change the sentence.

**Comment by gorryfair** [comment]
OK - so I think you are saying the framer depends only on the specific next protocol, rather than upon the transport service that was offered? - It is still not clear to me that this is correct.

**Comment by philsbln** [comment]
@gorryfair that is a fairly good question… 
 - The behaviour of the framer defiantly depends on the transport service provided (which may be a subset or superset of the transport service requested). 
 - A framer needs to support all possible outcomes of the transport services requested
 - It may optimize based on the protocols it actually finds, e.g., turn into a no-op with the transport preserves message boundaries.
 - Whether the next protocol is a sufficient representation of this is unclear to me. Maybe not, if one thinks of supporting arbitrarily large messages and UDP over IPv6 with and without fragmentation…
