### ISSUE TITLE
Slim down per-protocol behavior, move other mappings out

### ISSUE THREAD

**Issue by JonathanLennox** [ietf-tapswg/api-drafts#398]
Right now, the per-protocol behavior is specified in Implementation, which is an Informational document; however, this stuff really should be specified normatively.

So either they should be split out into (one or more?) separate documents, or Implementation should be made Normative just for the sake of one of its sections (which imo would be weird).

**Comment by philsbln** [comment]
I guess having a separate document for the per-protocol behaviour makes a lot of sense.
This document than can also define names for protocol specific properties.

**Comment by tfpauly** [comment]
Interim discussion: considering splitting off a non-informational document for mapping definitions

**Comment by abrunstrom** [comment]
Last discussion ended in agreement on splitting out protocol mappings. Two options were discussed 1) taking out all protocol mappings, 2) leaving TCP and UDP  as the two basic protocols and moving the other mappings. Good if we can conclude on which path to take.

**Comment by gorryfair** [comment]
I suggest that keeping UDP and TCP in here could be a simple expedient, especially if we make it clear that other RFCs can specify additional mappings. These two are very long-established transport protocols, and I think we can rapidly conclude this spec using them. Whilst I would be very happy to also see bindings for other important transports, that seems like something that could delay the group.

**Comment by tfpauly** [comment]
Leave minset protocols (UDP, TCP, SCTP, MPTCP), and define the template for new mappings.

Split out drafts: (TLS + DTLS), QUIC (and fallback to TLS, maybe join with TLS), HTTP

**Comment by mwelzl** [comment]
Just a small correction: minset also includes UDP-Lite, and the LEDBAT congestion control (the latter should probably be skipped since its encapsulation still isn't spec'd).
