### ISSUE TITLE
Event handlers: MUST they always be registered?  (or else..?)

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#404]
In section 4, we say: "Messages are received asynchronously through event handlers registered by the application. Errors and other notifications also happen asynchronously on the Connection."
This does not explain whether event handlers MUST be registered for all types of events (I guess not?), and what happens when no event handler is registered (I guess some reasonable default behavior - but shouldn't we be explicit about this?).

**Comment by MaxF12** [comment]
I definitely think they should not be required for all events (especially errors). 
I would assume that an event only gets thrown if an event handler is registered.

**Comment by tfpauly** [comment]
I think it is important to allow certain events not to be handled by applications. That's one goal that I've had in Network.framework. A minimal application not catch all edge cases, but it can certainly ignore events it doesn't do anything special with.

For example, an application can not register any handler for a connection becoming ready, if it instead just sends, and waits for a send to succeed or fail.

**Comment by csperkins** [comment]
If there are certain types of event handlers that MUST be registered, then we need to be explicit about that. 

The others are, presumably, SHOULD register a handler?

**Comment by mwelzl** [comment]
I very much agree with folks that we should not require all event handlers to be registered!

However, the text currently just isn't explicit about these things at all. Indeed: if something MUST be registered, the text should say so. But also, if an event handler is not registered for some events, then the text should explain that this is ok, and then, XYZ will happen.

**Comment by theagilepadawan** [comment]
Absolutely agree. Require the application to register all event handlers would make the API highly unflexible!

Could it be an idea to require certain event handlers to be passed with key API calls like `Preconection.Listen()`? It doesn't make much sense to start listening without a handler for incoming connections.

**Comment by philsbln** [comment]
I see no event in the API an application MUST subscribe to, but there are a lots it should. 

What might need mentioning is that some events may have implementation-specific default handlers that do some thing (e.g., exit the application) and the application should not assume ignore everything is always safe.
