### ISSUE TITLE
API: Specifying local interfaces as Local Endpoint VS. as a Selection Property

### ISSUE THREAD

**Issue by theri** [ietf-tapswg/api-drafts#410]
When reading the current API draft, I was wondering the following:

If an application wants to specify one or multiple local network interfaces, it can either set the Local Endpoint(s) or it can set the "Interface Instance or Type" Selection Property.
I think both ways are valid and should exist, but I'm wondering if we should specify anything on the interaction of these two ways to do a similar thing.

For example, should we explicitly mention the Selection Property in Section 5.1 ("Specifying Endpoints"), to make readers aware that there is a "better" way to do this, which allows more flexibility?

Also, if an application specifies conflicting things, I guess this leads to an InitiateError, ListenError, or RendezvousError. Our current text already says this for the InitiateError:
> "An InitiateError occurs either when the set of transport properties and security parameters cannot be fulfilled on a Connection for initiation (e.g. the set of available Paths and/or Protocol Stacks meeting the constraints is empty) or reconciled with the local and/or remote Endpoints"

But should we make this particular issue more explicit here and/or should we add it for the ListenError or RendezvousError?

**Comment by mwelzl** [comment]
> For example, should we explicitly mention the Selection Property in Section 5.1 ("Specifying Endpoints"), to make readers aware that there is a "better" way to do this, which allows more flexibility?

I think so, yes!
Regarding the error in case of a conflict:

> But should we make this particular issue more explicit here and/or should we add it for the ListenError or RendezvousError?

I think so, yes - to all your questions: make it more explicit, state it in the description of both the ListenError and RendezvousError.

Just my 2 cents
