### ISSUE TITLE
Do we need to say more about authentication and encryption?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#413]
I wondering if we should to talk a bit more about authentication in the the arch doc. The API doc has the concept of security parameters, however there is no discussion about this in the arch document. 

Also, just double-checking: private keys and certificates/identify can be set as a security parameter of a pre-connection. However, is that really a connection parameter or rather a local endpoint property?

**Comment by tfpauly** [comment]
To match the API, add Security Properties to Section 4.1.2.

**Comment by tfpauly** [comment]
Try to associate with the endpoint?

**Comment by tfpauly** [comment]
Add to figure 4 too

**Comment by britram** [comment]
closed by #506, I think?
