### ISSUE TITLE
Is the Local Endpoint "optional"?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#414]
the arch doc says:
"Local Endpoint: The Local Endpoint represents the application's
      identifier for itself that it uses for transport connections; for
      example, a local IP address and port."
This sounds like I always need some kind of identifier. However, I guess there should also be an option where I don't constrain the local interface and identifier at all and the transport service can select one, right? If that is true maybe we can say this here explicitly?!

**Comment by MaxF12** [comment]
In section 4.1.1 it is specified when the local endpoint is required (i.e. on a listen and rendevousz) and when it is optional, is that sufficient?

**Comment by mirjak** [comment]
Yes, I noticed that later. But just to be fully clear we could also say something more here.

**Comment by britram** [comment]
So, architecturally, here is *always* a local endpoint specifier, but in most client-side use cases using initiate, it will be a special local endpoint that specifies "any/all available local endpoints".

IMO anything beyond that is an API detail, so I'd recommend closing this with no change to Arch.
