### ISSUE TITLE
add example for "information about the received Message"?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#416]
arch doc sec 4.1.4:
"When receiving Messages, Message Properties can contain
      information about the received Message, such as metadata generated
      at the receiver and information signalled by the remote endpoint."
Maybe provide an example here...?

**Comment by mwelzl** [comment]
Suggestion: ECN, which is information given from UDP in the form of such metadata.

**Comment by tfpauly** [comment]
QUIC stream identifier example works

**Comment by tfpauly** [comment]
Final message is in API, just use that

**Comment by britram** [comment]
closed by #505
