### ISSUE TITLE
Add Framer to Figure 3

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#417]
Reading something about framers in section 4.1.4 came actually a bit as a surprise to me as we don't talk a lot about framer earlier in the document (yes there is one forward reference in section 2.2 but that's it). Now that we have message in Figure 4, we should maybe also add framers...?

**Comment by mirjak** [comment]
Also maybe we should say a bit more what framers are than we currently do?

The current text is:
"   *  Framer: A Framer is a data translation layer that can be added to
      a Connection to define how application-layer Messages are
      transmitted over a transport protocol.  This is particularly
      relevant for protocols that otherwise present unstructured
      streams, such as TCP."

We could probably add to this:
"A framer can define a bit pattern or syntax such as a length field or prelimiter that is pre- or suspended by the transport service to the message's bytes and is know by the transport service or application on the other endpoint to phase the received bytes into a message."

**Comment by tfpauly** [comment]
Framer goes at bottom of API above implementation

**Comment by mwelzl** [comment]
For consistency - while you're at it, please fix the consistency conflicts with
https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-connection-state-and-orderi
(a few small things)
