### ISSUE TITLE
Acknowledgements in Arch

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#419]
As I'm not an author, can you add me to ack section, please... :-)

There might be other people missing....

**Comment by britram** [comment]
actually, should we add you as an author to arch?

**Comment by mirjak** [comment]
I'm happy to be an author, however, no sure I actually wrote any text (I don't think there is much left from the postsockets text...?). Also, I guess we already have too many authors. If I get added, I'm fine to be in an authors section at the end of the doc.
