### ISSUE TITLE
Syntax Preconnection

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#426]
Currently we define a Preconnection like this:
Preconnection := NewPreconnection(LocalEndpoint,
                                        RemoteEndpoint,
                                        TransportProperties,
                                        SecurityParams)

And then use it in the examples e.g. like this:
   Preconnection := NewPreconnection(None,
                                     RemoteSpecifier,
                                     TransportPreperties,
                                     SecurityParameters)

But should we do this instead:
Preconnection := NewPreconnection(LocalEndpoint?,
                                        RemoteEndpoint?,
                                        TransportProperties,
                                        SecurityParams)

I know that is also a bit confusing but maybe more inline with the syntax we define. Or we probably need to at least define the keyword "None"...

**Comment by theri** [comment]
I think your proposed syntax change makes sense.
When we first wrote this, we didn't have optional parameters yet, but now that we do, let's use them!
