### ISSUE TITLE
API, sec 5: SHOULD add Framers

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#427]
In the API doc sec 5 says.
"Message Framers (see Section 10), if required, should be added to the
   Preconnection during pre-establishment."
Should this be SHOULD or even MUST? If SHOULD is correct I think we need to say slightly more about when it makes sense to add a framer later.

**Comment by tfpauly** [comment]
I think it should be "can be added..."; not normative, just descriptive of fact.

**Comment by gorryfair** [comment]
Can we start with the "If' perhaps...
"If messages frames are to be used, they MUST be  added to the
Preconnection during pre-establishment."?
