### ISSUE TITLE
selection algorithm (text in API doc)

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#429]
In section 5.2. in the API doc:
"Internally, the transport system will first exclude all protocols and
   paths that match a Prohibit, then exclude all protocols and paths
   that do not match a Require, then sort candidates according to
   Preferred properties, and then use Avoided properties as a
   tiebreaker.  Selection Properties that select paths take preference
   over those that select protocols.  For example, if an application
   indicates a preference for a specific path by specifying an
   interface, but also a preference for a protocol not available on this
   path, the transport system will try the path first, ignoring the
   preference."

This sounds rather like an example algorithm that should maybe go into the implementation doc instead? Or is there any part of this that we need to specify normatively in order to ensure that all systems implement the same?

**Comment by theri** [comment]
This goes back to issue #149 on "conflicting policies". At the time, we decided that there must be a deterministic outcome, therefore, text was added to both the API and the Implementation document, see #169. 
If we keep it that way, perhaps the text here should point out that the goal is to resolve conflicting policies, so we achieve a deterministic outcome.

**Comment by mirjak** [comment]
Ah okay, thanks for the background info; missed that. I think we need to use normative language here then. Maybe also a separate subsection makes this more prominent.

**Comment by gorryfair** [comment]
This reads to me like the rules for processing polices rather than an example algorithm. I think it is part of the API... Normative language would be good and a stronger opening that explains why the rules exist.

**Comment by mwelzl** [comment]
I don't think a separate subsection would make this a better read - this fits fine as it stands, as an intro to the transport property specification IMO. Regarding normative language, that's a separate discussion. So, can we close this issue?

**Comment by theri** [comment]
Agree that we don't need a separate subsection. I can try to tweak the beginning of this part a bit to explain why the rules exist as @gorryfair suggested.
Regarding normative language - we definitely have it in the API draft, right? So why not have the discussion on it here as well?
if we're serious about deterministic outcomes, I guess the whole thing needs to be a MUST, right?

**Comment by mwelzl** [comment]
Sorry, true, that normative language debate was about the arch draft, and we definitely have it in the API draft. So yes, let's discuss it here. I also think a MUST would make sense.

**Comment by philsbln** [comment]
So the order of filtering out require/prohibit is not important (outcome is the same) - making the order a MUST does not make sense. Also, first sorting by preference and then filtering has the same outcome as doing it the other way around. the only thing we need to say is that filtering MUST happen and sorting SHOULD happen.

**Comment by mwelzl** [comment]
ok - I have to admit I didn't think this through, I just agree that we want a deterministic outcome from this.

**Comment by philsbln** [comment]
Why did we require a deterministic behavior in first place? 
Does this prevent TAPS implementations from running experiments like Apple did with TCP SACK and ECN? Does this prevent probabilistic path probing?

**Comment by gorryfair** [comment]
This was discussed in the TAPS BoF? ... I thought it was about developers being assured that X will happen if they choose Y and not finding the ground shifting as they use the interface.

**Comment by tfpauly** [comment]
Interim: Prefers and avoids allow the implementation to decide the ordering and weighting; require and prohibit are the only hard requirements. Applications should be able to cope with any possibility that isn't prohibited.

Likely should add implementation text to say how preferences weight racing.

**Comment by theri** [comment]
During the interim discussion, we found that #496 was too strict and limiting, so we opted for another approach that moves the selection algorithm to the Implementation draft. 
I'm preparing another PR implementing these changes.

**Comment by abrunstrom** [comment]
The text that ended up in the implementation draft is not fully consistent with the racing text, opening a new issue for this and closing this issue.
