### ISSUE TITLE
Default values for Interface Instance and PvD

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#435]
We require implementations to have default but we don't provide any recommendation for interface and PvD.

**Comment by theri** [comment]
For Interface, this would the default be to set "Ignore" on all available interfaces, right? This indicates that the application has no preferences of its own, so the implementation can apply some default system policy. Also, if the application specified some local endpoint, this might constrain the actual interfaces used (related to #410).
If we try to phrase this as (Preference, Enumeration), it reads a bit weird though: ("Ignore", "Cellular") and ("Ignore", "WiFi"), for example. So perhaps we should just write text saying that the default is to set no application preference.

**Comment by mirjak** [comment]
I think text is fine as well but we need to say something.
