### ISSUE TITLE
Message size

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#443]
"Maximum Message Size on Send

   Name:  send-msg-max-len

   Type:  Integer (read only)

   This property represents the maximum Message size that can be sent."

What the maximum message size for streams...? We should specify what should be returned if there is no limit. 

Or is the assumption that this will the return the maximum local buffer size? Would that be semantically correct?

**Comment by gorryfair** [comment]
Is this intended to be the largest size of data block that can be sent using a send operation? - In which case, I think there is always a limit?

**Comment by mirjak** [comment]
Yes that limit exists but that seems to mix up two different things. If that it what we want, we need to say this explicitly.

**Comment by gorryfair** [comment]
Yes. I think we should. I am not sure what we mean by maximum message size... but maybe others want to explain?

**Comment by mwelzl** [comment]
@gorryfair asked "Is this intended to be the largest size of data block that can be sent using a send operation?" - the answer is yes. Is the description of this property not clear enough? It reads: "This property represents the maximum Message size that can be sent."
Why does this mix up two different things? Maybe you're thinking "sent" as in "can leave the host", while I'm thinking "sent" as in "used by a send call". So maybe that sentence should be rephrased to be more explicitly about the latter.

**Comment by mirjak** [comment]
It seems we have different understandings of this property, so we clearly need to clarify this. But I guess we first need to agree what it actually means. Or maybe we just call it Maximum Buffer Size?

**Comment by mwelzl** [comment]
Maximum send buffer size would capture what it means, but it describes something internal. I'd prefer to use your phrasing from above in the description: "the largest size of data block that can be sent using a send operation? "

It's the added "using a send operation" that makes it unambiguous.
