### ISSUE TITLE
Do we need msg-reliable and lifetime?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#446]
These two message properties are interconnected and therefore have a dependency. I would rather prefer to only have one property. Lifetime already has one "special" value (infinity) to indicate reliable transmission. We could also declare 0 as special to indicate unreliable transmission (only transmit once and never retransmit).

Also should we rather use -1 for reliable? And also do this for other properties that currently have meaning for infinite? Or would it be more correct to say max instead of infinite?

And more more question on lifetime: Do we need an event that indicates to the application that transmission was aborted due to lifetime expiry?

**Comment by mwelzl** [comment]
> These two message properties are interconnected and therefore have a dependency. I would rather prefer to only have one property. Lifetime already has one "special" value (infinity) to indicate reliable transmission. 

No. Quote from the description of lifetime:

> Setting a Message's Lifetime to infinite indicates that the application does not wish to apply a time constraint on the transmission of the Message, but it does not express a need for reliable delivery; reliability is adjustable per Message via the "Reliable Data Transfer (Message)" property (see Section 7.4.7). 

Consider an unreliable, congestion controlled transport (e.g. QUIC with datagrams). Specifying a "lifetime" means that, once the lifetime has expired, the Message can be deleted from the send buffer. Setting "lifetime" to infinite means that the Message will never just be deleted from the send buffer. This does not at all guarantee that the Message will be retransmitted in case it was lost.

> Also should we rather use -1 for reliable? And also do this for other properties that currently have meaning for infinite? Or would it be more correct to say max instead of infinite?

The mistake is the mix of "integer" and "infinite". The latter is okay for type "numeric". I have already fixed this in PR #403 (which is still open).

> And more more question on lifetime: Do we need an event that indicates to the application that transmission was aborted due to lifetime expiry?

That's the Expired Event, see section 7.3.2.

**Comment by mwelzl** [comment]
Can we close this issue?

**Comment by tfpauly** [comment]
Interim: Agreed with @mwelzl, closing.
