### ISSUE TITLE
Is "Singular Transmission" the right term

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#447]
When I initial read the heading I thought this is again about reliability. May we can call this single-segment or something...?

**Comment by gorryfair** [comment]
Well it's a term - I don't like it much. Single segment doesn't mean it's all in one IP packet (it means it's all in one transport segment). 
We could just say sending as a single IP packet.

**Comment by tfpauly** [comment]
Interim: proposing to rename to something more simple like Don't Fragment? We don't have a good name.

**Comment by gorryfair** [comment]
Don't Fragment seems good too me - and tidy this sentence:
OLD: /Attempts to send a message with this property set
   with a size greater to the transport's current estimate of its
   maximum transmission segment size will result in a "SendError"./
NEW:  /Setting this property causes a "SendError" when
   an attempt is made to send a message
   with a size greater than the transport's current estimate of the
   maximum packet size./
