### ISSUE TITLE
Right design for Partial Send

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#448]
The section on partial send says:

"All data sent with the same MessageContext object will be treated as
   belonging to the same Message, and will constitute an in-order series
   until the endOfMessage is marked.  Once the end of the Message is
   marked, the MessageContext object may be re-used as a new Message
   with identical parameters."

Can we reconsider for a second if that is really the way we want to design this? This is really implicit and therefore an easy source for errors. I guess we could alternatively use an explicit message identifier...? Or the send action always return an identifier and for subsequent sends we input this identifier again? Or someone has a smarter idea?

**Comment by mwelzl** [comment]
I don't have my head buried in code like some others here (@tfpauly, @MaxF12 , ..), so I guess that these folks should speak up - but just from reading this, I agree that the current design sounds like an easy source for errors.

**Comment by tfpauly** [comment]
I'd prefer to just remove the part that mentions reusing the same object. That's an implementation detail (and a perf optimization). The rest seems correct.
