### ISSUE TITLE
Right semantics for batch sending?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#449]
batch sending, as currently specified, means that you already have to have all messages ready in the application because you can declare a patch. That means you have to potentially "buffer" some message in the application. Wouldn't it may be better/easier to have a message property that indicates that a certain message should wait (probably up until a maximum time) for the next message and then buffer it in the transport instead?

**Comment by tfpauly** [comment]
We can just clarify the text that the batch may be an arbitrarily long-running block of code, and not require knowing up front all of the data.

**Comment by tfpauly** [comment]
Could also allow begin batch/end batch.

Explain use case around optimizing send performance.
