### ISSUE TITLE
Early data property on receive

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#453]
I'm not certain about the semantics used here, given this property can only be true once in one specific message.

Did we discuss already the option of providing a message together with the ConnectionReceived event? You cannot set the message length and max length in this case but you can set a default value before you create the listener and that would be used then. Or we could even have a separate ConnectionReceivedAndMessage function for application that care about early data.

**Comment by mwelzl** [comment]
I personally find this uglier than what we have: if I don't care about a Message being idempotent or not, I can write the same code to receive a Message, whether it arrives as early data or not, and just ignore the "early data" Message property. With your proposal, I can't do that.

**Comment by mwelzl** [comment]
Can we close this?
