### ISSUE TITLE
Message context

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#455]
In the section on message context we have the following text:
"Message Contexts can also be used to send messages that are flagged
   as a reply to other messages, see Section 7.2 for details.  If the
   message received was send by the remote endpoint as a reply to an
   earlier message and the transports provides this information, the
   MessageContext of the original request can be accessed using the
   Message Context of the reply:

   RequestMessageContext := MessageContext.GetOriginalRequest()"

Is that even possible? How can the transport now that a received message is a reply? Just because it was received on the same stream? Not sure if the transport can every say this for sure...?

**Comment by tfpauly** [comment]
If you're writing on a QUIC stream with a message, the data coming back on that stream is the message associated with it, etc.

**Comment by mirjak** [comment]
Hm, I'm not sure that correct to assume. E.g. assume both ends send a request on the same bidirectional stream. If you receive the request from the other end right after you've send your request, you'll assume that the reply. 

Why is the function actually needed?

**Comment by mwelzl** [comment]
I think in the one-Connection-becomes-one-stream model, this function is not needed. If messages are spread across streams, then this function is necessary to ensure that the response goes on the same stream.

**Comment by britram** [comment]
suggest this as a topic for interim discussion.

**Comment by mwelzl** [comment]
Michael will look at the interim minutes and figure out what needs to be done.

**Comment by mwelzl** [comment]
I found the minutes, but to no avail:
https://etherpad.ietf.org:9009/p/notes-ietf-interim-2020-taps-01

Can we just discuss this right here some more?
Above, I said that this seems to me to only be necessary when messages are spread across streams (every message is a new stream). However: the abstract entity that we already expose to an application, which incorporates the desired request-response logic, is the Connection.

So: as an application programmer, if I want to make sure that there's a clear request-response relationship between two messages, then I just need to use the same Connection for them and keep it open for this communication. How this Connection is mapped below is a different question... but anyway, this is how a programmer would convey the request-response relationship.

From this, I conclude: @mirjak is right, this doesn't make sense and should be removed.

I'm probably missing something. Tell me!

**Comment by britram** [comment]
So IMO the underlying issue here is that certain transports might actually be able to bind messages to replies (QUIC), but not all can, and there's no great way to let the application know that you can't without doing unexpected things to its code flow.

I'd support removing it.
