### ISSUE TITLE
Framers again...

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#457]
I know we moved some text about framers into the implementation doc but that really doesn't seem right when I look at it now.

The section about framers in the implementation doc is the only section that defines an interface which probably is already an indication that just moving this text there was not right. However, also the text in the API doc seems now incomplete. 

I think we should move it back and rather define some real simple examples framers in the implementation document (just a prefixed length field (as many UDP mapping use) or maybe even an example implementation for STARTTLS). Further after moving it back we could figure out if really all parts of the interface are necessary or if there would be a more minimal interface that we could use. E.g. I'm not sure about the FailConnection() call or at least I think this could need more explanation.

**Comment by mirjak** [comment]
Also I think it would be good to the section on framers earlier in the doc. I will open a separate section to propose some restructuring (as I also think it would be good to have the connection properties earlier).

**Comment by MaxF12** [comment]
I think the real problem with framers is that we left them vague to avoid having to worry about all the implications they bring with them (which are a lot as they impact almost every stage of the life of a connection) but also to not limit what implementations can do with them by making them very rigid. 

But I do agree that the text in API feels somewhat incomplete. Maybe one solution would be to explain what a framer should at least be able to do in the interface draft without specifying the actual API that is in implementation. 
I think we all agree at _when_ a framer should be able to interact with the connection just not _how_ that interaction is supposed to look like (as that is highly implementation specific).

**Comment by tfpauly** [comment]
I disagree that we should move the text back into the API document, since the group was very clear before that the details should be moved to implementation. The boundary we defined was to leave in the API: (a) the definition of what a framer is and why it's used and (b) the interface an application uses to add a framer to the connection.

The API text should be complete with regards to how a *user* of a framer performs actions. What specific text would we want to add here?

**Comment by mirjak** [comment]
First as I say that's the only piece of additional interface we define in the implementation draft which already is a sign that it's maybe not ideal. 

But for the API draft the part of how a framer interact with the transport is really unclear and looking at the part of interface, that now defined in the implementation doc, makes it really clear.

I disagree that this part of the interface can or should be left to the implementation. The fact that you have to call the framer before you start any transmission and the events a framer should be aware of are generic and nothing implementation specific.

**Comment by mirjak** [comment]
In the implementation draft we say:
"A Message Framer is primarily defined by the set of code that handles events for a framer implementation"

My assumption is that a custom framer implementation could be part of the application logic and therefore we need to define this interface as well.

However looking at the implementation draft I guess I now confused myself about how this actually works. Why is the sending logic asynchronous? Isn't this something that happens iteratively when the application calls send(). How would that actually work? I thought the application could just call Connection.send() and then the connection could call MessageFramer.send() and that would simply return a modified message... can you give an example for sending and receiving based on the interfaces currently defined in the implementation draft?

Also please note that while I think the interface definition belongs in API draft, however, there are comments about copying and curser handling which should/could probably say in the implementation draft.

**Comment by tfpauly** [comment]
Interim:

Add to -interface:
- Explain that framer(s) is in between the rest of the protocol stack and the application
- Intercepts calls to start/stop and send/receive

And just leave as is, and have another framers document in the future once we get more details.
