### ISSUE TITLE
Connection Groups, Priority, and Cloning

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#461]
Section 11.1.3 of the API says about Priority:
"As noted in Section 6.4, this property is not
   entangled when Connections are cloned."
Not sure what this means. I though when you clone a connection you would actually take the priority of the cloned connection but then you can change it independently for each connection in a group. Or what's the priority after cloning? Back to the default of 100? We should say this explicitly. Or maybe you even want to provide the priority while cloning?

Actually looking at this now again, I think we would need to specify cloning a bit better anyway. I assume that calling clone() on a multiplexing capable connection would create a new stream; in case of quic is would only create local state but no on-the-wire singling. However if you call clone on a TCP connection, is that basically an initial() call that triggers the TCP handshake? We should say this explicitly.

**Comment by theri** [comment]
I'd say it's exactly as you thought:
When you clone a Connection, all Properties are copied (including the Priority), but then they are not entangled: If you change the Priority on the cloned Connection, the Priority on the original Connection stays as it was. If Priority was entangled, then it would change on both Connections if you change it on one of them.
But yes, perhaps this is confusing and the text should be more explicit.

The part on specifying cloning better: There's text on this in the Implementation draft on what happens with Clone() for each protocol. But maybe we can say in the API document that Clone() might trigger on-the-wire signaling or it might not, depending on the protocol.

**Comment by mirjak** [comment]
Yes, both additions/clarification would be good.
