### ISSUE TITLE
Do we want to keep appendix about Go sample implementation in API doc?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#469]
Do we want to keep appendix B and if so should it point to Theresa's implementation instead (I'm not indicating that Theresa owns this implementation or that she is the only implementor but I think people know what I mean)?

**Comment by gorryfair** [comment]
Sorry for a stupid question: Why is this API - not implementation?

**Comment by theri** [comment]
I guess originally this was supposed to illustrate a concrete example of an API based on our abstract interface.
Now that we have actual implementations, to which we refer in an Appendix of the Implementation draft, maybe we can get rid of the Go sample API. It has become out of sync with the drafts anyway.

**Comment by britram** [comment]
Yep, this was meant to illustrate the API before it was defined. I'll cut it.
