### ISSUE TITLE
Arch: "the ability to easily adopt different transport protocols"?

### ISSUE THREAD

**Issue by theri** [ietf-tapswg/api-drafts#470]
In Section 1.2, Overview, the architecture draft says that TAPS offers "the ability to easily adopt different transport protocols".
What does "adopt" mean here?

I guess this relates to Section 2.3 (maybe say that explicitly here), but even after reading this Section, I don't quite understand why "adopt". Is the point here that a flexible interface makes it easier to add support for new protocols? Then perhaps we should say this here.

**Comment by tfpauly** [comment]
It means that applications don't need to rewrite a ton of code or adopt a new library to access a new transport protocol. In how I read it, "adopt" captures that, but if there's some other text you would like to suggest, that's fine.

**Comment by mirjak** [comment]
For me "adopt" is fine as it should be clear from the rest of the doc. However, if we want to be more clear we could say "make use of different protocols without the need to change the interface" or something...?

**Comment by tfpauly** [comment]
Looks good, merged!
