### ISSUE TITLE
Arch: Consistency of "Transport Services system" and "Transport System"

### ISSUE THREAD

**Issue by theri** [ietf-tapswg/api-drafts#471]
In the architecture document, I noticed that we sometimes say "Transport Services system" and sometimes "Transport System". Are these the same?
Are "Transport Services implementation" and "Transport System implementation" the same, too?

**Comment by tfpauly** [comment]
I prefer "Transport Services system" and "Transport Services implementation"

**Comment by mwelzl** [comment]
I find it long and clumsy  :(
Side note: we'll have to rename it everywhere in the API draft too if we go with this.

**Comment by britram** [comment]
was this fixed by #482?

**Comment by tfpauly** [comment]
Yes it was. We already used Transport Services *most places* so it's not all that different.
