### ISSUE TITLE
Arch: UDP checksums as protocol-specific property?

### ISSUE THREAD

**Issue by theri** [ietf-tapswg/api-drafts#475]
The architecture draft uses UDP checksums as an example of a protocol-specific property in Section 3.2 and 4.1.2.
I find this a bit confusing because in the Interface draft, checksum coverage is a Generic Connection Property (Section 11.1.2).
Should we maybe use a different example of a protocol-specific property, such as the TCP User Timeout we have in the Interface draft?

**Comment by tfpauly** [comment]
Sure, we can switch the example around
