### ISSUE TITLE
Is format of message an implementation detail?

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#477]
In section 7.1 of API it says:

> Message data is transferred as an array of bytes, and the resulting object contains both the byte array and the length of the array.
`messageData := "hello".bytes()
 Connection.Send(messageData)`

For some languages that are dynamic typed (i.e. python) this limits the usability of the API as it adds an unnecessary extra step to each send.
To me this seems like it should be an implementation detail and not specified in the API.

**Comment by tfpauly** [comment]
What are the options other than raw bytes?

**Comment by MaxF12** [comment]
In python you could just pass any type that gets automatically converted inside the API. For example, in our implementation you could just pass a string or integer that gets converted to bytes inside the implementation before sending.

**Comment by britram** [comment]
We generally consider this a case for framers. However, I think it's reasonable to assume that any of the objects used in a TAPS implementation should provide some way for the app to get at the underlying bytes (and therefore, at least implicitly, the length). I don't read this text as prohibiting the use of some object that is `bytes()`able.

**Comment by mwelzl** [comment]
I agree that this is an implementation detail that's irrelevant to the abstract API. Can we close this issue?

**Comment by csperkins** [comment]
Requiring the data be accessible as a byte array is overly restrictive. Can we just remove "Message data is transferred as an array of bytes, and the resulting object contains both the byte array and the length of the array." and the `messageData := "hello".bytes()` call?
