### ISSUE TITLE
Appendix A.1. / Adding preference properties

### ISSUE THREAD

**Issue by theagilepadawan** [ietf-tapswg/api-drafts#486]
A.1. states: 

*"As Selection Properties of type Preference will be added to a TransportProperties object quite frequently, implementations should provide special actions for adding each preference level i.e, TransportProperties.Add(some_property, avoid) is equivalent to TransportProperties.Avoid(some_property)"*

As a TransportProperties object constitutes of Selection, Connection and Message Properties objects, I think it's more natural to make the action of adding a preference part of the API for Selection Properties: 
```TransportProperties.SelectionProperties.Avoid(some_property)```

**Comment by mwelzl** [comment]
It seems that, at least for now, only Selection Properties are of type "Preference". So indeed, this could streamline things a bit.

**Comment by mwelzl** [comment]
On second thought, this strikes me as an unnecessary detail. I don't think we have "TransportProperties.SelectionProperties", "TransportProperties.MessageProperties" etc. defined - we just have the categories represented by the document structure and headings. Of course, we could now go all the way and specify a namespace hierarchy as you describe here, but I don't think this is worth it.

That said, I think what you say does make more sense for implementations; but implementing it as you describe should be okay, as the code examples in the draft are just that - examples.
