### ISSUE TITLE
Fig. 4: fix terminology mismatch with API sec. 12

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#489]
Fig. 4 isn't fully consistent with sec. 12 in the API document.

A few things that stood out to me:
- InitiateWithSend() is missing. I can see that this isn't trying to cover everything, but randomly leaving some things out makes it all a bit confusing IMO...
- "Connection Received" reads as if it should really be the "ConnectionReceived<>" event in the API doc. So I would put these events there and use the "<>" to indicate them.
- Same with "Closed"... this is actually an event, so why not write it as such, with the "<>"?
- RendezvousDone is missing... should we include all events or not? Of course that would then also require adding Sent, Received, ...  maybe it would be better to indicate that events are events, but put a statement somewhere saying that not all events are shown.
- In the same vein, I would replace "Connection Ready" with "Ready<>"
- "Conn. Finished" reads as if it might be an event, but this event doesn't exist... I would just remove this

**Comment by britram** [comment]
I've added InitiateWithSend(), and removed Conn. Finished; you're right, these are confusing.

This diagram does not use the API draft's event notation, and I'm not sure it makes sense to introduce it here -- it would require a bit more expository text only to make a diagram that is an attempt to provide a high-level view provide a... less high-level view. (The expository text now says "... some actions ... have been omitted for brevity and simplicity" and I think that's the right approach.)

**Comment by mwelzl** [comment]
Agreed!
