### ISSUE TITLE
ReceiveHandler per Receive?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#509]
Apple does this: https://developer.apple.com/documentation/network/nwconnection/2998572-receive

...and it may be more convenient than what we currently have (or do we have it unspecified?  **My** interpretation of our text would have been to use only one receive handler associated to the Connection). E.g., if an application expects 3 different types of messages to be received in sequence, it can hand over three different receive handlers in Apple's case, and that seems useful.

Apple also has a "completion" handler per sent event, handed over as a parameter to "send". Is this necessary? Who needs 3 different "Sent" handlers for 3 different messages - shouldn't the "sent" handler rather be a singular per-Connection thing?

**Comment by tfpauly** [comment]
I think this gets into an implementation-specific area. If the language has an easy way to provide a unique completion/closure for a given invocation of Receive(), then I think it is preferable to do this to having a single function.

If anything, it may be nice to make a not for Received() and Sent() that they should, if supported by the language, provide this kind of linking between calls and events.

**Comment by mwelzl** [comment]
I agree, and I assign this to Tommy since he offered (in an email) to write text. Thanks a lot!
