### ISSUE TITLE
Inconsistencies in text realted to selection algorithm and racing

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#517]
The text on the selection algorithm is not fully consistent with the text on racing, as it is written as if the entire tree is available. NOticed this as we moved text to the implementation draft as a result of #429 .

**Comment by britram** [comment]
possibly overtaken by events...

**Comment by abrunstrom** [comment]
Issue was overtaken by events and can be closed with no action.
