### ISSUE TITLE
Architecture NiT: /assumes/

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#518]
I think the word /assumes/ is not a good choice of word in the arch draft.
OLD:
and it assumes an implementation that can use multiple IP addresses,
multiple protocols, multiple paths, and provide multiple application streams
NEW:
and it can provide benefit when an implementation can use multiple IP
addresses, multiple protocols, multiple paths, and provide multiple
application streams.

**Comment by tfpauly** [comment]
Done
