### ISSUE TITLE
Reliable Data Transfer (Message) default - from Kyle Rose's review

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#520]
List discussion:

**Kyle:**
> 7.4.7. Reliable Data Transfer (Message)
> 
> * The default isn't "true", it's whatever the underlying connection had, right?
> 

**@philsbln**:
>  Ack

**@mwelzl**:

> I agree too, but doesn’t this warrant some more discussion?
> I think our defaults all translate into things that can work in some way when TCP is used - with “Reliable Data Transfer” being an exception, as it just can’t work in a UDP-only system. Are there others?  I think I’ll open an issue for this one.
> 

**@gorryfair**:

> I don't agree at all - To me this was just the default behaviour of the API.
> 
> I think the default needs to be "reliable" and an app will have to over-ride that to get datagram/unreliable operation. That doesn't mean if you have only UDP (for instance) that you can't offer TAPS, to me it simply means you always need to say that the app wants this service.

**Comment by mwelzl** [comment]
I agree with the conclusion of @gorryfair above - in which case we should leave things as they are. Other views?

**Comment by abrunstrom** [comment]
I agree that if the application does nothing then communication should be reliable. But I understand Kyle's comment as asking about the relationship to the selection property Reliable Data Transfer (Connection). If you for example set that to Avoid and the TAPS system selects SCTP as the protocol, then if you do not set Reliable Data Transfer (Message) on a message I assume it will be sent as an unreliable message. So in that sense the reliability of a message defaults to whatever is set for the connection, unless it is overridden by setting Reliable Data Transfer (Message).

**Comment by gorryfair** [comment]
So if we agree upon Reliable Data Transfer (Connection), then it would seem less confusing for Reliable Data Transfer (Message) - to use the same logic. Does an apps writer need to know the data will be sent as an unreliable message? 
(I'm not sure I like "avoid reliable data transfer" as a meaningful concatenation of keywords BTW:-).

**Comment by mwelzl** [comment]
Let's see what needs to be done. Suggestion: the only textual change would be to add the following, at the beginning of Section 7.5, just before "The following Message Properties are supported":

"Connection Properties describe the default behavior for all Messages on a Connection. If a Message Property contradicts a Connection Property, it overrides the Connection Property for the specific Message. For example, if "Reliable Data Transfer (Connection)" is set to "Avoid" and a protocol with configurable per-Message reliability is used, setting "Reliable Data Transfer (Message)" to "Prefer" for a particular Message will ensure that this Message is reliably delivered. If the underlying protocol can not support this per-Message behavior, this Message Property choice will yield an error."
