### ISSUE TITLE
Registry for "interface instance or type"  (from Kyle Rose's review)

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#523]
_from Kyle_:
> These type symbols really deserve an actual registry, or at least the start of one. Otherwise, we are likely to end up with a mess.

**Philipp Tiesel**:
> There is already one, but that one was not useful for our matters.

**Comment by squarooticus** [comment]
I'm not sure what Philipp's response means. Where is this registry, and why was it not useful?

**Comment by csperkins** [comment]
Kyle Rose's review: https://mailarchive.ietf.org/arch/msg/taps/o1ehdiAwdqAG42xy2Gy5Cb62eYA/

**Comment by tfpauly** [comment]
This will be system/implementation specific in general, I'd say.

**Comment by tfpauly** [comment]
Add a sentence to 5.2.10 to indicate that this is implementation specific

**Comment by tfpauly** [comment]
Mention that these should be documented?
