### ISSUE TITLE
What constitutes trust verification prior to the handshake?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#524]
Kyle Rose asked this question in his review, referring to section 5.3.2.

**Comment by mirjak** [comment]
Session resumption...?

**Comment by squarooticus** [comment]
I think I was quibbling with the word "proceed". Not sure why I didn't just say that in the review.

> Trust verification callback: Invoked when a Remote Endpoint's trust must be validated before the handshake protocol can proceed.

Credentials are typically exchanged as part of the handshake, which means the handshake has already begun, so I think it will read better if you change "proceed" to "continue".
