### ISSUE TITLE
single messageContext object for both sends and receives

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#525]
from Kyle Rose's review:

> 7.3.3. SendError
> 
> Is there a reason why a single messageContext object is used for both sends and receives? I probably missed the original discussion about this, but I'd like to understand the reasoning.
> 
> (Maybe I should have said "class" instead of "object".) For example, the "lifetime" property makes sense as metadata for sends, but is completely irrelevant to the receiver. The same is true of several other message properties. It might make sense for an implementation to use a single type to represent metadata both for sends and receives, but is that also true for an abstract API?
>

**Comment by mwelzl** [comment]
I agree that implementations would have two different messageContext subtypes for sending and receiving, but I also think that this may be an implementation issue and unnecessary detail for this abstract API. Others?

**Comment by mirjak** [comment]
I you have a request/response protocol this actually gives you additional information by connecting these two messages together.

**Comment by mwelzl** [comment]
Also true. Maybe best to leave it as it is, then, and close this issue?
