### ISSUE TITLE
7.3.1 Sent   (from Kyle Rose's review)

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#526]
Kyle wrote:
> It seems like an abstract API would be helpful for the reference to the Message to which a Sent event applies: this seems like something many, many applications would need to do. With callbacks, the application can always curry in a reference to the original message (that's what my event system from ~2001 did), so maybe that should be the recommendation and the message reference removed...? I don't have a strong feeling here other than that if something is included then its use should be more well-defined.

**Comment by squarooticus** [comment]
Upon re-reading this, I think I'm okay with what's there.
