### ISSUE TITLE
(hopefully) minor point about properties terminology

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#531]
Implementation draft sec 3:
"In the remainder of this document, we only refer to Selection Properties because they are the more typical case and have to be handled by all implementations.

The implementation stores these objects and properties as part of the Preconnection object for use during connection establishment."

I don't understand these two sentences. In the API doc it seems we use the term Transport Properties for both selection and configuration properties. Why do we only talk about selection properties in this doc?

Also in the next sentence what's meant by "objects and properties"? I guess the object(s) that hold the properties? But then this is saying twice the same and we should only use one term to avoid confusion.

**Comment by mirjak** [comment]
Also in the next section 3.1:
"Once an application specifies its Transport Parameters"

I guess that should be Transport Properties instead?

**Comment by mwelzl** [comment]
I agree; I suspect that this is ancient leftover text that should be cleaned up.
