### ISSUE TITLE
Recommendations for Delayed Racing

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#537]
Section 4.2.1  on delayed racing:
"For example, if the first child represents an IP address with a known route, and the second child represents another IP address, the delay between starting the first and second IP addresses can be based on the expected retransmission cadence for the first child's connection (derived from historical round-trip-time). Alternatively, if the first child represents a branch on a Wi-Fi interface, and the second child represents a branch on an LTE interface, the delay should be based on the expected time in which the branch for the first interface would be able to establish a connection, based on link quality and historical round-trip-time."

What the reasoning for these two recommendations? I'm actually not sure what exactly is meant. Is the first case 3xRTT (-> initial RTO) and the second 1xRTT? Why?

Also in the next paragraph:
"Generally, branches between paths and protocols should have longer delays than branches between derived endpoints."

What? Why?

And then 
"The maximum delay should be considered with regards to how long a user is expected to wait for the connection to complete."

How do I know this?

**Comment by mwelzl** [comment]
Also, maybe it's just me, but I can't parse "retransmission cadence", and the phrase with "historical round-trip time" is 1) confusing (I don't get what it means, but maybe that's due to me misunderstanding "cadence"?), and 2) seems to be missing an article.

**Comment by csperkins** [comment]
I read this as examples of things to consider when implementing a happy-eyeballs style algorithm, rather than explicit recommendations. Maybe this fix is to make this more vague, rather than more explicit?

**Comment by abrunstrom** [comment]
I think @csperkins is right and the intention here is that these are just examples of things to consider. We should conclude if anything more is needed beyond making it more clear in the text that these are examples and fixing the other language issues.

**Comment by gorryfair** [comment]
The issue I agreed with was a desire to find simpler terms to describe these examples.

**Comment by tfpauly** [comment]
Refer to Happy Eyeballs for exact timing algorithm as the concrete reference (or ICE, etc).

**Comment by theri** [comment]
It would be helpful to add some of the reasoning behind, e.g., "Generally, branches between paths and protocols should have longer delays than branches between derived endpoints."
