### ISSUE TITLE
Interface for app-driven racing of "unconnected" protocols?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#538]
Impl draft Section 4.5: Handling racing with "unconnected" protocols
"In the case that the application signals that the initial Protocol Stack is failing for some reason and that another option should be attempted, the Connection can be updated to point to the next candidate Protocol Stack. This can be viewed as an application-driven form of Protocol Stack racing."
How does the application indicate that? I don't think this is covered by the API draft?

Also I would recommend to move this section as a subsection within 4.5. (Completing Establishment) or at least switch the order with the previous section (Establishing multiplexed connections) to get a better reading flow.

**Comment by abrunstrom** [comment]
This may affect the API draft so we should conclude if the API draft needs to be updated. We do have the functionality in NEAT for racing with unconnected protocols so i think the text is based on that.

**Comment by tfpauly** [comment]
Change this to text about how a framer can be used to drive racing over UDP. We shouldn't have a special API for marking the current connection failed.

**Comment by tfpauly** [comment]
Action is to propose initial text and follow up at next interim.
