### ISSUE TITLE
Listeners and ports

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#539]
Impl draft section 4.6 (Implementing listeners):
"If no Local Endpoint is specified, the implementation should either use an ephemeral port or generate an error."
Do we need an interface for the application to indicate that an ephemeral port should be used?

**Comment by mwelzl** [comment]
It's implicit in the old socket API - e.g., when I write a client, I only need to provide a server port. I think it's similarly implicit in our current API, right? So ... what's missing?

**Comment by mirjak** [comment]
The text above says "use an ephemeral port or generate an error". So when would you throw an error? If the assumption is that always an ephemeral port should be used (no matter actually how the underlying interfaces works) that should be stated (in the API doc).

**Comment by gorryfair** [comment]
If you do not use an "ephemeral port", and choose to specify the port - then you may get the error if it can't be completed.

**Comment by mwelzl** [comment]
... or if the system is out of resources for some reasons. Just like "accept" can fail in the normal socket API.

**Comment by gorryfair** [comment]
That too.

**Comment by mwelzl** [comment]
@mirjak requested that I adapt the "error" text in the implementation draft too. In doing so, I noticed:

- I don't understand @gorryfair's comment above, about choosing the specify the port. I think this kind of error was possible with sockets somehow, but this text talks about not specifying a Local Endpoint. Technically, I think not specifying a Local Endpoint yet specifying a port is not possible.

- Regarding my own comment, any call may fail for reasons such as the system being out of resources; I think mentioning this in the text here doesn't add any value though.

As a result, I'll remove the part about the error from the text in my update to PR #556.
