### ISSUE TITLE
Batching Sends

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#542]
In the implementation draft section 5.1.3 says that there should be an interface for the application to indicate batch sending. Section 7.7 specifies such an interface. Should the section in the implementation draft be updated or removed?

**Comment by mwelzl** [comment]
I think it should be removed. Mainly, it points out that batching reduces overhead, which is also stated in the API draft in section 7.7.

**Comment by abrunstrom** [comment]
Perhaps it is still important for the implementation to know that it needs to support batching sends though? I would suggest adjusting the text so it reads from the implementations perspective. Something like 

> Since sending a Message may involve a context switch between the application and the transport system, sending patterns that involve multiple small Messages can incur high overhead if each needs to be enqueued separately. To avoid this, the application can indicate a batch of Send actions through the API. When this is used, the implementation should hold off on processing Messages until the batch is complete.

**Comment by mwelzl** [comment]
I agree; this is a nice text proposal. PR #599 replaces the current text with your proposed one.
