### ISSUE TITLE
minIncompleteLength when receiving data on streams

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#543]
Impl draft section 5.2 Receiving Messages:
"if, on the other hand, the top-level protocol only supports a byte-stream and no deframers were supported, the application must specify the minimum number of bytes of Message content it wants to receive (which may be just a single byte) to control the flow of received data."
This text says the application MUST specify minIncompleteLength, however, the API draft says that this values is optional. This should be further clarified and more guidance given in case the value is not set.

**Comment by mwelzl** [comment]
Having looked at this and the API carefully, my suggestion would be to turn the semicolon preceding this statement into a full stop and remove all of this "if, on the other hand, ...." text in the implementation draft.

**Comment by mirjak** [comment]
WFM.
