### ISSUE TITLE
Certificates and other security parameters

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#548]
Can we/do we need to add more guidance in the implementation draft on handling of certificates or other security related parameters?

**Comment by tfpauly** [comment]
We can talk about the endpoint identities that need to be passed to security protocols for validation, etc. Probably talking about handling certificates is just "pass directly to security protocols".

**Comment by tfpauly** [comment]
See #977

**Comment by tfpauly** [comment]
Closing as a dup of 977
