### ISSUE TITLE
Add signal that inbound data was 0-RTT

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#563]
In section 5.3, there's a discussion of how to send data early to use a 0-RTT capability. Should there also be description of a signal that data arrived using 0-RTT? Section 8 of RFC 8446 suggests making this state clear so that applications can guard against replay attacks, etc.

**Comment by mirjak** [comment]
Yes, that could be useful and I guess it would be easy enough to set a flag in the message-context of the received message. I guess we could even re-use the idempotent flag; or maybe a new one is more clear...

**Comment by mwelzl** [comment]
Isn't this exactly the API's "Early Data" Receive Message Property, in Section 8.3.2?
See: https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-early-data

**Comment by mwelzl** [comment]
ping: am I right, and this can be closed?

**Comment by tfpauly** [comment]
Yup!
