### ISSUE TITLE
Namespaces based on IANA protocol numbers registry

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#568]
Just a minute, how can this be a MUST not colide when the registry is still open?:

Namespaces for the keywords provided in the IANA protocol numbers registry (see https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml) are reserved for Protocol Specific Properties an d MUST not be used for vendor or implementation specific properties.

The keyword in this registry is text that has no reserved format, except this registry appears to use upper case. New entries *could* be added to this registry in future, how can the vendor names be orthogonal. I can only see this if we the key - defined as a number 1-255; and vendor numb ears > 255. Or we declare lower case as significant, or some tag?

**Comment by gorryfair** [comment]
Thought linked to #523.

**Comment by squarooticus** [comment]
Assign to me when I have the right permissions on the repo.

**Comment by mwelzl** [comment]
Thanks, someone beat me to it...

**Comment by squarooticus** [comment]
Anyone recall what we actually decided to do here? I'm thinking we want to express that IANA protocol keywords translated to lowercase and removing all characters not in [0-9a-z-] are reserved for the corresponding protocols, but how did we decide to prevent future collisions? Do we require a single parent prefix like "x-" or "p-" followed by a vendor-specific keyword?
