### ISSUE TITLE
5.3 Is  "Fast Open" just one "packet"?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#580]
The opening para reads to me like there is just one first packet. ... or is this actually more than one packets before the handshake complete?

**Comment by tfpauly** [comment]
It is one packet for TCP, but it can be more for QUIC, TLS 1.3 (etc)

**Comment by theri** [comment]
Reference Connection Property "Maximum Message Size Concurrent with Connection Establishment"
