### ISSUE TITLE
Naming of different racing options.

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#588]
Opening this to follow up on a comment by @mwelzl  on #587 that is now closed.

"Simultaneous" and "Staggered" would be better names than "Immediate" and "Delayed". Just from these terms, I would normally think that "Immediate" means to start racing right away, whereas "Delayed" means that nothing would happen for some time. So these two terms are slightly misleading in my opinion.)

**Comment by squarooticus** [comment]
I agree this would be an improvement.
