### ISSUE TITLE
multipath: when and how to open new subflows?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#589]
Sorry we just merged the multipath part into the API doc but I think there is still an issue about this part:

'Active: : The connection will negotiate the use of multiple paths if the chosen transport supports this. It will actively bring up paths based on the multipath policy ({{multipath-policy}}) selected by the application, as limited by the Interface Instance and Provisioning Domain Instance properties (see {{prop-interface}} and {{prop-pvd}}).

Passive: : The connection will support the use of multiple paths if the remote endpoint requests it. The connection will not actively initiate the use of any new paths, but will accept paths initiated by the remote endpoint.'

This mixes two things which should be separated: requesting MP support actively (or just do it if requested by the other end) and opening of new subflows when MP support was negotiated successfully. I thought we wanted to take the later out (opening sub flows) and discuss that separately....?

**Comment by mirjak** [comment]
Just created PR #591 to remove the part about opening new subflows. Do we need to further discuss when/how to open subflows or do we leave this as open for now?

**Comment by britram** [comment]
closed by #591

**Comment by mirjak** [comment]
Agree that interim (June 19) to not address opening of subflows in the API
