### ISSUE TITLE
Allow to query for grouping

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#610]
See the discussion in PR #607. I think this is best dealt with by merging PR #607 after a small fix, then doing a separate PR to address this.

IMO the easiest way to do this is to allow to query a group number (a simple integer). Without grouping, every new Connection simply gets a new number. Having the same group number as any previous Connection(s) indicates group membership. This is how we did it in NEAT too.

If people agree with this, I can take care of this.

**Comment by gorryfair** [comment]
I remember the discussion in NEAT, to me it seems a good way to resolve the issue.

**Comment by mwelzl** [comment]
PR #607 now resolves this differently. It doesn't matter much, IMO the method in this PR also works fine.

**Comment by mwelzl** [comment]
I merged PR #607, which closes this issue.
