### ISSUE TITLE
Allow setting multiple values for some Security Parameters

### ISSUE THREAD

**Issue by theri** [ietf-tapswg/api-drafts#612]
If calling Set() for Security Parameters overrides (#609), then the API should allow setting a Security Parameter to multiple values, e.g., using a list. This would be needed, e.g., to set multiple cipher suites.

I don't think we need to make this overly formal. Adding one sentence to the Security Parameters section should be enough. 
Right?

**Comment by philsbln** [comment]
We should also consider whether setting multiple values is not only needed for Security Properties, but also for Transport Properties like Interface and PvD. This one is more complex, as it comes with a ```(Preference, String)``` tuple.

Not sure whether just adding a sentence and making ```set``` accept a list auf values is the right approach or if we should have an ```add``` call for that – The former is nicer in the API document, the latter seems more appropriate when thinking about how one would use the API

**Comment by theri** [comment]
Agree that we want to enable setting multiple values for Interface and PvD, but I thought that's why their Type is "Set (Preference, Enumeration)" - I took this to mean that it's multiple Interfaces, each with a Preference. But reading the text again, maybe I misunderstood.
If I misunderstood, I think the best approach is to indeed allow specifying multiple (Preference, Enumeration) in a single Set() call.

**Comment by mwelzl** [comment]
Closed by #611

**Comment by theri** [comment]
Reopening this because I still think we should add a sentence to Section 5.3.1 of the API draft, perhaps simply saying that the implementation should support setting multiple values for a single Security Parameter.
Still not sure about the Interface and PvD properties - I think that making set accept a list auf values, as suggested by @philsbln, is the right approach, but perhaps it's worth adding a sentence to explain this to their sections as well.

**Comment by tfpauly** [comment]
Interface and PvD are already "sets of tuples". We could have a sentence to clarify that this is a "collection", or maybe just call it "collection". Maybe also add a sentence to the data types section to indicate that they can have collections. Mention in text that security parameters can take collections.
