### ISSUE TITLE
Streams/Connections Relationship is unclear

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#618]
I found the relationship between streams and connections to be extremely murky throughout the draft, and left it not really sure how I would control a streamed transport.

Section 6.4 hints suggests that opening additional streams is an alternative implementation of Clone() for transports that can do so. Does this imply that if the peer stream limit does not allow new streams, the transport should open a connection instead? How does SetNewConnectionLimit() in Sec 6.2 relate to streamed transport -- are there two levels of listener: a stream listener and a connection listener? How would opening "stream listeners" relate to the maximum number of streams the peer could open (i.e. do I have to call listen() 8 times to allow the client to open 8 streams)? Or are there no stream listeners and these "connections" just sort of appear?

Skimming the -impl draft, I can see there's some text here but it is not fitting together for me. There are at least three streamed transports and it would be helpful to explain how the API conceptualizes this, perhaps in a new section.

**Comment by tfpauly** [comment]
To clarify, Listen() is called once and keeps receiving streams within the NewConnectionLimit.

The main thing to clarify is how the NewConnectionLimit applies to streams of a multiplexed transport.

We could look at having a limit of connections per endpoint in a group from a listener.

**Comment by tfpauly** [comment]
Add a property to section 7.1.

**Comment by tfpauly** [comment]
Also make sure to have an early section being very explicit about the overall interaction model.

**Comment by tfpauly** [comment]
In section 4.1, we could add an example for explicit group management via clone, etc.

**Comment by mwelzl** [comment]
Sigh, I will never self-assign an issue again *before* its discussion  :-)   but it's ok... I'll do it
