### ISSUE TITLE
API for enum values?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#621]
sec 4.2.2
"implementations MUST provide a
      method for the application to determine the entire set of possible
      values for each property."

Is this meant to be a requirement for a machine-readable API for learning the enum, or merely a requirement for documentation? i.e. is it satisfied if the values are in the man page or comments of the C header file?

**Comment by gorryfair** [comment]
As a by-note, isn't this a great place to use "REQUIRED" and say whether it is required to specify or required to support :-).

**Comment by tfpauly** [comment]
Proposal: Just remove "however, implementations MUST provide a method for the application to determine the entire set of possible values for each property."

This is too implementation- and language- specific.
