### ISSUE TITLE
Clarify Use of Application Congestion Control

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#625]
sec 5.2.9
It would be helpful to say "Applications that neither prohibit nor require congestion should query the result and disable their own congestion control if present in the transport"

**Comment by gorryfair** [comment]
Interesting, but we need to be careful in what we say. It seems safe, but not performant to do CC at multiple layers, and if it's done at a lower layer performance might be improved by not replicating the function at a higher layer...

**Comment by tfpauly** [comment]
Link to UDP guidelines document.

Just mention that there are performance implications of multiple CC loops; don't just say "disable CC".
