### ISSUE TITLE
Problems with temporary local addresses

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#626]
sec 5.2.12
Using temporary local addresses may break various mechanisms that prove address ownership (e.g QUIC resumption tokens) and therefore impair performance as the client has to re-verify its address.

**Comment by tfpauly** [comment]
The default is to use a temporary address for client local address; and to not use it for a server local address. This is the same as most socket APIs. What are you suggesting in the text, @martinduke?

**Comment by martinduke** [comment]
right, a QUIC resumption token will generally contain the client's IP address so that future connections no longer have to go through Retry and anti-amplification mechanisms, which reduce throughput.

so IIUC 5.2.12 could say something like "Clients that use temporary local addresses might invalidate server-provided tokens that validate the client's IP addresses (e.g. Sec 8.1.3 of quic-transport), increasing latency."

**Comment by tfpauly** [comment]
Add a one-sentence warning that using a temporary address has a potential performance impact on resumption.

**Comment by gorryfair** [comment]
Do we wish to refer to RFC 7721?
