### ISSUE TITLE
Does stop() add value to the API?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#627]
sec 6.2 
"After Stop() is called, the Listener can be disposed of." I don't understand the difference between calling listener.stop() and simply disposing of the object. Does this imply that there is a listener.start() that allows a configured listener to resume?

**Comment by tfpauly** [comment]
We should just not talk about "disposing" here. Just remove the sentence.

**Comment by squarooticus** [comment]
Object disposal implies a language with synchronous destruction, something we can't assume. For something garbage collected, you'd need an explicit close method because you don't know when the object will be destroyed.
