### ISSUE TITLE
Clarify idle timeout, specify keep alive enablement

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#628]
sec 7.1.4
It would be helpful to clarify the relevance of control vs application data in the idle timeout -- for various reasons, the connection could stay alive regardless of how active the connection is (in fact, perhaps "keepalive" is a generally useful notion that can be exposed in the API?)

**Comment by tfpauly** [comment]
The timeout in 7.1.4 should include control data (like ACKs, etc). This should be clarified: "data" in this context is any transport data, not just application data.

We can have a simple boolean to enable keepalives as well.

**Comment by mwelzl** [comment]
Aha, this should have been closed by PR #643, but "responds to issue #628" wasn't auto-detected by git. Manually closing now.
