### ISSUE TITLE
Event for PMTU changes

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#630]
sec 7.1.9.
We're going to need an event for MTU changes. These can't simply be Send errors because the Sent event might go first, or the transport might be sending a probe with padding that doesn't correspond to a message.

**Comment by gorryfair** [comment]
So does this mean MTU of the interface or PMTU of the path?
- It seems simple to add an event for interface MTU changes.
-  For the PMTU, this raises a few questions before we add:
(i) I can see the motivation for an event for a decrease in PMTU, and that seems relatively easy to add ... and could also return the new upper limit
(ii) Would the same also be true of an increase in the PMTU? If so, it could be helpful if the upper layer probably says how "large" it is interested in using - e.g., DPLPMTUD has the notion of MAX_PLPMTU as an upper bound on probing.

**Comment by martinduke** [comment]
PMTU of the path. I don't have a strong opinion on increases, but I would probably have an event for increases and not bother with the maximum. An unnecessary increase notification seems less expensive than another bit of API to specify the max.

**Comment by tfpauly** [comment]
Just add a path changed event to the application (similar to the one in implementation).

**Comment by tfpauly** [comment]
Add event to Section 7.3?

**Comment by gorryfair** [comment]
Just to be sure: This is a Path Changed Event, not a specific event relating to PMTU size.

**Comment by gorryfair** [comment]
New text looked good, I think this issue has been resolved.

**Comment by mwelzl** [comment]
#648 closed this.
