### ISSUE TITLE
Sent<> event after ack

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#632]
sec 8.3.2.1
Reading the Sent event, I was pretty sure that reliable transports would deliver the event until the ack arrived. But Sec 10 most definitely does not say that. I would think that the ack would be a more useful signal, but maybe I'm in the rough on this -- certainly many transport implementations will not do this well.

**Comment by tfpauly** [comment]
We generally don't think that having the signal be based on getting an ack is the right thing to do. This won't always be possible, for one, and it isn't clear what to do.

The signal for the send completing is that the data is *sent*, which means that there was room in the window. If data can't be sent, this provides backpressure. Backpressure should operate at the layer of the transport's window more than the acking details.

**Comment by martinduke** [comment]
Makes sense, I'll close this issue.
