### ISSUE TITLE
Figure Legends in API

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#635]
We should update the figure/table legends:

add: Table 1: /Selection Properties Preferences/

In Section 8.1.2.,

add: /Figure 1: Protocol Stack showing a Message Framer/

In Section 10,

/Figure 1/Figure 2/

**Comment by tfpauly** [comment]
I think this is for API, not Architecture. These sections are references to API, as far as I can tell.

**Comment by mwelzl** [comment]
I'm not a native speaker, so I probably shouldn't even be making this suggestion ....  but: isn't the use of plural slighly odd in the first item ?

in the PR, I have now proposed "Selection Property Preference Levels" instead of "Selection Properties Preference Levels".
