### ISSUE TITLE
Rendezvous() example in §4.1.3 is simplistic

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/api-drafts#636]
The peer example showing how to use `Rendezvous()` in §4.1.3 is overly simplistic. It's likely worth showing the interactions with STUN, etc.

**Comment by squarooticus** [comment]
Agreed. The example gives the reader no real indication of what the call to Rendezvous() does.

I'm also not sure I would reference TCP simultaneous open in §6.3. Given its dependence on time synchronization between peers, does anything actually use it, and is there any utility to it vs. one side listening and the other connecting, with the listener rejecting anything with the wrong getpeername()? STUN OTOH would be a great example of how TAPS could greatly simplify something that requires multiple explicit connections with BSD sockets for setup.
