### ISSUE TITLE
Address family and port abstraction

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#656]
In the past, when I've designed transport abstraction APIs, I've always kept address family abstract, just as BSD sockets do. In this case, you've got WithIPv4Address and With IPv6Address as separate methods on the Endpoint type instead of just a single WithAddress method that takes an object of a type appropriate to the address family.

Similarly, you've got WithPort as a first-class method instead of making it part of the Endpoint, as BSD sockets does with sockaddr_in. What if you want to support both TCP and QUIC, but the QUIC endpoint is on a different port? The notion of "port" is similar between the two, making the use of the same name appropriate, but it is only by convention that they often match: they are completely different spaces implemented in entirely separate codepaths in every network stack. ICMP doesn't even have a port: what if you wanted to use that (or some other port-less protocol that, for instance, multiplexes via IPv6 host ID) with this interface.

**Comment by mwelzl** [comment]
See #571 - this should in principle be covered by the PR answering #571. We think it should be made clear that EndPoints are abstract entities and can have more than just ports, addresses, ... etc.

**Comment by squarooticus** [comment]
Ok, we can either move this point over to #571 and close this, or leave it open as a placeholder once that one has been resolved to see if everything is covered. Your choice.

**Comment by mwelzl** [comment]
Moved; closing.
