### ISSUE TITLE
To abstract or not to abstract? That is the question

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#658]
Selection property querying is better than it was, but querying still feels odd:

* Using "has been applied" to mean "on" or "in use" or "active" necessitates a bunch of explanatory text in §5.2 that would otherwise be unnecessary.

* Reporting "true" for properties that are "on" or "in use" or "active" is very UNIX-y, but less abstract than I'd like to see here. At least we're not encoding -1 as a special return value anymore. A perhaps suitably abstract interface here would be something like:

```
tp := Connection.GetTransportProperties()
if tp.has('reliability'): ...
```

**Comment by mwelzl** [comment]
Welcome, author!

**Comment by squarooticus** [comment]
Ugh. Can I insert a GIF of a pile of books falling on me?

**Comment by tfpauly** [comment]
Also, make SecurityParameters more abstract (don't do "strings" that look like Python).

**Comment by squarooticus** [comment]
> Also, make SecurityParameters more abstract (don't do "strings" that look like Python).

I made a change in the third commit of #658. LMK if that matches your expectations.

**Comment by squarooticus** [comment]
Er, I mean #687. @tfpauly
