### ISSUE TITLE
SecurityParameters probably needs a rework

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#662]
The SecurityParameters section seems to be describing an abstract API that assumes the underlying security protocol is TLS. I have a few questions that might motivate a rework:

* What if I want to race TLS/TCP against QUIC, and have different credentials for each
* What if I want to race two TLS connections against each other, and have different credentials for each?
* What if I have multiple supported groups?
* What if my security protocol authenticates peer identities some way other than challenge/response?
* How does this API relate to the work done in draft-ietf-taps-transport-security? There's a nice section in appendix B describing the relation to minset, but no equivalent for this.

I'm not sure if something completely generic is possible here. It might be that the interface to the underlying security protocol might need to be specific to the state machine for the protocol itself. You could potentially do something like:

```
ep1_tls := TLS_Parameters(private_key=priv1, cert_chain=pub1, ca_list=public_ca_list, ...)
SecurityParameters.Register(RemoteEP1, ep1_tls)
ep2_tls := TLS_Parameters(priv_op_cb=curry(sign_with_hsm, hsm_handle1), cert_chain=pub2, \
    auth_peer_cb=curry(verify_with_hsm, hsm_handle1), ...)
SecurityParameters.Register(RemoteEP2, ep2_tls)
```

**Comment by squarooticus** [comment]
FTR:

I have come completely 180° on this after a discussion about the security implications of "racing" security parameters in the interim. This should be resolved in favor of specifying a single set of security parameters which then constrain the rest of protocol and path selection.

**Comment by tfpauly** [comment]
As discussed in interim, we should keep things with a single identity, etc. ALPN is an exception, but the current semantics don't prevent having ALPN that is conditional to transports.

We may want to mention the identity issues or refer back to the architecture security considerations in the API security considerations.

**Comment by squarooticus** [comment]
We decided that if an application wants to race protocols using different trust anchors or identities, the application needs to explicitly support that through some assertion that all identities are equivalent, e.g., by packaging them in a container that TAPS considers to be a single identity for its purposes.
