### ISSUE TITLE
Message framers form a pipeline

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#664]
In §8.1.2 ¶3, the doc says:

> the Message Framer can intercept all calls to Send() or Receive() on a Connection to add Message semantics

but this doesn't seem to be conceptually compatible with the text at the top of §8.1.2.1, which says:

> Multiple Framers may be added.

I think the way most developers would think about this is as a pipeline: you feed data into the top-level framer with Send, which then percolates downward through the pipeline to the bottom-level framer, which then sends it to the transport.

**Comment by mwelzl** [comment]
I think this should be easy to address, by rephrasing:
`Multiple Framers may be added.`
as:
`Multiple Framers may be added. In this case, Framers that are added in addition to already existing Framers call each other.`

... BUT "call each other" is surely a terrible way to put this, and there must be a way to say this cleanly and neatly, in line with how the code really goes. THIS, I suspect, is a very simple thing for @tfpauly to do, and hence I assigned it to him.
