### ISSUE TITLE
Message properties

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#666]
Shouldn't the default value for every message property basically be "inherit", i.e., from the connection?

§8.1.3.3:

> If true, it specifies that the receiver-side transport protocol stack only delivers the Message to the receiving application after any existing previous ordered Message that was passed to the same Connection via the Send Action.

This is a bit awkwardly worded. If this is supported for both reliable and unreliable transports (unclear?), then:

* For reliable transports, this means that this message will not be delivered to the application until all previous ordered messages on the connection are delivered.
* For unreliable transports, this means that any message prior to this one in ordering but received subsequently will not be delivered to the application.

**Comment by mwelzl** [comment]
Multiple things here. Default: interesting idea, I tend to say "yes".

About §8.1.3.3:
This is meant to support both reliable and unreliable transports - why this unclear (why wouldn't it support both)?
IIRC this was me, borrowing the wording from SCTP which also covers both of these cases (reliable and unreliable). I like your description (at least the one for reliable transports), but I think it's good to be explicit about the relationship to the Send Action. How about this, maybe simpler to read and still generic:

`The order in which Messages were submitted for transmission via the Send Action will be preserved for all Messages on a Connection that have this Message Property set to true.`

**Comment by squarooticus** [comment]
...will be preserved on delivery via Receive<> events for all Messages... ?

**Comment by mwelzl** [comment]
We got us a deal!  :-)   Seriously, this is better and clearer, thanks!  Will fix

**Comment by mwelzl** [comment]
Seeing the number of this issue, it's clear to me that you chose the wrong issue when you wrote "For the love of Satan".

**Comment by mwelzl** [comment]
Just a note regarding #680: you said that the default for every message property should basically be "inherit"; checking them carefully one by one showed me that this is only a reasonable decision for three of them: Ordered, Reliable Data Transfer (Message) and Message Capacity Profile Override.

E.g., a default of using less than a full checksum doesn't and probably shouldn't exist anywhere. Any default other than "False" for "Final" (last Message of the connection) really doesn't make a lot of sense (only the application would know that it has only one Message to send).  ... and so forth.

**Comment by squarooticus** [comment]
You are technically correct, which is the best kind of correct. I basically meant that message properties that are used to override the same property at the connection level should default to "inherit".
