### ISSUE TITLE
Fragmentation

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#667]
I'm not 100% sure, but I believe the DF bit applies only to intermediate hops, not to the originating machine. E.g., if you have DONTFRAG set on your socket (or at the system level via pmtud) and shove 60K into a sendto() call, the kernel will still happily chop your datagram into multiple <=1500 octet packets. So, the text in §8.1.3.9 is probably misleading.

**Comment by mwelzl** [comment]
I'm not sure if this makes the text misleading? The text only says that "a message should be sent and received as a single packet without network-layer fragmentation, if possible."
It may not be possible...  there's also this sentence: "When used with transports supporting this functionality and running over IP version 4, the Don't Fragment bit will be set."   - consider the first half of the sentence: the functionality is constrained to being offered only over transports that provide this precise functionality.

**Comment by squarooticus** [comment]
I think the text is literally correct, but misleading in that it implies a level of actionability that doesn't appear to be in evidence. Unless you have a means to know path MTU, you can't adjust your message length to avoid fragmentation or drop, so what good does this do other than result in drops vs. path fragmentation in IPv4? This will have zero effect on IPv6, for instance.

**Comment by gorryfair** [comment]
I'm confused about the confusion. What is being asked?

**Comment by squarooticus** [comment]
I think I'm asking for an example of where this property would make a difference to the wire image, other than in the DF-set case on IPv4 where intermediate hops will drop rather than fragment.

**Comment by mwelzl** [comment]
I think that this is really mainly about DF / IPv4.

But, if you think of a protocol like SCTP which stuffs messages into packets, this protocol could theoretically decide that message X should not be placed such that the first half of it goes into packet 1 and the next half into packet 2, but that packet 1 should just be shorter and the whole message X should go into packet 2 instead. This is transport-layer fragmentation, not network-layer fragmentation, though.

Perhaps "network-layer" should be removed from the text? This should be safe to do as long as we don't make any promises.

**Comment by gorryfair** [comment]
I don't think we should conflate transport segmentation of data with network-layer fragmentation. These have different purposes. A source host still has the choice to fragment at the network-layer to the PMTU, by the way, even when DF is set - as in IPv6.

Protocols like STUN might use this to control which packets are sent with fragmentation at the sender to the PMTU, and which carry control packets to probe for a larger PMTU.

**Comment by mwelzl** [comment]
Sure the host can at the network layer anyway; we're not giving any guarantees against that. Fine not to conflate - but then the semantics of the text in §8.1.3.9 really only translates into: "in case of IPv4, DF=1". I think this is fine - it seems Kyle wants more, but why? Or should the text more bluntly say "IPv4 DF=1" perhaps?

**Comment by squarooticus** [comment]
Michael, that's basically what I'm arguing. The only lever TAPS has is over intermediate hop behavior on IPv4, reducing the whole property to "sets DF=1 on IPv4".

I also agree with Gorry re: segmentation vs. fragmentation. Do we need text re: segmentation for protocols like SCTP and QUIC?

**Comment by mwelzl** [comment]
The minset part for the transport layer thing is called "request not to bundle messages"; the minset appendix currently identifies that the "No Fragmentation" message property conflates this with network layer fragmentation. I suggest that I'll fix this, by:

1. changing the "No Fragmentation" text a little bit, just to more bluntly state that this is really only about IPv4 DF
2. adding a Message Property that has just the transport-layer "request not to bundle messages" semantics.

That should do the trick, I believe.
