### ISSUE TITLE
Reply mapping to connection

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#668]
§8.2.2 says:

> By using the replyMessageContext, the transport system is informed that the message to be sent is a response and can map the response to the same underlying transport connection or the stream from which the request was received.

But it appears the Connection object is still required to call Send, so what value does this provide? I.e., how are you supposed to use replyMessageContext from the example?

**Comment by mwelzl** [comment]
I agree - it seems to me now that this really adds no value. What am I missing?  I'm assigning @philsbln because he was among the first to propose this... maybe he can explain

**Comment by mwelzl** [comment]
Ping  :)

**Comment by tfpauly** [comment]
Interim: We will remove all "reply/replies" from the API doc.
