### ISSUE TITLE
Preconnection needs to support multiple Local and Remote Endpoints

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/api-drafts#675]
The `Preconnection.Rendezvous()` call needs multiple local and remote candidate endpoints. 

This means `NewPreconnection()` should take lists of `LocalEndpoint` and `RemoteEndpoint` objects (section 5) and there should be ways of adding/removing `LocalEndpoint` and `RemoteEndpoint` objects from a `Preconnection`

Relates to #571

**Comment by squarooticus** [comment]
Pairs of? Local and remote endpoints probably need to be linked.

**Comment by csperkins** [comment]
#697 updates the description of `Endpoint` to say:
>   An Endpoint cannot have multiple identifiers of a same type set.
>   That is, an endpoint cannot have two IP addresses specified.  Two
>   separate IP addresses are represented as two Endpoint Objects

That's fine, but it prevents a single `Preconnection` being used in `Rendezvous()` when there are multiple remote candidates. For `Rendezvous()` to work, we need to relax this restriction and allow multiple addresses of the same type to be added to an endpoint. 

@tfpauly what's the rationale for the change in #697 ?

**Comment by philsbln** [comment]
I remember having multiple addresses on an endpoint would also benefit multicast.

**Comment by tfpauly** [comment]
@philsbln the explanation for how multicast is handled didn't change at all here, btw.

**Comment by tfpauly** [comment]
@csperkins I think it would make most sense to either:
- Use the alias approach, where one endpoint can have a list of aliases that are equivalent options, or
- Let the preconnection have multiple endpoint objects for rendezvous

The definition of a single endpoint object is a lot easier to keep track of and understand if it is a single address or equivalent identifier.
