### ISSUE TITLE
Behavior of Framers in Connection Groups

### ISSUE THREAD

**Issue by MaxF12** [ietf-tapswg/api-drafts#681]
How do framers behave in connection groups? I.e. do all connections share one framer object or does the framer object get duplicated when a connection gets cloned? If it does get duplicated, does it keep its current state? 

This might mostly be an implementation detail but I think it should be mentioned in section 6.4 of API.

**Comment by mwelzl** [comment]
Interim: same type of framer is plausible default (but new instances), but in general a framer should be per connection. State is not shared across connections.

Bigger problem: framers are added to preconnections, not connections, so how is this done with cloning?
(perhaps: add list of framers as parameter added to the clone call)

**Comment by britram** [comment]
I've thought about it, and Idon't think we actually have a bigger problem here:

On an initiated Connection/ConnectionGroup, the provenance of the Framers is Preconnection.AddFramer() -> Preconnection.Initiate().

On a Listener, the provenance of the Framers is Preconnection.AddFramer() -> Preconnection.Listen() -> Listener.Clone().

In a Rendezvous situation, there is (unless I'm missing something) always a Preconnection from which a Framer can ultimately be inherited.
