### ISSUE TITLE
Framer Dynamics

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#684]
Per discussion at the interim on 2 October:

We might want to split the framer stack (currently implicit in the Preconnection) into an explicit object in the interface, in order to support framer dynamicism.

Concretely:

- add a FramerStack object, and have AddFramer be a call on that. (Optionally, a new Preconnection comes with an empty FramerStack, and Preconnection.AddFramer just passes through to its internal FramerStack.)
- Initiate, Listen, and Clone optionally take a FramerStack object that *replaces* the existing FramerStack.
- Connection gains a ReplaceFramerStack call, which *replaces* the existing FramerStack as soon as the send buffer is empty, pushing back any unconsumed received bytes/objects and re-deframing them 

I'm not convinced this will work, but csperkins@ had some good arguments about why this would be useful for WebRTC like things.

@tfpauly (and everyone else, of course): wdyt?

**Comment by MaxF12** [comment]
I agree that it is a good idea to have different FramerStacks for different Connections coming from the same Preconnection (so through listen and clone).
Having one framer that can determine what kind of connection is underlying and then switches its behavior accordingly seems to go against the concept of framers being very compartmentalized  so developers can just grab them off the shelf and pluck them in. 

I am not sure that you need to be able to hand over a FramerStack on initiate or change them out on active connections.

**Comment by britram** [comment]
from the interim: ReplaceFramerStack is a box of dragons (hello, concurrency) so we probably shouldn't do it in the general case.

**Comment by britram** [comment]
and we don't need the rest of this in the general case, so closing.
