### ISSUE TITLE
Remove the term "TAPS" from drafts

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#690]
TAPS -> Transport Services

**Comment by mwelzl** [comment]
I realize that this is a silly discussion to have, and I just don't care... but I *am* curious: why?

**Comment by tfpauly** [comment]
Well, mainly because we say "Transport Services" throughout and the term "TAPS" isn't defined. But also because I don't and never have understood how "TAPS" is an abbreviation of "Transport Services". If we want to abbreviate it, let's just use "TS".

**Comment by mwelzl** [comment]
Hey, I needed a 4-letter acronym for a working group, that was all, and I didn't want to have a discussion about something that I considered so unimportant.... also, taps signals the end of the day, when everyone is to go to sleep:
http://usscouts.org/mb/taps.asp

So yeah... as you can see, I really don't care, I was just curious. Let's just use "transport services" throughout. And next time I form a WG I'll really think hard to make a good acronym.  :-)

**Comment by gorryfair** [comment]
+1 to "transport services" everywhere.
(actually i liked the name of the WG Michael!)

**Comment by JohnGrantNineTiles** [comment]
I'd always assumed the AP was from API.
