### ISSUE TITLE
Network Policies

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#701]
In Sec 2:

Should Section 3.2 also talk about network policies, e.g. a certain network supports a DSCP that the application desires?

**Comment by britram** [comment]
As discussed in Feb 2021 interim, this seems like a rabbithole. Gorry will figure out whether it is and write language if not, or close if so.

**Comment by gorryfair** [comment]
I'd like to add a couple of lines of text here to bullet 2 that discusses how you might learn that an attached network supports certain features - e.g. through a PvD, routing advertisement, or local discovery method, and suggest that this could enable a system to know which paths have specific characteristics.

**Comment by gorryfair** [comment]
I propose this as a starter:

When additional information (such as Provisioning Domain (PvD) information {{RFC7556}}) is provided about the networks over which an endpoint can operate, this can inform the selection between alternate network paths. Such information includes network segment PMTU, set of supported DSCPs, expected usage, cost, etc. The usage of this information by the Transport Services API is generally independent of the specific mechanism/protocol that was used to receive the information (e.g. zero-conf, DHCP, or IPv6 RA).

Thoughts... ?

**Comment by gorryfair** [comment]
Tried to create a PR to add some policy to the path selection #836
