### ISSUE TITLE
What is a "confirmed" route?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#703]
In Sec 4.5 of taps-impl:

"An implementation should consider such a protocol stack to be established as soon as a local route to the peer endpoint is confirmed."

What does this mean for an unconnected protocol? That there is an entry in the route table, or that it's received a packet?

**Comment by gorryfair** [comment]
Good catch: This appears to be rough sentence. The term "confirmed" occurs only once, and a "local route" is something quite different to what is intended!

We do talk about establishing connectivity with a remote endpoint... maybe that might work?
