### ISSUE TITLE
Define multipath terms

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#704]
Before distinguishing between protocols that do "multipath" and "migrating between paths", it might help to define these terms. This is tripping is up in QUIC, and IIRC the original "Multipath TCP" was pretty much the migration case.

Something like, "In this section we distinguish between 'multipath' protocols and protocols that allow migration between paths. The first means <blah blah>..."

**Comment by martinduke** [comment]
This is in section 7.2 of taps-impl.

**Comment by britram** [comment]
We define multipath (by policy in section 6.1.7 handover, interactive, aggregate) in the API doc. Section 4.2 in Implementation should use these definitions.

**Comment by mwelzl** [comment]
I wanted to fix this now, but stumbled over the following sentence in the implementation draft:

> If the Protocol Stack includes a transport protocol that also supports multipath connectivity with migration support, the Transport Services implementation should also inform the Protocol Instance of potentially new paths that become permissible based on the Selection Properties passed by the application.

This talks about the protocol below the transport services system; do multipath-supporting protocols with *no* migration support exist? I struggle to imagine a scheduler that wouldn't make this happen... e.g. lowest latency scheduling, but with the exception: if a path becomes completely unavailable, keep going?  :-)

Looking at the three policies in section 6.1.7 of our API, clearly, migration should work with all of them (and "Handover" is limited in that it doesn't do anything else, but it's gotta be a subset of the others anyway, I'd say).

Am I missing something?  Just checking...

**Comment by abrunstrom** [comment]
I think the example of no migration support would be a multipath protocol that is not able to add new paths, so SCTP without support for the ADD_ADDR extension perhaps? Not sure this is a case we need to worry about though...

**Comment by mwelzl** [comment]
Ah, a multipath protocol that doesn't do multipath  :-)

**Comment by abrunstrom** [comment]
Well, it can do multipath with the paths you give it from the beginning :) 
Possibly something else was intended with the text from the beginning, but this is what I could think of...
