### ISSUE TITLE
Flushing protocol state is not in the interface

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#706]
Section 9.1 of taps-impl loosely refers to the need for an interface to "flush protocol state" to preserve anonymity, but such a capability is not in taps-interface.

**Comment by gorryfair** [comment]
I don't like this text: 
"Applications must have a way to flush protocol cache state if desired. This may be necessary, for example, if application-layer identifiers rotate and clients wish to avoid linkability via trackable TLS tickets or TFO cookies."

Those of you who know me, would immediately see a "MUST"..."if desired."  and a "may be necessary". My suggestion is that this digs too deep, and we should remove the text. I could also live with something more neutral though:

Note: There are case where applications need to flush protocol cache state, for example, if application-layer identifiers rotate and a client wishes to avoid linkability of trackable TLS tickets or TFO cookies.

**Comment by mirjak** [comment]
I'm fine to have the more neutral sentence proposed by Gorry. I don't think we should specify an interface for it but I think it's good to mention.

**Comment by abrunstrom** [comment]
I agree that the best approach is to make it more neutral. The other option would be to say that this interface is implementation specific. For sure, we do not want it in the API I think.

**Comment by martinduke** [comment]
I have no opinion on Gorry's comment, but I'm a bit mystified by the "shouldn't be in the API doc" argument. Perhaps I'm not understanding the purpose of taps-interface? I thought it was a qualitative description of the controls offered to the application, which this clearly would be!

**Comment by mirjak** [comment]
I would define taps as an interface to control network connections. So flushing state is a good thing in some scenarios for privacy but not really needed to handle network connections.

**Comment by britram** [comment]
See also #721 -- this surfaced that we have drifted on connection group versus context, which we need to fix in arch.

**Comment by britram** [comment]
Martin to write a PR against API to propose a context API that would provide the intent of this functionality.

Alternative is to NOP this in the API doc ("connection contexts are too implementation specific to expose in a general way" or similar)

**Comment by britram** [comment]
A second alternative is a one-bit fix: a selection property that requires a given connection to be in a separate connection context (which implies a separate connection group) from other connections created in the preconnection.
