### ISSUE TITLE
Issues with TCP-specific considerations (taps-impl 10.1)

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#707]
- I don't think you mean that TAPS should throw a ConnectionError on a TCP Retransmission Timeout!

- I'm somewhat concerned about half-close, though this might just be editorial. An HTTP/3 implementation needs to send FIN when it's done requesting, for instance (I realize that HTTP/3 is not TCP, but I imagine the semantics are the same). So I think it would send its request with a end-of-message, According to the "Send" description, TAPS will send CLOSE.TCP automatically after the FIN.

A regular "Close" will trigger a "Closed" event which tells the application it isn't getting more data, so I _guess_ this just barely works if TAPS sends CLOSE.TCP but not Closed, and waits for the Close command from the app? Like I said, I'm not sure this is wrong, but it's not clearly stated how an app that needs half-close functionality should implement that.

**Comment by gorryfair** [comment]
I really really don't think that TAPS should cause any Error on a TCP Retransmission Timeout!
- This happens for many reasons, and isn't an upper-layer issue.

**Comment by mwelzl** [comment]
Regarding the half-closed scenario, I think you're onto something there. Let's see how this would work, for a client sending a message followed by a FIN, and the server answering:
(Note: all "close" calls "from above" have complete "all is over" semantics, to be able to also work with protocols which do *not* support half-closed connections (such as SCTP).)

Client:
Send, Message marked as Final. According to the implementation draft, this causes CLOSE.TCP, which will transmit the FIN to the server. As you suggest, the CLOSE.TCP would not invoke Closed, and instead wait for the Close command from the app - this makes sense and would work like that, but indeed it's not stated anywhere, so this text should be added.

Server:
If this is a native TCP server, there's no problem.
If this is a TAPS server, then there's no way for the server to know that it should not issue a Closed upon the FIN coming after the Message. After Closed, the application cannot write anymore. Game over.

How do we handle the server case? E.g., we could add yet another selection property: "Allow writing after Closed". Not exactly beautiful ... but is there any other way to do it?

**Comment by tfpauly** [comment]
Section 7:

Whether the connection can be used to receive data. A connection cannot be used for reading if the connection was created with the Selection Property Direction of Communication set to unidirectional send or if a Message marked as Final was received, see Section 8.3.3.3. The latter is only supported by certain transport protocols, e.g., by TCP as half-closed connection.

**Comment by tfpauly** [comment]
Also: 

8.3.3.3. Receiving Final Messages
The Message Context can indicate whether or not this Message is the Final Message on a Connection. For any Message that is marked as Final, the application can assume that there will be no more Messages received on the Connection once the Message has been completely delivered. This corresponds to the Final property that may be marked on a sent Message, see Section 8.1.3.5.

**Comment by britram** [comment]
technically solved in API ("the best kind of solved") by existing text in 8.3.3.3, section 10.1 still needs work in impl.

**Comment by mwelzl** [comment]
I write this here so people don't miss it:
There is this statement in the API doc, describing the Close call, which my PR for this issue will remove: "If the Remote Endpoint still has data to send, it cannot be received after this call."

We can allow reading until Closed fires. For protocols such as SCTP that do not support half-closed connections, Closed would have to fire immediately upon calling Close.
