### ISSUE TITLE
SCTP Connection Objects description is unclear

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#708]
Sec 10.6 of taps-impl is pretty confusing:

> 
Connection objects represent a flow of SCTP messages between a client and a server, which may be an SCTP association or a stream in a SCTP association. How to map Connection objects to streams is described in [NEAT-flow-mapping]; in the following, a similar method is described. To map Connection objects to SCTP streams without head-of-line blocking on the sender side, both the sending and receiving SCTP implementation must support message interleaving [RFC8260]. Both SCTP implementations must also support stream reconfiguration. Finally, both communicating endpoints must be aware of this intended multiplexing.

..

there's yet more.

Maybe I should read NEAT-flow-mapping, or remind myself about the details of SCTP, but I think the third sentence (To map Connection Objects...) is not well-constructed.

There are three conditions here: both SCTPs must:

- support 8260,

- support stream reconfiguration, AND

- know what's going on.

But what do these conditions enable?

Is it mapping connections to streams at all?

Is it mapping them without HOL blocking (i.e., if not met, I still can map but there is HOL blocking)?

Something else?

**Comment by mwelzl** [comment]
Guilty as charged!  I wrote this and I can fix it.
Meanwhile, I'll explain:
8260 => to reduce HOL blocking delay.
stream reconfiguration => to save memory and be able to re-use stream numbers, and to realize the role of a FIN (stream reset = FIN)
know what's going on => yes, but this is an application requirement ... the applications on both sides must be able to handle this. E.g., a server written over a TAPS system could just listen on all protocols, including streams, and get whatever kind of Connection (including, possibly, one that's really only a stream) - and then answer on it (I actually tested exactly this with NEATPy). This server can handle this easily. Another server could be a native TCP server, certainly not expecting SCTP, let alone Connections riding on streams - this server could not handle this. The client application, when connecting, must know what it's doing. I can make a PR to explain these matters in the text.
