### ISSUE TITLE
Transport system -> Transport Services system?

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#712]
# Configuration-time errors

"The transport system should have a list of supported protocols available"... I think this means that the TAPS implementation does this, not that the kernel has any tabular notion of transport properties. If so, I have further suggestions for the wording here.

**Comment by mwelzl** [comment]
Yes; I think we had once agreed that this should be "Transport Services system" everywhere, and we (or at least I) have been sloppy with this in the API and Implementation drafts. Thanks, this comment makes it clear to me why it's important to use this term correctly.
