### ISSUE TITLE
"Racing"

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#714]
Is "racing" really the right term? It might be a term of art that applies even in cases like this, but many of the relationships between different branches in the tree are based on preference rather than lowest latency. I don't feel strongly about this, but I don't know if this has been brought up yet, so I figured I'd mention it.

**Comment by mwelzl** [comment]
I agree that it may seem a bit misleading, but I think it's ok - it's just the word we use for it, and the term and how we use it is quite clearly defined in the Architecture draft, section 4.2.2. Just my 2c

**Comment by gorryfair** [comment]
I like "racing" - it's just a term....

**Comment by britram** [comment]
Racing is defined in the architecture document; add a reference back there.
