### ISSUE TITLE
Use of protocol, protocol stack

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#715]
Throughout the document, the term "protocol" is used in lots of different ways. In some cases, it clearly refers to the underlying transport. In other places, it refers to the top-level protocol that the application directly interacts with. In yet other places, it seems to refer to the whole protocol stack, sometimes including the framers. I feel like the document would benefit from a scrub of these usages, and maybe even a glossary describing what exactly is meant by these terms.

**Comment by britram** [comment]
Use Protocol Stack and Protocol Instance from section 4.2 of Arch; I'll do this on my review pass.

**Comment by britram** [comment]
Taking Protocol Stack to mean a whole stack of Instances, Protocol Instance to be a single protocol with an instantiated Stack, and Protocol to mean the protocol without referring to a specific instance within a Connection, then the state of the document after #1025 is semantically correct, if a little ugly, in my estimation.

I'd suggest s/Protocol Stack/protocol stack/ everywhere, though. I don't thing the Very Important Casing makes the document readable or clears up any terminological confusion about what a protocol stack is.
