### ISSUE TITLE
Partial final message

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#717]
Under

# Receiving Messages

the doc says:

> If a Connection becomes finished before a requested Receive action can be satisfied, the implementation should **deliver any partial Message content outstanding**, or if none is available, an indication that there will be no more received Messages.

Emphasis mine. This is a key enabler of truncation attacks, so the interface should only do this if the application is well aware of the implications of receiving partial messages and/or if the partial nature of the message is made clear to the application.

**Comment by tfpauly** [comment]
Should go into API security considerations to tell apps to be careful to not assume that when a connection closes that their received data was complete and/or well-formed.
