### ISSUE TITLE
Align Connection Group terminology in the Architecture with the API

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#721]
Connection Groups used to be about state and context sharing as well as entanglement. Now it's about entanglement. We need to rename Connection Groups ("connection contexts"?) in the architecture to replace the existing "group" concept, and to retain "connection group" in the API for entanglement.

**Comment by gorryfair** [comment]
Seems like this could be 360 degrees of rotation in our thinking? (which could be OK, NEAT was written to specify both contexts and flow groups). Let's try some definitions here and see if we converge...

**Comment by abrunstrom** [comment]
I think #723 brings this back in synch again so no need to rename, possibly the last part of this section in architecture should be removed though as we do not have fine-grained control

> The interface to specify a Connection Group can expose fine-grained tuning for which properties and cached state is allowed to be shared with other Connections. For example, an application might want to allow sharing TCP Fast Open cookies across groups, but not TLS session state.
