### ISSUE TITLE
Is it time for QUIC?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#726]
QUIC beat TAPS to the RFC Ed queue. Should the implementation draft provide a specific considerations sections for QUIC?

In my mental model of TAPS, providing a common API for QUIC implementations is one of the main reasons for TAPS adoption.

**Comment by gorryfair** [comment]
I'm not sure.... here's why: QUIC hasn't yet been around long by API standards, and although I do have hopes, it's clearly going to be a while before QUIC's API is at the same maturity, and I'd hate to hold-up TAPS while we get that perfected. Would it be worth considering opening and "quick-ly" adopting an ID specifically to do this?

**Comment by abrunstrom** [comment]
I think what we agreed before was to stick to the protocols from RFC8303 for the implementation draft and that other protocols, including QUIC, would be covered in their own mapping documents. I think that is still a good decision.

**Comment by tfpauly** [comment]
I believe we had previously decided to use the mapping documents, as @abrunstrom indicates. Marking as such.

**Comment by tfpauly** [comment]
See https://github.com/tfpauly/draft-taps-quic-mapping

**Comment by britram** [comment]
I suspect that the existence of draft-(pauly-)taps-quic-mapping closes this issue in the affirmative.
