### ISSUE TITLE
Closing state not defined

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#731]
The Closing state is mentioned in the interface draft, but is not defined anywhere as far as I can tell. The state machine diagram includes only Establishing, Established, and Closed.

**Comment by mwelzl** [comment]
Great catch, thanks!

Judging from the outcome in this discussion:
https://github.com/ietf-tapswg/api-drafts/issues/182
...this sounds like an omission in the state machine diagram.
