### ISSUE TITLE
Is the "candidate tree" concept actually normative?

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#743]
Section 4 paragraph 3: "This document structures candidates for racing as a tree". This statement is true, but it doesn't say whether this structure is a necessary outcome of the architecture and the design of the interface, or merely a terminological convention that makes it much easier to discuss. I think it's the latter.  

At the least, this sentence should be clarified to make it clear that the tree structure in section 4 (and subsequent) is terminological, not normative. To make this clearer, I'd also create a new "operations on candidate trees" sections, containing sections 4.1.2, 4.1.3, 4.1.4, and 4.1.5.

**Comment by tfpauly** [comment]
Clarify that this document uses tree terminology, and that implementations can, but don't need to, reflect that in their data structures.
