### ISSUE TITLE
mutability of Preconnection objects is unclear (Sec 2)

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#744]
Preconnections are mutable, until they are not. The second paragraph of section 2 states "bundles of properties an application can both read and write", which seems to conflict with this. Para should lead with the fact of mutable mutability over the preconnection lifecycle, not "is mutable".

**Comment by tfpauly** [comment]
The Connection/Listener makes a deep copy that is now immutable, but the original object is still mutable.

**Comment by tfpauly** [comment]
`the implementation should ensure that the copy of the properties held by the Connection or Listener is immutable.`

`the implementation should ensure that the copy of the properties held by the Connection or Listener is not modified by changes the application makes to the original Preconnection object.`
