### ISSUE TITLE
Editorial issues on 5.1.1. Message Properties

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#746]
I believe these are all editorial.

First, this list needs some front matter: "protocols should implement each of the following Message Properties on send as follows" or similar.

- "Ordered" should state that protocols that do not support configurable ordering may ignore the property.
- "Final" should note that it is not mandatory to close the connection after a Final message.
- "Corruption Protection Length" should note that it can be ignored basically everywhere but UDP-Lite. 

One open question: is it an error to send a Message after a Final message, and does the protocol implementation need to handle this itself?

**Comment by gorryfair** [comment]
... "Corruption Protection Length" should note that it can be ignored basically everywhere but UDP-Lite. ... In protocols such as UDP-Lite, various tunnels would, DCCP allows, etc.

**Comment by abrunstrom** [comment]
I think it should be an error to send a Message after a Final message and the implementation of the transport services system should handle it. If it is not an error, then it will fail sometimes and sometimes not depending on if the connection is closed or not, that seems less useful to me.
