### ISSUE TITLE
What if there's no context switch penalty for sending messages? (Sec 5.1.2)

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#749]
Section 5.1.2: "the implementation should hold off on processing Messages until the batch is complete" assumes that there is indeed a context-switch penalty. Batch semantics are only for hints to the implementation/protocol stack, and this advice only applies when that hint allows the stack to reduce context switch penalty. Correct?

(If so, this should be noted explicitly)

**Comment by abrunstrom** [comment]
Agreed, I think your text reads better @gorryfair, should it be "... defer the processing of Messages ..." though? I think it also solves the question from @britram as it is now expressed as an opportunity for the implementation.
