### ISSUE TITLE
Framer changes and send/receive buffers (Sec 6.1)

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#750]
Dynamic framer add and passthrough (last two paragraphs of section 6.1) assume synchronous operation; what happens to bytes in the send/receive buffers when the framer stack changes? 

There either needs to be an explicit mutex here (allowing the framer/implementation to lock the buffers at the exact point the framer change happens, not allowing any bytes to be processed while the dynamic framer decision is made), or some way to annotate in a buffer the replay point after which a dynamic reframing is necessary.

Are we going to leave this up to implementors to figure out, or should we point out that here be dragons?

**Comment by tfpauly** [comment]
We should clarify that these operations within the data path of the stack should be synchronized.
