### ISSUE TITLE
Nit: Section 3.1: No such protocol…

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#753]
I’ll argue this “but no such protocol is available on the host running the transport system”
 is asking for a feature, so I think the text ought to read:
“but no such feature is available in any protocol  the host running the transport system”

**Comment by tfpauly** [comment]
"but no protocol available on the host offers such a feature"

**Comment by gorryfair** [comment]
This was fixed in the already merged PR.
