### ISSUE TITLE
Structuring Options as a Tree?: what is an option?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#756]
“4.1.2. Structuring Options as a Tree”
- I don’t like “options” on its own, I think this needs some other word with it!
- what is an option v. an connection attempt? 
“When an implementation responsible for connection establishment needs to consider multiple options,”
…or is something optional here (v. what is meant by 4.1.1.3.3)?
… or actually is this “Alternatives for Structuring as a Tree”? 
 (help me please!)

**Comment by tfpauly** [comment]
Can we do this in #743 ?
