### ISSUE TITLE
Nit: should be unreliably transmitted.

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#757]
I was bound to complain that we don't WANT to be more unreliable,...
"then the Message should be unreliably transmitted."
Can we say:
..."then the Message should be sent using an unreliable transport."

**Comment by abrunstrom** [comment]
Clearly better, but perhaps "unreliable transport" is also not the best? Would "then the Message should be sent without any reliability guarantees" be better?

**Comment by gorryfair** [comment]
Much better - now perfect!!!

**Comment by gorryfair** [comment]
See PR: Not unreliable, but no reliability guarantees. #837
