### ISSUE TITLE
Should resolve() have a callback?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#759]
I might be confused, but resolve() in Sec 5.3 of -api (Rendezvous) sure sounds like something that is asynchronous and needs a callback. Or is this just the stack's instantaneous view of these addresses?

**Comment by mwelzl** [comment]
Quote from the same section:

> If successful, the Rendezvous() Action returns a Connection object via a RendezvousDone<> Event:
> Preconnection -> RendezvousDone<Connection>

and further down, after some text introducing it:
> Preconnection -> EstablishmentError<reason?>

Did you just miss these, or were you expecting something more?

**Comment by martinduke** [comment]
Oof, I just missed it.
