### ISSUE TITLE
Can you close a Preconnection?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#762]
From reading -api I am not certain of the lifecycle of preconnections?

Is it
-Generate preconnection
- initiate() or listen()
- preconnection is immediately destroyed?

or
-Generate preconnection
- initiate() or listen()
- initiate()/listen()
- ...

Either way, there ought to be a way for taps to throw away this state, either because we never called initiate/listen (1st case) or we're done creating new connections (2nd case).

Or is TAPS not holding any state, with the application fully responsible for holding the object? I'm playing with treating connections and preconnections as socket-style file descriptors, and that model won't work without a preconnection.destroy() or whatever. But maybe that model is just wrong!

**Comment by tfpauly** [comment]
The preconnection is reusable for many initiate() calls.

We may want to mention something in Appendix A (https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#section-appendix.a) about the fact that if you're in C, you'll need to free your objects.
