### ISSUE TITLE
 Is Appendix A  actually implementation?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#772]
Question: I just wonder if Appendix A. actually more  implementation, rather than API (interface). 

If more needs to be said in future, wouldn’t this appear as implementation details, so maybe the annexe might better be a part of that?

**Comment by squarooticus** [comment]
As I've said previously, I do not think so. "Implementation" for these drafts really refers to how a working Transport Services system should behave, while "interface" refers to how a user should interact with a Transport Services implementation. The type information contained in this appendix is part of the description of the Transport Services interface.

**Comment by mwelzl** [comment]
Yes, to me this appendix is a small collection of hints on how to make the step from this abstract API to a concrete API, whereas the implementation draft is about what happens underneath.

**Comment by gorryfair** [comment]
Ok, let’s close this question, the text is needed somewhere, so it can be here.

Gorry
