### ISSUE TITLE
What is "entangled"?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#774]
I don’t actually understand the difference between a connection in a Connection Group and an “entangled connection” ? 

Both terms are used in API, but in different ways (possibly by different authors) - do we really really need the word “entangled”??  if we do we need, can we define and explain this.

**Comment by mwelzl** [comment]
I think that having the word is good as it indicates a deeper relationship than mere "grouping". Just based on terms, I'd (correctly) imagine that I can define priorities between members of a group, and that they somehow belong together... as in: Close with a common call, etc. ... but I don't think that I would expect, just from this term, that changing a property on one of them affects all the others.  Hence the phrasing: "The connections within a group are 'entangled' with each other".
However, I agree that in most other places, we should talk about "groups" instead. I can try to fix this.

**Comment by gorryfair** [comment]
Sounds good - we should add that explanation upfront in the definitions then also?

**Comment by mwelzl** [comment]
Yes, I think so.

**Comment by mwelzl** [comment]
I have addressed this in PR #794. Note that the text interchangeably talked about both Connections and Connection Properties as being "entangled". I have now written this such that the term "entanglement" applies to Connection Properties only, whereas Connections in a group are, well, members of the same Connection Group.
