### ISSUE TITLE
What's a callback?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#775]
We have a “ Terminology and Notation” section, but we don’t define these terms:

Clone: Calling Clone on a Connection yields a group of Connections: the parent Connection on which Clone was called, and a resulting cloned Connection. 

Entangled connection:   if we do we need this term, we should define and explain what is different.

Callback: can we have a one line definition that explains the different with respect to an event that an application can also asynchronously receive.

**Comment by mwelzl** [comment]
I can take care of the first two

**Comment by mwelzl** [comment]
As I looked at this now, I felt that such definitions would seem a bit out of place in the "Terminology and Notation" section; rather, if we need to define it globally, the concepts of Cloning and Entanglement should be defined where we also define what our Connections are, what Transport Properties are, etc.  - and this is in -arch.

Thoughts?

**Comment by gorryfair** [comment]
This isn't need for entangled with the way used in PR #774

**Comment by mwelzl** [comment]
I'm adding the arch label so people notice  :-)

**Comment by tfpauly** [comment]
The one action remaining is defining "callback" within the scope of section 4.3.

**Comment by gorryfair** [comment]
Looks like this will be addressed.
