### ISSUE TITLE
Priority property "represents a hierarchy of priorities"?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#779]
The text reads quire off when it says a priority property represents a hierarchy of priorities:
   This property represents a hierarchy of priorities.  

- Could this better be: ‘A priority property is organised within a hierarchy of priorities. ‘?

**Comment by mwelzl** [comment]
When reading "hierarchy", it's easy to think that there may be priority sub-groups within priority groups, or something of that nature. Yet, this is not the case, it's just a flat priority assignment. Hence, to me, mentioning "hierarchy" here is misleading altogether. Therefore, I think we'd be much better off removing this sentence, i.e. replacing:
> This property represents a hierarchy of priorities. It can specify the priority of a Message, relative to other Messages sent over the same Connection.
with
> This property specifies the priority of a Message, relative to other Messages sent over the same Connection.
