### ISSUE TITLE
Are message framers entangled in a connection group?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#788]
This is not fully clear from section 5.4., however, if connections in a group are each QUIC streams, I think it should be possible to use different framers on each stream. So it might be okay that a framers is copied when clone is called but changing a framer on one connection should not change the framer on the other connection in a group...?

**Comment by mirjak** [comment]
Also an related editorial comment (that could be addressed in the same PR eventually): this section on groups only at the very end has a paragraph starting with "Note that calling Clone() can result in on-the-wire signaling..." which kind of explains that groups are supposed to be used for multistream protocol but can also be mapped to separate connection if the protocol doesn't not support multiplexing of stream on one connection. I think this information should be added at the very beginning of this section.

**Comment by mirjak** [comment]
Actually, now looking at the framer section, I guess you would rather like to already set the new framer before you clone a connection...?

**Comment by mwelzl** [comment]
I agree with everything you say here; about your last suggestion, maybe a framer should be an optional argument of the clone call?
