### ISSUE TITLE
Priority for single stream

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#790]
Section 7.2.6. says " for example, if a transport stack that only provides a single in-order reliable stream is selected, prioritization information can only be ignored."

I don't think this is entirely true as you can still decide in which order you schedule independent messages on one stream.

**Comment by mwelzl** [comment]
I don't get this. The sentence says "in-order". Scheduling them from buffer A into buffer B in accordance with priorities won't help when everything leaves buffer B in a fixed sequence.

**Comment by gorryfair** [comment]
How about a less complex sentence: ..."for example, if the transport system selects a stack that only provides a single in-order reliable stream, the prioritization information is ignored."

**Comment by mirjak** [comment]
message on the taps "layer" are independent. so the order an application calls send on these message doesn't have to be the same order the messages are send on an "in-order stream"

**Comment by mwelzl** [comment]
Oh, now I see what you mean. Hmmm...  looking at the text, it seems that we could just delete this sentence and the problem is solved?

**Comment by abrunstrom** [comment]
I think what was intended with the example was to show that the set priorities may not have any effect. Perhaps we should instead just add "and the set priorities may not have any effect" if we want to be explicit? Removing it also works though.

**Comment by gorryfair** [comment]
I think just add that!

**Comment by mwelzl** [comment]
I'm for removing it (I think I wrote this sentence btw :-)  ).  Giving this example just throws off someone who thinks about this case like Mirja did here - even if we say "may not apply", the reader may (correctly) think "but why, in this case they CAN well apply!". So I don't find that helpful.

For context, the full current statement is:
> A Transport Services system gives no guarantees about how its expression of relative priorities will be realized; for example, if a transport stack that only provides a single in-order reliable stream is selected, prioritization information can only be ignored. However, the Transport Services system will seek to ensure that performance of relatively-prioritized connections and messages is not worse with respect to those connections and messages than an equivalent configuration in which all prioritization properties are left at their defaults.

and I believe that we say everything we need to say if we just change this into:

> A Transport Services system gives no guarantees about how its expression of relative priorities will be realized. However, the Transport Services system will seek to ensure that performance of relatively-prioritized connections and messages is not worse with respect to those connections and messages than an equivalent configuration in which all prioritization properties are left at their defaults.
