### ISSUE TITLE
be more concrete about receiving

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#791]
Reading 7.3.2 I found the concepts there quite abstract. I think it would really help to be a bit more specific and e.g. take UDP and TCP as examples basically saying some like: as UDP is consider a message based protocol, each received datagram will trigger receive() of a complete message. As TCP is stream-based all TCP segments will be delivered by ReceivedPartial().

**Comment by tfpauly** [comment]
My impression here is that we could use some examples for different protocols for sending and receiving (for messages, datagrams, and raw streams).

This could be a 7.4 Examples section.

**Comment by gorryfair** [comment]
Do we need to do this - can we just close this?

**Comment by tfpauly** [comment]
I think it's still valuable to have an example of ReceivedPartial somewhere.

**Comment by csperkins** [comment]
The ReceivedPartial example is good. I think we may need clarification that Received can support object-based rather than just byte-array-based responses.
