### ISSUE TITLE
S1.1: Definition of Tuple refers to property before it is defined

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#798]
S1.1, Definition of Tuple refers to property before it is defined

**Comment by mwelzl** [comment]
This must be about the sentence: "The composition of types and their order depends on the property and is fixed for the property."

I wonder if this could be addressed by just removing this sentence? I'm not sure it's really needed.

**Comment by britram** [comment]
Yep. Will remove the sentence.
