### ISSUE TITLE
S4: Why are only SecurityParameters optional in NewPreconnection?

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#804]
For other parameters you have to pass in an empty object if you do not want to set anything but not for SecurityParameters. Unclear why the parameters are treated differently?

**Comment by tfpauly** [comment]
- Make security parameters non-optional
- Remove "Transport Properties MUST always be specified while security parameters are OPTIONAL."
- Define that there is an implementation-specific security parameter to disable security
