### ISSUE TITLE
Be more clear about Setting Message Properties on Preconnections and Connections

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#808]
In 3.2 it is clear that you can set Message Properties on Connections and Preconnections, but the rest of the document is not very clear about this.

In 4.2 for instance the text only talks about setting Selection Properties and Connection Properties on PreConnections. 

In 7.1.3 the text says "Connection Properties describe the default behavior for all Messages on a Connection". But I think that Message Properties set on a Connection or PreConnection may also describe the default behavior so this relationship should be clarified. Also, the Message Property defaults given for Properties that do not depend on other Properties sets the defaults for all Messages in a Connection I assume? I also assume that a Message Property set on a Message Context overrides a Message Property set on a PreConnection or Connection, but this is also not specified.

In 5.4. Connection Groups, I assume that setting Message Properties on a Connection applies to all Connections in the Connection Group? This is not clear.

**Comment by tfpauly** [comment]
In general, I agree. If you set a message property dynamically on a connection, though, I don't think it would affect the group—I could have one stream in a multiplexed protocol have separate behavior, such as priority.

**Comment by mwelzl** [comment]
+1 to tfpauly. But this is already written in 5.4, maybe you missed it (Anna)?   "Message Properties are also not entangled. For example, changing Lifetime (see Section 7.1.3.1) of a Message will only affect a single Message on a single Connection."

**Comment by abrunstrom** [comment]
I am fine with an update of a Message Property to a connection applying only to that connection. Priority is not a good example as it is already a special case, but my main issue was that we need to be more clear about the behavior in the specification. 

@mwelzl the issue is about setting a Message Property on a Connection. The text you refer to talk about setting Message Properties on a message. You could interpret the first part as a general statement, but the way the text is structured it is easy to think it refers to setting Message Properties on a message so I think we should be explicit also about setting Message Properties on a Connection. Could be a second example.

**Comment by abrunstrom** [comment]
So after looking at the text again, I think the example talking about setting Message Properties on a message should be removed, see comment in the pull request.
