### ISSUE TITLE
S4.2.5. Relation to UDP for Use of 0-RTT Session Establishment and use of safelyReplayable

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#809]
The text says 
> Note that disabling this property has no effect for protocols that are not connection-oriented and do not protect against duplicated messages, e.g., UDP.

What does disabling mean? Does this mean mean that it is valid to set this property to "Prohibit" but still set "safelyReplayable" to "Require" on the PreConnection. Should that not be an error?

This is also related to #780. The use of safelyReplayable for both reliable and unreliable services makes the text a bit confusing. Would it not be sufficient to state that if you do not Require Reliable Data Transfer you have to be prepared to deal with duplication?

**Comment by tfpauly** [comment]
We should remove this sentence in 4.2.5:

```
Note that disabling this property has no effect for protocols that are not connection-oriented and do not protect against duplicated messages, e.g., UDP.
```
