### ISSUE TITLE
S4.2.7, S4.2.8 Full Checksum Coverage - Names of the Properties do not seem intutive

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#810]
Why is the name not rather something like perMsgChecksumFullSend?

**Comment by gorryfair** [comment]
Happy with a change if making this more consistent.

**Comment by gorryfair** [comment]
There are some related changes in  #839

**Comment by gorryfair** [comment]
@abrunstrom :  Did the merged PR 839 happen to address this? - If not please make a PR.

**Comment by abrunstrom** [comment]
@gorryfair PR 839 updated the name, but still found it confusing so made a PR.

**Comment by gorryfair** [comment]
See review.
