### ISSUE TITLE
S4.2.14. Multipath Transport - why different?

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#812]
I know we have discussed Multipath Transport many times, but when reading is seems strange when you get to Multipath Transport and here there is no option to "Require" this property, only to "Prefer" it. We should at least say why. It is perhaps intuitive that you do not need to distinguish between Avoid and Prohibit, but not why Require would not be useful.

**Comment by tfpauly** [comment]
Add a sentence after this to explain why "require" wouldn't make sense:

```
Enumeration values other than "Disabled" are interpreted as a preference for choosing protocols that can make use of multiple paths. 
```
