### ISSUE TITLE
S7.3.2.1. - send replies and map responses to their requests

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#815]
The text below is a bit confusing as there are no details about how to to send replies and map responses to their requests in Section 7.1.1. This can be easily fixed by clarifying what Section 7.1.1 provides details on. But I was also wondering if there should be some more details on how to send replies and map responses to their requests somewhere?

> The messageContext is provided to enable retrieving metadata about the message and referring to the message, e.g., to send replies and map responses to their requests. See Section 7.1.1 for details.

**Comment by britram** [comment]
Note: this will be in §9.3.2.1. after #869 merge.

**Comment by philsbln** [comment]
Is seems the concept of mapping requests/replies has been fully eliminated. So just removing this part of the example.
