### ISSUE TITLE
S7.3.3.1. UDP(-Lite)-specific Property: ECN - Motivation

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#817]
I think this protocol specific Property is only included because it comes from RFC8923? Should be made clear in the text.

**Comment by mwelzl** [comment]
Yes.
Just for clarification: RFC 8923 takes this from RFC 8304, which takes it from RFC 8085.

**Comment by gorryfair** [comment]
How about something like: " [RFC8293] following the guidance in [RFC8085] "?
