### ISSUE TITLE
Convenience Functions - options rather than requirements

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#820]
The appendix text about convenience functions talks about "implementations should" provide various things. This reads strangely to me. I think these are not requirements and the text should be more in the form of it can be useful for implementations to provide various things.

**Comment by gorryfair** [comment]
How about: " implementations can provide special actions for adding each preference level i.e, TransportProperties.Set(some_property, avoid) would be equivalent to TransportProperties.Avoid(some_property):..."
