### ISSUE TITLE
Capacity profile discussion in 4.1.3 doesn't match capacity profile in the API draft

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#835]
The Capacity Profile in the API draft (now) lists these possible choices: Default, Scavenger, Low Latency/Interactive, Low Latency/Non-Interactive, Constant-Rate Streaming and Capacity-Seeking.

The text in section 4.1.3 only discusses Scavenger, Low Latency/Interactive, and Constant-Rate Streaming.

**Comment by gorryfair** [comment]
Aha - I could offer to align the Capacity Profile classes?

**Comment by gorryfair** [comment]
See a PR to align Capacity profile with API #858

**Comment by gorryfair** [comment]
Resolved
