### ISSUE TITLE
How does the application express preference for derived endpoints?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#842]
In the impl draft, I'm supposed to build a tree based on, in order

(1) "path": AFAICT this means "interface". The -api draft provides in interface preference framework in 4.2.11. (BTW if it really means interface maybe we should say 'interface').

(2) Protocol: almost all of 4.2 in -api explains how to express this. (with an assist in -impl 4.1.3 explaining how to handle PREFER vs. AVOID)

(3) "derived endpoint" I gather this is basically multiple addresses coming back from remote endpoint resolution. But where is the construct in -api that allows applications to express a preference here?

**Comment by tfpauly** [comment]
I'm not sure we want to add anything to the API here. There are existing preferences that can bias towards IPv6, such as preferring or requiring `useTemporaryLocalAddress`. I think we can just detail that in the implementation draft.
