### ISSUE TITLE
Where are events sent?

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/api-drafts#843]
In the interface draft, Section 1.1:
```
*  An Object sends an Event:
         Object -> Event<>
```
Where is the event sent? Perhaps `An Object generates an Event that needs to be processed by the application`?

**Comment by mwelzl** [comment]
Interim: add "to the application"

**Comment by gorryfair** [comment]
Could alternatively say the same another way around: "Applications can use these events..." (i.e. avoid saying *only* applications do this).

**Comment by MaxF12** [comment]
Section 6 in impl-draft has the parts where the framer objects receive events. There is no terminology section in implementation, so not sure if the terminology section in API should cover it as well.

**Comment by britram** [comment]
We already say this in the intro text to this section, but I can tweak the structure and add some additional text to make this more clear.
