### ISSUE TITLE
Endpoint aliases and protocols

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/api-drafts#854]
Interface, section 4.1.2:
```
   In order to scope an alias to a specific transport protocol, an
   Endpoint can specify a protocol identifier.  These identifiers MUST
   only be set for aliases.

   RemoteSpecifier.WithProtocol(QUIC)
```
Why the limitation to aliases? Specifying a protocol might limit the utility of connection racing, so should perhaps be discouraged, but does it break anything to specify a protocol for a non-alias Endpoint?

**Comment by mwelzl** [comment]
Interim: suggest to remove the second sentence.
