### ISSUE TITLE
Add examples for ASM and SSM

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#874]
In the multicast endpoint section, we should have explicit examples for patterns of ASM and SSM.

Listen(multicast address, port, interface)
Get a connection from a specific remote endpoint
Initiate a connection back to talk to that endpoint,
etc

**Comment by tfpauly** [comment]
We should mention the IGMP joining in Implementation, etc too

**Comment by gorryfair** [comment]
If we haven't done so, should note than one process may receive from the same address with SO_REUSEADDR so that every incoming multicast or broadcast UDP datagram destined to the shared port is delivered to all.

**Comment by tfpauly** [comment]
@gorryfair I think the other bits about reuse address belong in implementation, filed #876

**Comment by tfpauly** [comment]
Interim: waiting on @csperkins

**Comment by gorryfair** [comment]
CSP to propose a PR to see if this needs to be taken in a different direction.
