### ISSUE TITLE
ART-ART: RFC 2119 Language in Arch

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#889]
In 3.1 consider "It is important for applications using a Transport Services
system to be robust to the" instead of using REQUIRED. 

At 3.2, if this were a requirements document for the Transport Services system,
the SHOULD in the first paragraph might make sense. But if its an architecture
document, or better, an overview and introduction. It would be better to simply
say "is" rather than SHOULD. (And in a requirements document, I would argue
that this SHOULD should be a MUST).

**Comment by gorryfair** [comment]
I think 3.1 probably needs a little more unpacking,  this is a little abstarct in what is needed to say required: "Applications using a Transport Services system interface are REQUIRED to be robust to the automated selection provided by the system, where the automated selection is constrained by the requirements and preferences expressed by the application."  
We could therefore loose the /REQUIRED/.

I'll suggest this as a starting point for 3.1 - the topic here is not an interoperability requirement of the protocol on the wire, it is about whether the method needs to have the feature to satisfy the design goals: "It is therefore is RECOMMENDED that a Transport Services system permits more specialized protocol features to be used."

**Comment by britram** [comment]
this will be fixed with any reasonable fix to #879
