### ISSUE TITLE
ART-ART: Special values in parameters

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#896]
I cringe at systems that define Integers to be integers and some other
enumerated things ("special values"). Is it necessary to define things this
way? I understand it's currently typical to have this behavior in the APIs of
the protocols this system is attempting to abstract, but is it impossible to
stop propagating that kind of type confusion? This API could move the things
special values are being used for into separate arguments for example.

**Comment by britram** [comment]
This only appears to be used for checksum coverage; don't overload integer for this application.

**Comment by britram** [comment]
Use type enumerations instead. Some languages let you do this. Otherwise you just pick an out-of-range integern.

**Comment by theri** [comment]
The "special value" also shows up for numeric in 8.1.3, 8.1.4, 8.1.8 and 8.1.9
