### ISSUE TITLE
ART-ART: Remove first sentence of API summary

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#899]
As you can tell, I don't think the documents do what the first sentence of the
API summary claims. This document would not lose anything if you deleted the
sentence.

**Comment by britram** [comment]
Agreed, we can lose this sentence.

**Comment by gorryfair** [comment]
Why? Removing this makes no sense to me.

**Comment by mwelzl** [comment]
For one, it's redundant - it only repeats what we already say earlier twice.
