### ISSUE TITLE
ART-ART: Endpoint cannot have multiple identifiers of a same type set

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#908]
I think there's a need for more discussion and clarity around the restriction
that "An Endpoint cannot have multiple identifiers of a same type set." Why
not? You effectively are letting the endpoint have (potentially) multiple IP
addresses when you create it with an identifier that is a DNS name. This feels
like an artificial, inconsistent, restriction given the rest of the document
(look at the 3rd paragraph of 6.1).

**Comment by britram** [comment]
I think the right thing to do is to delete "An Endpoint cannot have multiple identifiers of a same type set. That is, an endpoint cannot have two IP addresses specified. Two separate IP addresses are represented as two Endpoint Objects."; if you agree, please do so.

**Comment by tfpauly** [comment]
I don't agree that we should delete this. This has been a quite important point in our experience with the API. To make the system work well, resolution should be handled by the TAPS system. If you want to connect by a hostname, provide the hostname—don't try to cache the addresses (often incorrectly) and just pass the same set of addresses again.

Note that this doesn't stop _multiple_ addresses from being added to a preconnection. We have this example:

```
Preconnection.AddRemote([]RemoteEndpoint)
```

Just, one endpoint is a single identifier. You can pass multiple if you want multiple.

**Comment by tfpauly** [comment]
@britram
