### ISSUE TITLE
ART-ART: WithServiceName

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#909]
Would there be any benefit of having something like "WithServiceName" to
qualify a specifier for use with NAPTR/SRV? Or is the thinking that the
resolution of the thing handed down through WithHostname is restricted to
A/AAAA?

**Comment by britram** [comment]
yes, probably.

**Comment by tfpauly** [comment]
We do have this for mDNS services in Network.framework, and internally have tested with SRV. These are useful indeed.

**Comment by tfpauly** [comment]
Interim: Yes, this is a nice solution. Let's mention how to use withService for SRV types in the text.
