### ISSUE TITLE
ART-ART: Grouping from remote

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#913]
I'll have to read the document yet another time, perhaps, but after the few
times I went through it for this review, I'm still not clear on how/whether
connections are grouped because of actions from the remote end(s). If so, how
does the user learn about the grouping? Does it have to poll
Connection.GroupedConnections() every time its told of a new Connection?

**Comment by gorryfair** [comment]
Yes and "aha" - I am happy to add that a connection group is a concept at the sender to arch, I add in a pending PR to address "cloning".  I suggest MW does this for interface.
