### ISSUE TITLE
secdir: s6: MUST/MAY for Local and Remote Endpoint requirements

### ISSUE THREAD

**Issue by seanturner** [ietf-tapswg/api-drafts#973]
0 from this [secdir review](https://mailarchive.ietf.org/arch/msg/secdir/yUaaas7vohCXnERvfU7DvlILh4U/). Note that in that review I really was not very clear about the issue, I tried to do better here.

The MUST/MAY combination of the following Local Endpoint requirement:

    At least one Local Endpoint MUST be specified if the Preconnection is
    used to Listen() for incoming Connections, but the list of Local Endpoints MAY be
    empty if the Preconnection is used to Initiate() connections.

and Remote Endpoint requirement:

    At least one Remote Endpoint MUST be specified if the Preconnection is
    used to Initiate() Connections, but the list of Remote Endpoints MAY be
    empty if the Preconnection is used to Listen() for incoming Connections.

It says you MUST have a value but then it says maybe not under this one condition. Isn't the MUST then a SHOULD? I.e., you really, really need to do this unless there's this one condition and then it's okay to not set it? I realize I may be dancing on a pinhead here so I will bow to collective wisdom of the group.

**Comment by tfpauly** [comment]
I don't think this change is necessarily correct. The logic is:

If Listener: MUST have local endpoint, MAY have remote
If initiator: MUST have remote endpoint, MAY have local
