### ISSUE TITLE
secdir: s6.3.2: Certificate Path Validation?

### ISSUE THREAD

**Issue by seanturner** [ietf-tapswg/api-drafts#977]
2 from this [secdir review](https://mailarchive.ietf.org/arch/msg/secdir/yUaaas7vohCXnERvfU7DvlILh4U/).

Is s6.3.2 supposed to be about certificate path validation? It might be worth explicit saying that and providing a reference to RFC 5280?

Note that I do not have a proposed solution (yet).

**Comment by tfpauly** [comment]
Yes, we should reference RFC 5280 here.
