### ISSUE TITLE
secdir: s8.1.1: FullCoverage Special Value

### ISSUE THREAD

**Issue by seanturner** [ietf-tapswg/api-drafts#978]
3 from this [secdir review](https://mailarchive.ietf.org/arch/msg/secdir/yUaaas7vohCXnERvfU7DvlILh4U/).

This issue was addressed via #964. I included this only for completeness. Close at your leisure.

I read this definition a bunch. Are there two special values? The
Type line says “Full Coverage” is special, but then the description says “0” is
special too. Maybe look at s91.3.6 for inspiration?

**Comment by gorryfair** [comment]
This issue on coverage is resolved in the latest.
