### ISSUE TITLE
secdir: s9.1.3.2: Priority default value

### ISSUE THREAD

**Issue by seanturner** [ietf-tapswg/api-drafts#993]
11 from this [secdir review](https://mailarchive.ietf.org/arch/msg/secdir/yUaaas7vohCXnERvfU7DvlILh4U/).

Why 100?

**Comment by mwelzl** [comment]
Why not?  We needed to pick something... and I thought that picking a value that allows lower and higher values to come after with some granularity would be useful.

With a more old-fashioned programmer's hat on, I would have picked something like 127  :-)

Anyway: does it need a reason? Is it a bad choice?

**Comment by tfpauly** [comment]
Interim: no grand thinking, but seems fine =) Gotta choose something!
