### ISSUE TITLE
secdir: Security Parameters

### ISSUE THREAD

**Issue by seanturner** [ietf-tapswg/api-drafts#999]
I guess it's hard to know all of the parameters that might need to be set for a particular protocol, but since TLS has PSK modes should those be included? There are three defined: two in [RFC8446](https://datatracker.ietf.org/doc/rfc8446/) and one in [RFC8773](https://datatracker.ietf.org/doc/rfc8773/).

**Comment by seanturner** [comment]
It is/was. If you're importing a PSK (see 6.3.1. of draft-ietf-taps-interface) do you need to also set the PSK mode or at least mention you might need to?

**Comment by tfpauly** [comment]
Thanks, will do.
